### ISSUE TITLE
Enable-AzureADDirectoryRole missing parameter DirectoryRole

### ISSUE THREAD

**Issue by msevastian** [Azure/azure-docs-powershell-azuread#103]
Hi Team!
According to doc https://docs.microsoft.com/en-us/powershell/module/Azuread/Enable-AzureADDirectoryRole?view=azureadps-2.0
Cmdlet Enable-AzureADDirectoryRole missing parameter DirectoryRole. While trying to use RoleTemplateId parameter I'm getting

`Enable-AzureADDirectoryRole : Error occurred while executing ActivateDirectoryRole
Code: Request_BadRequest
Message: Instantiation of a 'DirectoryRole' object rerepresenting the implicit user role is not currently supported.
RequestId: 59d8442c-6819-4a58-9989-084a640cc7cf
DateTimeStamp: Tue, 30 May 2017 14:49:15 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed`

**Comment by TaraMeyer** [comment]
@msevastian - thank you for reporting the issue.  @RobdeJong - Can you please take a look at this reported issue?  Many thanks!

**Comment by RobdeJong** [comment]
@VinceSmith - can you please look at the reported issue?

Thanks - Rob

**Comment by TaraMeyer** [comment]
@VinceSmith any update on your progress?  Thanks!

**Comment by RobdeJong** [comment]
@msevastian - can you verify you are using the latest version of the PowerShell module?

**Comment by msevastian** [comment]
No success too
![image](https://user-images.githubusercontent.com/28624368/28738661-705a8802-73fd-11e7-8255-cf7de4985322.png)
@RobdeJong as you see I have installed latest available version of Azure AD module
