### ISSUE TITLE
Unable to use Get-AzureADUser cmdlet - Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by stukey** [Azure/azure-docs-powershell-azuread#114]
We've recently stood-up our Azure AD tenant and I've been testing with the Azure AD PowerShell module. I can connect to our tenant without issue using Connect-AzureAD cmdlet. However I am not able to retrieve any Azure AD user or group objects using the cmdlets. Here's what I see when trying the cmdlets:

```
Get-AzureADUser -SearchString "Stuart Test"
Get-AzureADUser : Unexpected character encountered while parsing value: <. Path '', line 0, position 0. At line:1 char:1
+ Get-AzureADUser -SearchString "Stuart Test"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADUser], JsonReaderException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonReaderException,Microsoft.Open.AzureAD16.PowerShell.GetUser
 
Get-AzureADUser -ObjectId "stuart.test@xxx.xxz"
Get-AzureADUser : Unexpected character encountered while parsing value: <. Path '', line 0, position 0.At line:1 char:1
+ Get-AzureADUser -ObjectId "stuart.test@xxx.xxz"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADUser], JsonReaderException
    + FullyQualifiedErrorId : Newtonsoft.Json.JsonReaderException,Microsoft.Open.AzureAD16.PowerShell.GetUser
```
 
I see the same error if searching by ObjectID or using the -Top parameter.

I have installed the AzureAD Module and am running the latest version (2.0.0.115). This is in PowerShell 5 on a Windows 2008 R2 server. 

```
$PSVersionTable
 
Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.36392
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Interestingly I don't have any issues getting users or groups using the old Azure AD v1 PowerShell module (e.g. Get-MSOLUser and Get-MSOLGroup).

Does anybody have any ideas how to trouble-shoot this?

**Comment by TaraMeyer** [comment]
@RobdeJong are you able to help point @stukey (Stuart) in the right direction?

**Comment by RobdeJong** [comment]
I have no idea what is happening here - please contact Microsoft support to figure this one out.

**Comment by TaraMeyer** [comment]
@stukey here's the page I could find on get support for Azure Active Directory:  https://docs.microsoft.com/en-us/azure/active-directory/active-directory-troubleshooting-support-howto

**Comment by stukey** [comment]
@TaraMeyer and @RobdeJong. Thank you both. I will follow the process to open a support issue.

**Comment by TaraMeyer** [comment]
You are very welcome!  Take care @stukey .

**Comment by lyyang-debug** [comment]
Hi @stukey. I meet the same problem. Any suggestion?

**Comment by tony8382** [comment]
Hi @stukey. I meet the same problem. Any suggestion?

**Comment by stukey** [comment]
@tony8382 Unfortunately I do not recall the solution. It just started working for us. Sorry I couldn’t be more help.

**Comment by olam-MCA** [comment]
Same issue for me ...

**Comment by tony8382** [comment]
@olam-MCA  Update to the latest version for the AzureAD Module and try again. 😀
