### ISSUE TITLE
Missing examples for the -Filter parameter

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-docs-powershell-azuread#116]
The help docs for the Get-AzureAD* cmdlets don't include examples and explanation of all the search and filtering options. It's hard to find a working syntax for the -Filter and -SearchString parameters.

**Comment by TaraMeyer** [comment]
@alexandair  thank you for the feedback.  @VinceSmith and @RobdeJong - are either of you able to add examples as requested by Alex?  Thanks!

**Comment by RobdeJong** [comment]
We're working on an overview article for search and filter

**Comment by alexandair** [comment]
Overview article is great. However, useful examples are critical for good user experience. Users expect to get examples built-in when they look for a help.

**Comment by RobdeJong** [comment]
We recently added some examples, will add more later

Thanks,

Rob

**Comment by shivtorov** [comment]
Existing example is wrong (= throws error)
`Get-AzureADUser -Filter "startswith(Title,'Sales')"`

results:

`PS C:\> Get-AzureADUser -Filter "startswith(Title,'Sales')"
Get-AzureADUser : Error occurred while executing GetUsers
Code: Request_UnsupportedQuery
Message: Unsupported method 'StartsWith' in query.
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ Get-AzureADUser -Filter "startswith(Title,'Sales')"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADUser], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.GetUser`
