### ISSUE TITLE
Set-MsolCompanyMultiNationalEnabled - possible Servicetype

### ISSUE THREAD

**Issue by Gpabarth** [Azure/azure-docs-powershell-azuread#142]
![capture2](https://user-images.githubusercontent.com/31070837/29367160-4bb74956-829c-11e7-861f-6f02a2516b2b.PNG)
Hi Team, it would be great to have a list of selectable servicetypes here. Trying to work with SharePoint online but due to the lack of information i'm not able to figure out the correct servicetype naming.

**Comment by TaraMeyer** [comment]
@RobdeJong  have you seen this suggestion?

**Comment by nani85** [comment]
any update on that? i would like to enable the future for Skype and getting the same error..

**Comment by billmath** [comment]
Hi @NatiSayada 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill
