### ISSUE TITLE
ForceChangePasswordOnly is an unexplained parameter

### ISSUE THREAD

**Issue by markwragg** [Azure/azure-docs-powershell-azuread#150]
There is no text in the help of the Set-MsolUserPassword cmdlet explaining the purpose of the `-ForceChangePasswordOnly` parameter and how it differs from `-ForceChangePassword` which is explained: https://github.com/Azure/azure-docs-powershell-azuread/blob/master/Azure%20AD%20Cmdlets/MSOnline/v1/Set-MsolUserPassword.md

Most examples online seem to use both, but it's not explained why this is necessary or what the difference is.

**Comment by TaraMeyer** [comment]
@markwragg thank you for reporting this issue. What version of the module and what specific cmdlets are you referring to?

**Comment by markwragg** [comment]
Sorry Tara, that probably would have been useful. I'm not sure on the module version (this was reported by someone on StackOverflow: https://stackoverflow.com/questions/46149055/postgresql-and-schedule-windows-2012-r2-schedule#comment79267009_46149055) but I would assume the latest. I've updated by initial comment with the help page where the explanation is missing and its the `Set-MsolUserPassword` cmdlet.

**Comment by TaraMeyer** [comment]
Great!  Thank you for the extra info @markwragg!  @RobdeJong - are you, or the PM able to flesh out the description for -ForceChangePasswordOnly parameter in this topic:  https://github.com/Azure/azure-docs-powershell-azuread/blob/master/Azure%20AD%20Cmdlets/MSOnline/v1/Set-MsolUserPassword.md?  Many thanks!

**Comment by TaraMeyer** [comment]
@RobdeJong- can you please take a look at this issue and let us know the best path forward?

**Comment by peterjk** [comment]
@RobdeJong A simple fix would be to add a sentence explaining the -ForceChangePasswordOnly eg
This parameter is used together with -ForceChangePassword to make the user change the current password on the next login.

That said, personally I think a better resolution would be if you could use them separately as it's kind of redundant the way it's done now needing both parameters.

**Comment by landall** [comment]
> @RobdeJong A simple fix would be to add a sentence explaining the -ForceChangePasswordOnly eg
> This parameter is used together with -ForceChangePassword to make the user change the current password on the next login.
> 
> That said, personally I think a better resolution would be if you could use them separately as it's kind of redundant the way it's done now needing both parameters.

I have the same question. What is the different of these two?

**Comment by peterjk** [comment]
> > @RobdeJong A simple fix would be to add a sentence explaining the -ForceChangePasswordOnly eg
> > This parameter is used together with -ForceChangePassword to make the user change the current password on the next login.
> > That said, personally I think a better resolution would be if you could use them separately as it's kind of redundant the way it's done now needing both parameters.
> 
> I have the same question. What is the difference of these two?

The -ForceChangePassword forces the user to set a new password the next time they log in, it also resets the userpassword to a new one that needs to be given to the user before they can log on again.

If you add the -ForceChangePasswordOnly switch the command will not reset the users password so the user can use the old password at next login and you don't need to distribute a new password before they can log in.

Hope this makes the difference clearer.

**Comment by billmath** [comment]
Hi @markwragg 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  I know the information was provided above but it needs to be added to the source code so that it appears in the online documentation.  The cmdlts information online is autogenerated from the source.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill
