### ISSUE TITLE
Ability to return Deleted Users from AzureADUser is missing

### ISSUE THREAD

**Issue by doctorscripto** [Azure/azure-docs-powershell-azuread#151]
In the previous version of MSonline, you could return users that were in the AzureAd Deleted bin.   If necessary you could purge them.   This feature is not presently available to users of this module.  It is needed for Administrators that use MFA as MFA does not work in the MSonline Module.

**Comment by TaraMeyer** [comment]
@RobdeJong -can you please take a look at this issue?

**Comment by WithHolm** [comment]
it has been a loong time since this was asked. any updates?

**Comment by billmath** [comment]
Hi @doctorscripto 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill
