### ISSUE TITLE
Connect-AzureAD - Does not work with ServicePrincipal and password

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-docs-powershell-azuread#154]
## Cmdlet(s)

Connect-AzureAD

## PowerShell Version

4.0

## OS Version

6.3.9600.18728

## Description

Unable to use Service Principal with password - instead of service principal and certificate - as described in the article: https://docs.microsoft.com/en-us/powershell/module/azuread/connect-azuread?view=azureadps-2.0

This should ideally work as Login-AzureRmAccount with ServicePrincipal and Password instead of Certificates.

## Repro script

![image](https://user-images.githubusercontent.com/13054214/31476883-6195019a-aef8-11e7-9778-4d86709b7768.png)

**Comment by cmenzi** [comment]
Currently, it only works with -ApplicationId <SP> and -Thumbprint "<thumb>"

**Comment by billmath** [comment]
Hi @rajaprad 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill
