### ISSUE TITLE
Get-AzureADUser ignores -Erroraction SilentlyContinue

### ISSUE THREAD

**Issue by kristofferoch** [Azure/azure-docs-powershell-azuread#155]
![image](https://user-images.githubusercontent.com/28562663/31540645-8231f84e-b00c-11e7-8d2e-419db61d0173.png)

**Comment by david-mayo** [comment]
This is particularly annoying, since it somehow can't even be redirected and produces a gargantuan error message:
```
PS>get-azureaduser -ObjectId 'fake.user@domain.com' -ErrorAction SilentlyContinue *>$Null
get-azureaduser : Error occurred while executing GetUser 
Code: Request_ResourceNotFound
Message: Resource 'fake.user@domain.com' does not exist or one of its queried reference-property objects are not present.
RequestId: 753c247c-440e-4975-bc31-6549c9fc27bd
DateTimeStamp: Sun, 20 Sep 2020 22:58:49 GMT
HttpStatusCode: NotFound
HttpStatusDescription: Not Found
HttpResponseStatus: Completed
At line:1 char:1
+ get-azureaduser -ObjectId 'fake.user@domain.com' -ErrorAction Silentl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADUser], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.GetUser
 ```

**Comment by billmath** [comment]
Hi @kristofferoch 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill

**Comment by PeteMitch99** [comment]
+1 for this

**Comment by PeteMitch99** [comment]
This is very strange and seems to also have effected the get-aduser command historically as well as Get-AzureADUser.

There is a lot of comments on the web about this being because get-aduser generates a terminating error and therefore erroraction has no effect. But during my testing with Get-AzureADUser i can get this run through as a non terminating error (code show below) when it shouldn't! This issue is the command doesn't seem to respond to the erroraction variable at all!

$ErrorActionPreference = "Continue"
$MailboxUserObj = (Get-AzureADUser -ObjectId $MailboxUserUPN -ErrorAction stop)
#a line after to check it continues
echo "i have finished"

or the other way

$ErrorActionPreference = "stop"
$MailboxUserObj = (Get-AzureADUser -ObjectId $MailboxUserUPN -ErrorAction continue)
#a line after to check it continues
echo "i have finished"

**Comment by jackchenwork** [comment]
I had a argument with one of my colleagues a while ago, he is powershell lover and I hate it to guts. Things like this made it so difficult to get powershell code to work properly and the issue has been here for years and seems nobody care.

I met this problem today, and my workaround is do not use ObjectId, instead :

`$user=Get-AzureADUser` |Where-Object { $_.UserPrincipalName -eq "$UPN" }
 if ( $null -eq $user) {
        Write-Host "user $UPN not found, skip"
        continue
 }
`

**Comment by McHusky** [comment]
> I had a argument with one of my colleagues a while ago, he is powershell lover and I hate it to guts. Things like this made it so difficult to get powershell code to work properly and the issue has been here for years and seems nobody care.
> 
> I met this problem today, and my workaround is do not use ObjectId, instead :
> 
> `$user=Get-AzureADUser` |Where-Object { $_.UserPrincipalName -eq "$UPN" } if ( $null -eq $user) { Write-Host "user $UPN not found, skip" continue } `

I just ran into the same problem and found your comment here. This quick fix using where-object takes too much time when many user objects exist. We did it the way Microsoft explains it:
https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureaduser?view=azureadps-2.0#example-4--get-a-user-by-userprincipalname

This also works for variables:
$user = Get-AzureADUser -Filter "userPrincipalName eq `'$UPN`'"

**Comment by Steltek** [comment]
> Thanks @McHusky , yeah I know Where-Object is slow and I rewrote it with Where:
> 
> `$users=(Get-AzureADUser).Where( { $_.UserPrincipalName -eq "$UPN" } ) if ( 0 -eq $users.count) { Write-Host "user $UPN not found, skip" continue } $user = $users[0]` But filter should be faster than where.

Instead of using where or filter, you can just wrap the whole thing in a Try and Catch the error:

```
Try {
  $user = Get-AzureAdUser -ObjectId $UPN
} Catch {
  echo "Could not get $UPN!"
  $user = $null
}
```
