### ISSUE TITLE
Issues with 'Connect-AzureAd -TenantId <string> -AADAccessToken <string> -AccountId <string>'

### ISSUE THREAD

**Issue by asbjorn-wiik** [Azure/azure-docs-powershell-azuread#156]
Hi

I'm trying create a script where i need both AzureAD and AzureRM powershell modules 

Since we require MFA to login, i wanted to try using the AccessToken from the AzureRM.ProfileClient

And using Connect-AzureAd -AADAccessToken <string> -AccountId <string> for login to have access to AzureAD commands

Commands used

```
$tenant = "tenantname.onmicrosoft.com"

Login-AzureRmAccount -TenantId $tenant

$azureRmProfile = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile

$profileClient = New-Object Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient($azureRmProfile)

Connect-AzureAd -TenantId $tenant -AADAccessToken $profileClient.AcquireAccessToken($tenant) -AccountId $($(Get-AzureRmContext).Account.Id) 

```

I get loged in fine but when running Get-AzureADUser

Get-AzureADUser : Error occurred while executing GetUsers 

Code: Authentication_MissingOrMalformed

Message: Access Token missing or malformed.

RequestId: 054e09ad-e1e3-493d-af4f-43df3e0b4841

DateTimeStamp: Mon, 16 Oct 2017 14:05:32 GMT

HttpStatusCode: Unauthorized

HttpStatusDescription: Unauthorized

HttpResponseStatus: Completed

At line:1 char:1

+ Get-AzureADUser

+ ~~~~~~~~~~~~~~~

  + CategoryInfo          : NotSpecified: (:) [Get-AzureADUser], ApiException

    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.GetUser

I can see that there is a difference in AccountType parameter that when logged in with 
`Connect-AzureAd -TenantId <string> -AADAccessToken <string> -AccountId <string>` 
AccountType parameter is set to **AccessToken**,
vs 
`Connect-AzureAd -TenantId <string>` 
AccountType parameter is set to **User**.

**Comment by LockTar** [comment]
I have exactly the same question. What is `AccountId`?

**Comment by gutyex** [comment]
What is AccountID?  
  
I have a token valid for https://graph.microsoft.com, but whatever I give as the AccountID when running Connect-AzureAD I get the same error when attempting to use the connection:

Get-AzureADUser : Error occurred while executing GetUsers 
Code: Authentication_ExpiredToken
Message: Your access token has expired. Please renew it before submitting the request.
HttpStatusCode: Unauthorized
HttpStatusDescription: Unauthorized
HttpResponseStatus: Completed

Checking the token that was used on JWT.ms shows that it is still valid.

All I find online is posts telling me to use Get-AzureRMContext to retrieve the account ID, nothing explaining what the accountID actually is

**Comment by billmath** [comment]
Hi @asbjorn-wiik 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill

**Comment by PorreKaj** [comment]
So, did this ever get resolved @gutyex ?

**Comment by gutyex** [comment]
@PorreKaj 

Using Parse-JWToken from https://www.michev.info/Blog/Post/2140/decode-jwt-access-and-id-tokens-via-powershell

$upn = (Parse-JWTtoken ($AADtoken)).Unique_name
Connect-AzureAD -AadAccessToken $AADtoken -AccountId $upn -MsAccessToken $Graphtoken
