### ISSUE TITLE
Add-AzureADGroupMember error "Error occurred while executing AddGroupMember"

### ISSUE THREAD

**Issue by terriharmon** [Azure/azure-docs-powershell-azuread#167]
We re experiencing a consistent error adding members to a security group

$refObjectId=Get-AzureRmADUser -UserPrincipalName $UserEmail
	Add-AzureADGroupMember -ObjectId [securitygroupID] -RefObjectId $refObjectId.Id

script above succeeds about half of the time and fails about half throwing :
Exception: Error occurred while executing AddGroupMember 
StatusCode: BadRequest
ErrorCode: Request_BadRequest
Message: One or more added object references already exist for the following modified properties: 'members'.

This group typically has hundreds of users that primarily have a common user name (i.e. Temporary User) but unique UPNs (i.e. user12345@) I am assuming when Add-AzureADGroupMember runs, it is first verifying whether member already exists in the group and is checking username (will have duplicates) rather than objectid (no duplicates)

Any suggestions to force command to use ObjectID for verification?

**Comment by YuriySamorodov** [comment]
@terriharmon 
Your script is already referencing user by id: `-RefObjectId $refObjectId.Id` 
You may try to use the following construct to force ObjectId resolution:
`-RefObjectId "$($refObjectId.id)"`

**Comment by billmath** [comment]
Hi @terriharmon 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

Bill

**Comment by Justice-Alliance** [comment]
i wanted to add massive owners for a Azure AD application but this is my error output :
+             Add-AzureADApplicationOwner -ObjectId $app.ObjectId -RefO ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzureADApplicationOwner], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.AddApplicationOwner
 
Add-AzureADApplicationOwner : Error occurred while executing AddApplicationOwner 
Code: Request_BadRequest
Message: One or more added object references already exist for the following modified properties: 'owners'.
RequestId: 3f541a87-1945-4be2-813d-05aa7bf0becc
DateTimeStamp: Wed, 19 Oct 2022 22:29:39 GMT
HttpStatusCode: BadRequest
