### ISSUE TITLE
Connect-AzureAD with the -Credential Parameter Clears the Password Property

### ISSUE THREAD

**Issue by mattmcnabb** [Azure/azure-docs-powershell-azuread#169]
I previously posted this issue to the UserVoice page for Azure:
https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/20363287-running-connect-azuread-with-the-credential-param

When I run `Connect-AzureAD -Credential $Cred`  for the first time in a new PowerShell session, the connection is successful, but the password property of the `$Cred` object has been cleared. I've reproed this on Windows 10 and Windows 7 and against more than one Office 365 tenant. Here's a quick test you can run:

```powershell
Describe "AzureAD credential issue" {
    BeforeEach {
        $Cred = Import-Clixml C:\users\username\Cred.xml
    }

    it "has a password" {
        $Cred.password.length | Should BeGreaterThan 0
    }

    it "clears the password" {
        $Null = Connect-AzureAD -Credential $Cred
        $Cred.password.length | Should Be 0
    }

    AfterAll {
        Disconnect-AzureAD
    }
}
```

The first test shows that if we create the credential object that the password length is greater than 0, and the second test shows that the password property has a length of 0 after the `Connect-AzureAD` command has been executed. Both of these tests will pass in a new PowerShell session, but will fail if you run again in the same session.

Please investigate this issue as this has caused me some headaches when connecting to Office 365 resources.

```
PS Repos:\> get-module azuread

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     2.0.0.131  AzureAD                             {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-AzureADDirectoryRoleMember...}


PS Repos:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by YuriySamorodov** [comment]
@mattmcnabb 
According to https://docs.microsoft.com/en-us/powershell/module/azuread/connect-azuread?view=azureadps-2.0  Credential parameter accepts PSCredential object.

It is not really clear from your example if $Creds variable is assigned to PSCredential object?

**Comment by mattmcnabb** [comment]
It is a PsCredential object. In this example I exported it to CliXml in order to more easily test my hypothesis. I get the same results if I manually test and create the credential object using Get-Credential.

**Comment by YuriySamorodov** [comment]
@mattmcnabb 
Hmm... I could not replicate this behavior.

![image](https://user-images.githubusercontent.com/5260172/34617930-13be66ca-f24e-11e7-83d9-f68af9569c45.png)

**Comment by mattmcnabb** [comment]
yes, but you're not testing the same thing. Please check the length of the password property of `$Credential`. Also, make sure you're in a new PowerShell session to replicate this.

**Comment by YuriySamorodov** [comment]
I am testing this in the new Powershell session. Password property is of zero length , but I can still connect to msolservice using the same variable no problem.

**Comment by mattmcnabb** [comment]
I don't see that behavior. If I run `Connect-MsolService -Credential $Credential` just after using `Connect-AzureAD -Credential $Credential`, then I get this error:

![image](https://user-images.githubusercontent.com/6998507/34620728-7aab58d2-f214-11e7-8f84-880d6fcadcae.png)

Regardless of outcome, why would `Connect-AzureAD` modify the properties of the PSCredential object? I haven't experienced this behavior with any other command that takes a credential input.

**Comment by corydwood** [comment]
I'm experiencing this issue as well. In my case, I'm trying to use the **Add-AzureRmAccount** cmdlet after using the **Connect-AzureAD** cmdlet with the same pscredential object.

The **Connect-AzureAD** cmdlet works fine but when I try to use the **Add-AzureRmAccount** cmdlet next, I get the error, **One or more errors occurred.: AADSTS90014: The request body must contain the following parameter: 'password'.**

I checked the pscredential object and the password length is set to 0 after running **Connect-AzureAD**.

**Comment by mkoch7811** [comment]
I'm experiencing this behavior as well. Some months ago, I created a function in my powershell profile that prompts for credentials, then uses those credentials to connect to Azure AD (MSOnline), Sharepoint Online, Exchange Online, Skype Online, and Security & Compliance. That function has been working flawlessly. Recently, I installed the Azure v2 module and added **Connect-AzureAD** into the function, replacing the Connect-MSOLService command.

When I call the function and enter my credentials, the **Connect-AzureAD** command succeeds, but then the next call (Sharepoint) responds with "password cannot be empty". The credentials dialog appears, and if I re-enter my password, the connection succeeds, but then the next connection attempt (Exchange) fails.

I've shuffled the commands around, moving **Connect-AzureAD** to the middle, then to the end. When it's in the middle, the first two connections (Sharepoint and Exchange) succeed, as does the connection to AzureAD, but then the connections to Skype and Security & Compliance fail.

For my purposes, moving **Connect-AzureAD** to the end solves the problem, allowing all connections to succeed before the connection to AzureAD. Of course, I can't use the saved credentials again, once the password has been cleared by **Connect-AzureAD**.

**Comment by egbertvanderhout** [comment]
Same issue here. Workaround (without having to change the order of commands in your scripts like @mkoch7811 suggests):
```
$Password = Read-Host -AsSecureString
$Username = "prefix@domain.tld"
$Credential = New-Object System.Management.Automation.PSCredential($Username, $Password.Copy())

Connect-AzureAD -Credential $Credential
# $Credential should still have a password
```
By copying the password the cmdlet eats the copy, not the original.

Still: weird issue.

**Comment by markekraus** [comment]
@RobdeJong I don't buy that at all. The password on the PSCredentail is a SecureString It does not exist as Plain-text in memory. I can understand clearing out the temporary conversion strings, but clearing the password from PSCredential is indefensible and, IMO, bad and misguided practice. In my experience, nothing in any module anywhere clears the password on a PSCredentail when it is consumed. Resuse of the same PSCredential object for multiple APIs is a common and acceptable practice. This is either bug or bad design.

**Comment by mattmcnabb** [comment]
I agree with @markekraus - this is a poor design decision. A module that modifies an artifact from the global scope is not one that I'm willing to use. Please change this behavior.

**Comment by cw-esp** [comment]
I am experiencing this as well. I finally tracked it down, so good to know it's not my issue. If this functionality is to stay, then the docs for Connect-AzureAD should state this is the case.

**Comment by joaopcoliveira** [comment]
Apparently this is indeed the case, due to the implementation of the [UserPasswordCredential](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/net45/UserPasswordCredential.cs) method ApplyTo() in the ADAL.NET for .NET 4.5+, which clears the password received as parameter.
+1 for changing this behavior.

**Comment by mattmcnabb** [comment]
@joaopcoliveira thanks for tracing down the source of the issue!

**Comment by ehrnst** [comment]
This is an odd issue, bu i'm only experiencing it in Azure Automation. Running connect-azureAD and Add-AzureRMAccount locally works fine.

**Comment by wesley-trust** [comment]
This had been driving me nuts, I reuse credentials in a script that needs to connect to Azure AD, Partner Center and AzureRM and couldn't figure out why the same credential object failed to authenticate.

**Comment by jeremyhagan** [comment]
Thanks goodness for this thread. It has been bugging me for ages. +1 for removing this behaviour.

**Comment by RobdeJong** [comment]
@Jean-Marc Prieur<mailto:Jean-Marc.Prieur@microsoft.com> – this is the issue we were discussing when we met this week. Do you have a work item for it?

-Rob

**Comment by ralpje** [comment]
Quick note to let you guys know I've run in to this problem as well, when creating a module to first get tenant details from AzureAD en then using the same credentials to connect to the GraphAPI. Using AzureAD module 2.0.1.10, FWIW. The makereadonly() is a valid workaround for me, but I do see this as a workaround and think this shouldn't be default behaviour.

**Comment by ThePoShWolf** [comment]
Glad I found this thread. This has been driving me crazy as well. Thank you for the workaround. I would like to see this changed as well.

**Comment by kilasuit** [comment]
Seriously??? this goes `against the grain` of what people with **ANY** powershell experience would expect and should **not** be the default, especially as the suggestion that this is for security is totally out of whack for the exact reasons @markekraus (a PowerShell MVP like me) pointed out about above.

It seems there's a similar issue that links to this "feature" to this issue at https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/999 for

the offending code I think is the below from a *very* quick scan

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/f34d98f75d14fd0123eb44cc506a9fe4d782967f/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/net45/UserPasswordCredential.cs#L91


@markcowl is this something that is covered by azure powershell or not?  If so can this be changed.

I am also dropping this via email to MVP d/l's to get better visibility

**Comment by RobdeJong** [comment]
We’re treating this as a bug and are working to solve it.

**Comment by jmprieur** [comment]
We fixed this issue in ADAL.NET last Friday (https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1087). 
Please update the PowerShell modules to [ADAL.NET](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/) 3.19.7 or later, which would fix the silly behavior

**Comment by darrmitchell** [comment]
Is there any ETA for when this will be fixed now that it's being treated as a bug? The read-only workaround does work, FWIW.

**Comment by RobdeJong** [comment]
Hi – I hope to release a fix for this today.

**Comment by itfranck** [comment]
I found the weirdest workaround: 
This works.
Password length is not reset to 0
```
$creds = get-credential -UserName 'username' -Message 'ss'
$creds2 = $creds
Connect-AzureAD -Credential $creds 

```


This doesn't (password reset to 0 and fails next time you want to use credentials)
```
$creds = get-credential -UserName 'username' -Message 'ss'
Connect-AzureAD -Credential $creds 
```

**Comment by RobdeJong** [comment]
Hi folks - this issue has now been fixed in the latest releases of the AzureAD and AzureADPreview module. Thanks for your help and patience!

**Comment by mattmcnabb** [comment]
Thanks Rob! I never gave up hope!

**Comment by mattmcnabb** [comment]
Brief testing is positive so far.

**Comment by thisispuneet** [comment]
Having this issue when I use Connect-PartnerCenter

`
> Connect-PartnerCenter -ApplicationId "xyz" -Credential $Credentials
Connect-PartnerCenter : AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'.
`

**Comment by superfliege** [comment]
We have this issue as well in Connect-AzAccount

Short example:
Connect-AzAccount -cred $cred
Connect-AzAdAccount -cred $cred 
Throw error Missing Password Property

I do not want this. This is bad code design. Please fix this...

But I will try the workarround from @RobdeJong : $Credential.password.MakeReadOnly()
Thanks for that.

**Comment by marcbertasius** [comment]
> Hi folks - this issue has now been fixed in the latest releases of the AzureAD and AzureADPreview module. Thanks for your help and patience!

Yeah, this isn't fixed. Still having an issue with Connect-AzureAD.

**Comment by mattmcnabb** [comment]
@marcbertasius That makes sense - I’d be willing to bet the Skype module hasn’t been updated in a minute.

**Comment by SjoerdV** [comment]
@mattmcnabb Indeed, running 'New-CsOnlineSession' will still clear the credential variable with version 7.0.0.0 of the SkypeOnlineConnector module. Could someone escalate this to the right product team?

**Comment by o-l-a-v** [comment]
I'm having this problem as well. I'm lead to believe that there is a problem with PowerShell itself, or the PSCredential object type. In my case I connected with Az module first, then when connecting with AzureAD module, the password property was cleared. Seems like long passwords (60ch for instance) might be related here.

Now I also use .MakeReadOnly() for the password, and it works. But who/ where should we report this bug?

**Comment by efd7887** [comment]
LOL @mattmcnabb

**Comment by billmath** [comment]
This has been fixed.
