### ISSUE TITLE
Edit button doesn't work in Azure AD modules

### ISSUE THREAD

**Issue by failattu** [Azure/azure-docs-powershell-azuread#174]
Hello,

The edit button in here gives 404 https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadapplication?view=azureadps-2.0#examples

So you can't find the source files through that.

Steps to reproduce: go to doc, press edit, get 404

URL is wrong starting from: /blob/master/Azure%20AD%20Cmdlets/AzureAD/v2/New-AzureADApplication.md

Edit url: https://github.com/Azure/azure-docs-powershell-azuread/blob/master/Azure%20AD%20Cmdlets/AzureAD/v2/New-AzureADApplication.md

**Comment by failattu** [comment]
Correct url: https://github.com/Azure/azure-docs-powershell-azuread/blob/master/azureadps-2.0/AzureAD/New-AzureADApplication.md

**Comment by billmath** [comment]
This has been fixed.
