### ISSUE TITLE
Get-AzureADUserLicenseDetail only displays SKUs (and options) if enabled at some point

### ISSUE THREAD

**Issue by kevinblumenfeld** [Azure/azure-docs-powershell-azuread#176]
Scenario:
Tenant has SKUs: (E1, E3, Visio, PowerBI, Project Pro etc)

**User joe@contoso.com**:  E1 SKU has been enabled
**PS**: `(Get-AzureADUserLicenseDetail -ObjectId "192c8ca6-2296-23f4-d057-5abc6d63624").ServicePlans`
**Results**: displays **Provisioning Status** of only E1 options (missing all other SKUs/Options)

**User joe@contoso.com**:  E1 SKU has been enabled, one option in E3 has been enable then disabled
**PS**: `(Get-AzureADUserLicenseDetail -ObjectId "192c8ca6-2296-23f4-d057-5abc6d63624").ServicePlans`
**Results**: displays **Provisioning Status** of only E1 & E3 options (missing all other SKUs/Options)

**Issue**:  Would expect all SKUs and Options to be displayed regardless of if any SKU/Option had been enabled at some point.

Thank you.

**Comment by RobdeJong** [comment]
@piotrci may able to anwer your question

**Comment by kevinblumenfeld** [comment]
Excellent! Looking forward to hearing back.  Thank you @RobdeJong & @piotrci

**Comment by kevinblumenfeld** [comment]
@RobdeJong I just realized that I opened this in the **docs** "issues" didn't I?  Should this not be in the Azure PowerShell repo (issues) instead?

**Comment by jeffreymcclain** [comment]
Just a heads up, the way I solved this was to enable every single license for a test user, copy paste the list of ServicePlanIds that user had, and then loop through that list of IDs for all other users. Basically I would set a temp variable to "Disabled" for each iteration of the loop, and it would only change to "Enabled" of that servicePlanId existed for the user (wasn't null) AND if the status value was "Successful" indicating the user had the license.

**Comment by billmath** [comment]
This is resolved.
