### ISSUE TITLE
Missing Get-AzureADDirectorySetting cmdlet in AzureAD 2.0.0.155

### ISSUE THREAD

**Issue by tseward** [Azure/azure-docs-powershell-azuread#189]
I've installed Azure AD 2.0.0.155 from the PoSh Gallery (https://www.powershellgallery.com/packages/AzureAD/2.0.0.155). The cmdlet Get-AzureADDirectorySetting indicates it cannot be found. What am I missing?

```PowerShell
PS C:\WINDOWS\system32> Get-AzureADDirectorySetting
Get-AzureADDirectorySetting : The term 'Get-AzureADDirectorySetting' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ Get-AzureADDirectorySetting
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureADDirectorySetting:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32> man get-azureaddirectory*

Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
Get-AzureADDirectoryRole          Cmdlet    AzureAD                   Gets a directory role.
Get-AzureADDirectoryRoleMember    Cmdlet    AzureAD                   Gets members of a directory role.
Get-AzureADDirectoryRoleTemplate  Cmdlet    AzureAD                   Gets directory role templates.

PS C:\WINDOWS\system32> Get-Module AzureAD

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     2.0.0.155  AzureAD                             {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredO...
```

**Comment by soerennielsen** [comment]
Same here.

**Comment by kong-zz** [comment]
Same here

**Comment by KjetilEVRY** [comment]
Same here, running Win10 1803.

**Comment by demongp** [comment]
Same here, my version is 2.0.1.10 for the Azure AD module.

**Comment by sadomovalex** [comment]
Same issue with AzureAD 2.0.1.10

**Comment by demongp** [comment]
Wow! Thanks sadomovalex!  Worked perfectly for me!

**Comment by avimalSandvik** [comment]
Hi, Im using the attached script to validate O365 Group. Im using Windows 10
Following error is encountered

PS D:\Amit A Vimal\PnP\Groupify> D:\Amit A Vimal\PnP\Groupify\ValidateInput.ps1
WARNING: The version '2.0.1.10' of module 'AzureAD' is currently in use. Retry the operation after closing the applications.
PackageManagement\Install-Package : The following commands are already available on this system:'Add-AzureADApplicationOwner,Add-AzureADDeviceRegisteredOwner,Add-AzureADDeviceRegisteredUser,Add-AzureADDirectoryRoleMember,Add-AzureADGroupMe
mber,Add-AzureADGroupOwner,Add-AzureADMSLifecyclePolicyGroup,Add-AzureADServicePrincipalOwner,Confirm-AzureADDomain,Connect-AzureAD,Disconnect-AzureAD,Enable-AzureADDirectoryRole,Get-AzureADApplication,Get-AzureADApplicationExtensionProper
ty,Get-AzureADApplicationKeyCredential,Get-AzureADApplicationLogo,Get-AzureADApplicationOwner,Get-AzureADApplicationPasswordCredential,Get-AzureADApplicationProxyApplication,Get-AzureADApplicationProxyApplicationConnectorGroup,Get-AzureADA
pplicationProxyConnector,Get-AzureADApplicationProxyConnectorGroup,Get-AzureADApplicationProxyConnectorGroupMembers,Get-AzureADApplicationProxyConnectorMemberOf,Get-AzureADApplicationServiceEndpoint,Get-AzureADContact,Get-AzureADContactDir
ectReport,Get-AzureADContactManager,Get-AzureADContactMembership,Get-AzureADContactThumbnailPhoto,Get-AzureADContract,Get-AzureADCurrentSessionInfo,Get-AzureADDeletedApplication,Get-AzureADDevice,Get-AzureADDeviceConfiguration,Get-AzureADD
eviceRegisteredOwner,Get-AzureADDeviceRegisteredUser,Get-AzureADDirectoryRole,Get-AzureADDirectoryRoleMember,Get-AzureADDirectoryRoleTemplate,Get-AzureADDomain,Get-AzureADDomainNameReference,Get-AzureADDomainServiceConfigurationRecord,Get-
AzureADDomainVerificationDnsRecord,Get-AzureADExtensionProperty,Get-AzureADGroup,Get-AzureADGroupAppRoleAssignment,Get-AzureADGroupMember,Get-AzureADGroupOwner,Get-AzureADMSDeletedDirectoryObject,Get-AzureADMSDeletedGroup,Get-AzureADMSGrou
p,Get-AzureADMSGroupLifecyclePolicy,Get-AzureADMSLifecyclePolicyGroup,Get-AzureADOAuth2PermissionGrant,Get-AzureADObjectByObjectId,Get-AzureADServiceAppRoleAssignedTo,Get-AzureADServiceAppRoleAssignment,Get-AzureADServicePrincipal,Get-Azur
eADServicePrincipalCreatedObject,Get-AzureADServicePrincipalKeyCredential,Get-AzureADServicePrincipalMembership,Get-AzureADServicePrincipalOAuth2PermissionGrant,Get-AzureADServicePrincipalOwnedObject,Get-AzureADServicePrincipalOwner,Get-Az
ureADServicePrincipalPasswordCredential,Get-AzureADSubscribedSku,Get-AzureADTenantDetail,Get-AzureADTrustedCertificateAuthority,Get-AzureADUser,Get-AzureADUserAppRoleAssignment,Get-AzureADUserCreatedObject,Get-AzureADUserDirectReport,Get-A
zureADUserExtension,Get-AzureADUserLicenseDetail,Get-AzureADUserManager,Get-AzureADUserMembership,Get-AzureADUserOAuth2PermissionGrant,Get-AzureADUserOwnedDevice,Get-AzureADUserOwnedObject,Get-AzureADUserRegisteredDevice,Get-AzureADUserThu
mbnailPhoto,New-AzureADApplication,New-AzureADApplicationExtensionProperty,New-AzureADApplicationKeyCredential,New-AzureADApplicationPasswordCredential,New-AzureADApplicationProxyApplication,New-AzureADApplicationProxyConnectorGroup,New-Az
ureADDevice,New-AzureADDomain,New-AzureADGroup,New-AzureADGroupAppRoleAssignment,New-AzureADMSGroup,New-AzureADMSGroupLifecyclePolicy,New-AzureADMSInvitation,New-AzureADServiceAppRoleAssignment,New-AzureADServicePrincipal,New-AzureADServic
ePrincipalKeyCredential,New-AzureADServicePrincipalPasswordCredential,New-AzureADTrustedCertificateAuthority,New-AzureADUser,New-AzureADUserAppRoleAssignment,Remove-AzureADApplication,Remove-AzureADApplicationExtensionProperty,Remove-Azure
ADApplicationKeyCredential,Remove-AzureADApplicationOwner,Remove-AzureADApplicationPasswordCredential,Remove-AzureADApplicationProxyApplication,Remove-AzureADApplicationProxyApplicationConnectorGroup,Remove-AzureADApplicationProxyConnector
Group,Remove-AzureADContact,Remove-AzureADContactManager,Remove-AzureADDevice,Remove-AzureADDeviceRegisteredOwner,Remove-AzureADDeviceRegisteredUser,Remove-AzureADDirectoryRoleMember,Remove-AzureADDomain,Remove-AzureADGroup,Remove-AzureADG
roupAppRoleAssignment,Remove-AzureADGroupMember,Remove-AzureADGroupOwner,Remove-AzureADMSDeletedDirectoryObject,Remove-AzureADMSGroup,Remove-AzureADMSGroupLifecyclePolicy,Remove-AzureADMSLifecyclePolicyGroup,Remove-AzureADOAuth2PermissionG
rant,Remove-AzureADServiceAppRoleAssignment,Remove-AzureADServicePrincipal,Remove-AzureADServicePrincipalKeyCredential,Remove-AzureADServicePrincipalOwner,Remove-AzureADServicePrincipalPasswordCredential,Remove-AzureADTrustedCertificateAut
hority,Remove-AzureADUser,Remove-AzureADUserAppRoleAssignment,Remove-AzureADUserExtension,Remove-AzureADUserManager,Reset-AzureADMSLifeCycleGroup,Restore-AzureADDeletedApplication,Restore-AzureADMSDeletedDirectoryObject,Revoke-AzureADSigne
dInUserAllRefreshToken,Revoke-AzureADUserAllRefreshToken,Select-AzureADGroupIdsContactIsMemberOf,Select-AzureADGroupIdsGroupIsMemberOf,Select-AzureADGroupIdsServicePrincipalIsMemberOf,Select-AzureADGroupIdsUserIsMemberOf,Set-AzureADApplica
tion,Set-AzureADApplicationLogo,Set-AzureADApplicationProxyApplication,Set-AzureADApplicationProxyApplicationConnectorGroup,Set-AzureADApplicationProxyApplicationCustomDomainCertificate,Set-AzureADApplicationProxyApplicationSingleSignOn,Se
t-AzureADApplicationProxyConnector,Set-AzureADApplicationProxyConnectorGroup,Set-AzureADDevice,Set-AzureADDomain,Set-AzureADGroup,Set-AzureADMSGroup,Set-AzureADMSGroupLifecyclePolicy,Set-AzureADServicePrincipal,Set-AzureADTenantDetail,Set-
AzureADTrustedCertificateAuthority,Set-AzureADUser,Set-AzureADUserExtension,Set-AzureADUserLicense,Set-AzureADUserManager,Set-AzureADUserPassword,Set-AzureADUserThumbnailPhoto,Update-AzureADSignedInUserPassword'. This module 
'AzureADPreview' may override the existing commands. If you still want to install this module 'AzureADPreview', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
 


[ValidateInput - Copy.txt](https://github.com/Azure/azure-docs-powershell-azuread/files/2114198/ValidateInput.-.Copy.txt)

**Comment by michaelmaillot** [comment]
> Same issue with AzureAD 2.0.1.10. I've installed both AzureAD and AzureADPreview. Command:
> `man Get-AzureADDirectory*`
> showed that Get-AzureDirectorySetting cmdlet is defnied in AzureADPreview module, not in Azure AD:
> 
> ```
> Name                              Category  Module                    Synopsis
> ----                              --------  ------                    --------
> Get-AzureADDirectoryRole          Cmdlet    AzureADPreview            Gets a directory role.
> Get-AzureADDirectoryRoleMember    Cmdlet    AzureADPreview            Gets members of a directory role.
> Get-AzureADDirectoryRoleTemplate  Cmdlet    AzureADPreview            Gets directory role templates.
> Get-AzureADDirectorySetting       Cmdlet    AzureADPreview            Gets a directory setting.
> Get-AzureADDirectorySettingTem... Cmdlet    AzureADPreview            Gets a directory setting template.
> Get-AzureADDirectoryRoleMember    Cmdlet    AzureAD                   Get-AzureADDirectoryRoleMember...
> Get-AzureADDirectoryRole          Cmdlet    AzureAD                   Get-AzureADDirectoryRole...
> Get-AzureADDirectoryRoleTemplate  Cmdlet    AzureAD                   Get-AzureADDirectoryRoleTemplate...
> ```
> 
> So solution was to restart Powershell and login to Azure AD using Connect-AzureAD from AzureADPreview module:
> `AzureADPreview\Connect-AzureAD`
> After that Get-AzureADDirectorySetting cmdlet became available.

Hi,

I've managed to make this command work, by only installing the AzureADPreview Module, which works, without the "AzureADPreview\" command prefix.

In my case, I've met this error when applying Directory Settings (disable Group / Team creation) : https://docs.microsoft.com/fr-fr/azure/active-directory/users-groups-roles/groups-settings-cmdlets

Hope it helps.

**Comment by loadedleke** [comment]
> Same issue with AzureAD 2.0.1.10. I've installed both AzureAD and AzureADPreview. Command:
> `man Get-AzureADDirectory*`
> showed that Get-AzureDirectorySetting cmdlet is defnied in AzureADPreview module, not in Azure AD:
> 
> ```
> Name                              Category  Module                    Synopsis
> ----                              --------  ------                    --------
> Get-AzureADDirectoryRole          Cmdlet    AzureADPreview            Gets a directory role.
> Get-AzureADDirectoryRoleMember    Cmdlet    AzureADPreview            Gets members of a directory role.
> Get-AzureADDirectoryRoleTemplate  Cmdlet    AzureADPreview            Gets directory role templates.
> Get-AzureADDirectorySetting       Cmdlet    AzureADPreview            Gets a directory setting.
> Get-AzureADDirectorySettingTem... Cmdlet    AzureADPreview            Gets a directory setting template.
> Get-AzureADDirectoryRoleMember    Cmdlet    AzureAD                   Get-AzureADDirectoryRoleMember...
> Get-AzureADDirectoryRole          Cmdlet    AzureAD                   Get-AzureADDirectoryRole...
> Get-AzureADDirectoryRoleTemplate  Cmdlet    AzureAD                   Get-AzureADDirectoryRoleTemplate...
> ```
> 
> So solution was to restart Powershell and login to Azure AD using Connect-AzureAD from AzureADPreview module:
> `AzureADPreview\Connect-AzureAD`
> After that Get-AzureADDirectorySetting cmdlet became available.

Worked like a charm... I needed to disable Office 365 group creation and needed the Get-AzureADDirectorySetting cmdlet...
Thank you

**Comment by rpcpancil** [comment]
Here is my resolution to this issue.
Check your AzureAD module version. Mine was version 2.0.2.31
![image](https://user-images.githubusercontent.com/22983163/76733742-611bea80-679c-11ea-829b-35ccf7c39cca.png)

Uninstall the existing module and install the latest AzureADPreview module
![image](https://user-images.githubusercontent.com/22983163/76733830-8d376b80-679c-11ea-91c6-7e0a4d960183.png)

Result: I was able to run the script
![image](https://user-images.githubusercontent.com/22983163/76733965-d1c30700-679c-11ea-8305-7648f5ba93e3.png)

**Comment by cdmenage** [comment]
This worked for me:

1. Open the Windows PowerShell app as an administrator.
2. Uninstall any previous version of AzureADPreview.
```
Uninstall-Module AzureADPreview
Uninstall-Module azuread
```
3. Install the latest version of AzureADPreview.
```
Install-Module AzureADPreview
```


(source: [Azure Active Directory cmdlets for configuring group settings](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-settings-cmdlets))

**Comment by plamber** [comment]
I was able to fix this issue by installing the AzureADPreview module like this:
```
install-module azureadpreview -AllowClobber
```

Afterwards, i restarted a powershell session and connected to AzureAD using the following command as suggested by @sadomovalex 
```
AzureADPreview\Connect-AzureAD
```

**Comment by billmath** [comment]
This cmdlt is available in the preview module.

**Comment by mabdulmoez** [comment]
It worked with me after using the following:

install-module azureadpreview -AllowClobber

AzureADPreview\Connect-AzureAD

restart the powershell

" Get-AzureADDirectorySetting" worked with me.

then I stuck with $Setting["EnableMIPLabels"] = "True"

I got this error 

(Cannot index into a null array.
At line:1 char:1
+ $Setting["EnableMIPLabels"] = "True"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray)


solved with this https://owenmurr.co.uk/p/execute-azureadlabelsync-does-not-look-to-work-correctly/
