### ISSUE TITLE
-ForceChangePasswordNextLogin with Current Password?

### ISSUE THREAD

**Issue by Scourgeza** [Azure/azure-docs-powershell-azuread#190]
Hi Guys, 

Apologies if I'm doing this in the wrong format. First time here.

I'm trying to assist a client to have their AD Logins Force Change Password every 60 Days Without changing their current password. 

I'm not sure what the correct way would be to change this policy? I was thinking to write a script to add the -ForceChangePasswordNextLogin to the user/s with the following command:

Set-AzureADUserPassword -ObjectId XXXXXXXXX -Password $currentpassword -ForceChangePasswordNextLogin True

But that doesn't work because "-Password" would need a parameter. 

What would the best way be to achieve this?

**Comment by marmstrong94** [comment]
This is something I've looked for as well. The -Password parameter is required.

In my case, I want to be able to immediately have a user's password expire. I was able to do so with the Set-MsolUserPassword command in the old module with the -ForcePasswordChangeOnly command, but the password parameter was not required.

I am unable to utilize the Msol module as my organization must use MFA.

**Comment by billmath** [comment]
Hi @Scourgeza 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
