### ISSUE TITLE
Get-AzureADApplicationProxyApplication does not work using ServicePrincipal and Certificate for Connect-AzureAD

### ISSUE THREAD

**Issue by mortenlerudjordet** [Azure/azure-docs-powershell-azuread#200]
AzureADPreview version 2.0.1.2

Get-AzureADApplicationProxyApplication works fine if one executes Connect-AzureAD using credentials logon.
Though if one does 
Connect-AzureAD -ApplicationId $AzureConnection.ApplicationId -CertificateThumbprint $AzureConnection.CertificateThumbprint -TenantId $AzureConnection.TenantId, using a service principal and certificate. Then run Get-AzureADApplicationProxyApplication the following error is thrown:
```
Get-AzureADApplicationProxyApplication : Error occurred while executing GetApplicationProxyApplication 
Code: UnsupportedTokenException
Message: Unable to extract identities from the token.
InnerError:
  RequestId: 81cd6e1e-5950-4ff0-89bf-b0b424952651
  DateTimeStamp: Tue, 03 Apr 2018 08:41:43 GMT
HttpStatusCode: InternalServerError
HttpStatusDescription: Internal Server Error
HttpResponseStatus: Completed
At line:1 char:1
+ Get-AzureADApplicationProxyApplication -ObjectId 'b8f5c334-3f29-49ef- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADApplicationProxyApplication], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.GetApplicationProxyApplication
```
This only happens for the new Proxy related functions, other functions like Get-AzureADApplication works fine using a serviceprincipal and certificate.

Please look into this

**Comment by RobdeJong** [comment]
+ @Sid<mailto:sisharm@microsoft.com>, can you investigate?

Thanks,
Harshini

From: Rob de Jong
Sent: Tuesday, April 3, 2018 11:24 AM
To: Azure/azure-docs-powershell-azuread <reply@reply.github.com>; Azure/azure-docs-powershell-azuread <azure-docs-powershell-azuread@noreply.github.com>; Harshini Jayaram <harshja@microsoft.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: RE: [Azure/azure-docs-powershell-azuread] Get-AzureADApplicationProxyApplication does not work using ServicePrincipal and Certificate for Connect-AzureAD (#200)

@Harshini<mailto:harshja@microsoft.com> – can you or your devs look at this please?

**Comment by mortenlerudjordet** [comment]
Any movement on this. Need to implement some certificate monitoring of services published through app proxy and need this to work :)

**Comment by ionutleca** [comment]
I get `Get-AzureADApplicationProxyApplication : Object reference not set to an instance of an object.`
when I use -AadAccessToken for Connect-AzureAD. It works fine if I use the -Credential method.

**Comment by ahmadabdalla** [comment]
Is this issue still being worked out? 

Still facing the problem when calling out cmdlets relating to 'ApplicationProxy'

`Get-AzureADApplicationProxyConnector : Error occurred while executing GetApplicationProxyConnectors 
Code: UnsupportedTokenException
Message: Unable to extract identities from the token.: oid
InnerError:
  RequestId: 5b6bed3a-75d9-47e7-8adc-97f37ddd9987
  DateTimeStamp: Thu, 07 Mar 2019 02:25:25 GMT
HttpStatusCode: InternalServerError
HttpStatusDescription: Internal Server Error
HttpResponseStatus: Completed
At line:1 char:1
+ Get-AzureADApplicationProxyConnector
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADApplicationProxyConnector], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.GetApplicationProxyConnector`

**Comment by isheppard-nhs** [comment]
Still getting this now too. Is this likely to be looked at?

**Comment by ionutleca** [comment]
In my case I was missing the `-MsAccessToken`.
-MsAccessToken (https://graph.windows.net)
-AadAccessToken (https://graph.microsoft.com)
After connecting usinf `Connect-AzureAD -MsAccessToken $MsToken -AadAccessToken $AadToken -AccountId $accountId -TenantId $tenantId`, Get-AzureADApplicationProxyApplication returned the expected result.

**Comment by Yevrag35** [comment]
> In my case I was missing the `-MsAccessToken`.
> -MsAccessToken (https://graph.windows.net)
> -AadAccessToken (https://graph.microsoft.com)
> After connecting using `Connect-AzureAD -MsAccessToken $MsToken -AadAccessToken $AadToken -AccountId $accountId -TenantId $tenantId`, Get-AzureADApplicationProxyApplication returned the expected result.

Yes, AppProxy cmdlets work if you're not using a ServicePrincipal (this is how I've been getting around it since the cmdlets became available).  This issue is about not being to use them when using ServicePrincipals.

```Connect-AzureAD -MsAccessToken $MsToken -AadAccessToken $AadToken -AccountId $accountId -TenantId $tenantId``` requires 'the -AccountId' parameter which, to my knowledge, can't be satisfied with a ServicePrincipal.

**Comment by ionutleca** [comment]
Correct, I needed to create a functional user with GA instead of using a service principal (only way I could automate it). Not sure a service principal can be used for the app proxy cmdlets ...

**Comment by mortenlerudjordet** [comment]
The issue is that using a ServicePrincipal (AD App) to connect did not work when I opened this issue.
Yes, one can work around the problem though a normal user will also roll over on pwd so usually not the best option when code running fully automated.

**Comment by ionutleca** [comment]
You can generate the tokens in a fully automated way using the linux az cli and then pass them to the ps1 script. But yeah, not a nice way to do it :(

**Comment by isheppard-nhs** [comment]
I was looking for a way to use powershell in isolation and without making use of a privileged user account if possible. But doesn't look possible for the time being. Thanks.

**Comment by tFable** [comment]
This is also an issue for me. 

Unfortunately, this is a blocker in the effort to fully automate certificate renewals in our AAD App Proxy-exposed Internal apps. This basically means we have to install the certificates manually.

@RobdeJong ,

Any progress with this one?

t

**Comment by comnam90** [comment]
Any updates on this??

**Comment by f-bader** [comment]
Still nothing? @RobdeJong this is still present in AzureADPreview v2.0.2.85
Do you need anything to get the fix started?

**Comment by githubarpyka** [comment]
I checked this with our developers yesterday. Resolving this issue is still in our backlog. It's tracked as important. Because of other higher priorities we cannot start with this in this quarter. Fixing the issue will be evaluated in July... Thank you for your understanding.

**Comment by flotpg** [comment]
I also ran into this.
We want to renew certificates of application proxy via automation account runBook.
What would the mentioned workarounds look like? Creating normal user, excluding it from MFA and place the password in clear text inside the script?

Best Regards, Flo.

**Comment by mateuszdrab** [comment]
Hello

Just adding myself to the list of affected users - halted my certificate automation attempt for now.

Thanks

**Comment by walterwalldmg** [comment]
Hello, I have same issue. Login with service principal and certificate I get this error when I run Get-AzureADApplicationProxyConnector:

_Microsoft.Open.MSGraphV10.Client.ApiException: Error occurred while executing GetApplicationProxyConnectors
Code: UnsupportedTokenException
Message: Unable to extract identities from the token.: oid
InnerError:
  RequestId: d554be45-5581-4368-9fe0-e43e8ee98281
  DateTimeStamp: Fri, 12 Jun 2020 09:57:18 GMT
HttpStatusCode: InternalServerError
HttpStatusDescription: Internal Server Error
HttpResponseStatus: Completed_

Get-AzureADApplication is working, but no command of Get-AzureADApplicationProxy...

Hope this will be fixed soon...
Thanks

**Comment by allanmoller** [comment]
damm just spend 4 hours trying to do this, before i found this thread........ well put one more on the list!!!

**Comment by flotpg** [comment]
Too bad this is still an issue. Is there no way to automate replacing application proxy certificates using certs from azure key vault?

**Comment by billmath** [comment]
Hi all,

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill

**Comment by MarkoKoivupera** [comment]
Hello,

Issue was closed in 2020, but this is still affecting us. Is there any updates or ETA on when we will be able to manage application proxies with powershell or graph API using managed identity or service principal? This is blocking proper application proxy certificate update automations at the moment.

**Comment by githubarpyka** [comment]
Hello Marko,

This is currently not supported as it's documented in our FAQ: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-proxy-faq#can-a-service-principal-manage-application-proxy-using-powershell-or-microsoft-graph-apis-

It's still in the backlog of our developers. Once we have an update on this, we are going to update this thread.

In the meantime could you please vote for this idea: https://feedback.azure.com/forums/34192--general-feedback/suggestions/42768932-manage-app-proxy-with-service-principal-graph-a

**Comment by mateuszdrab** [comment]
@githubarpyka 
Hi Arpad, do you have any updates on this? Could you point me to the work item?
Thanks

**Comment by rsegers** [comment]
> I've been able to run and update certificates on the App Proxy by running them as Workflows in an Automation Account in Azure. This is using a RunAs account and seems to work fine once the necessary permissions are given. I've set up some scripts to trigger this workflow from on-premises and pass the certificate PFX as base64 encoded argument - this runs as a cronjob from my K8s cluster sourcing the certificate from a cert-manager managed secret.
> 
> Happy to share the scripts if you'd like to explore.

@mateuszdrab Would you mind explaining this solution and required permissions? I haven't tried this, but I am sceptical about how this would work. The RunAs account is simply an app registration, e.g. service principal. If that works, than a reverse engineer to the correct token should be possible.

**Comment by mateuszdrab** [comment]
> > I've been able to run and update certificates on the App Proxy by running them as Workflows in an Automation Account in Azure. This is using a RunAs account and seems to work fine once the necessary permissions are given. I've set up some scripts to trigger this workflow from on-premises and pass the certificate PFX as base64 encoded argument - this runs as a cronjob from my K8s cluster sourcing the certificate from a cert-manager managed secret.
> > Happy to share the scripts if you'd like to explore.
> 
> @mateuszdrab Would you mind explaining this solution and required permissions? I haven't tried this, but I am sceptical about how this would work. The RunAs account is simply an app registration, e.g. service principal. If that works, than a reverse engineer to the correct token should be possible.

Perhaps it works because I used a SP with a secret (not a certificate)?

**Comment by erose96** [comment]
I am using a SP with a secret and get the same behavior others are reporting.
