### ISSUE TITLE
New-AzureADApplicationKeyCredential -CustomKeyIdentifier not taking string

### ISSUE THREAD

**Issue by ccassagnol** [Azure/azure-docs-powershell-azuread#202]
AzureAD Module loaded:

ModuleType Version    Name   
---------- -------    ----   
Binary     2.0.1.10   AzureAD
Binary     2.0.0.131  AzureAD
Binary     2.0.0.115  AzureAD

When running:

```PowerShell
$cer = Get-AzureKeyVaultSecret -VaultName key-vault-01 -Name certificate-test -Version 714e546e9d18401b92a183ce597c3950
$base64Value = [System.Convert]::ToBase64String($cer.Certificate.GetRawCertData())
$base64ThumbPrint = [System.Convert]::ToBase64String($cer.Certificate.GetCertHash())
New-AzureADApplicationKeyCredential -ObjectId <ObjectID of App in AAD> -Type AsymmetricX509Cert -Usage Verify -Value $base64Value -StartDate $cer.Created -EndDate $cer.Expires
 -CustomKeyIdentifier "1231242314124123213"

New-AzureADApplicationKeyCredential : Error occurred while executing SetApplication
Code: Request_BadRequest
Message: When present, application key identifier cannot be empty and can be at most 32 bytes.
Parameter name: applicationKeyIdentifierValue
RequestId: 68930e6a-c8ee-46a9-9971-0c69db4346ee
DateTimeStamp: Fri, 25 May 2018 00:13:46 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ New-AzureADApplicationKeyCredential -ObjectId {Redacted} ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureADApplicationKeyCredential], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD.Graph.PowerShell.Custom.NewAzureADApplicationKeyCredential

###
Get-AzureADApplicationKeyCredential -ObjectId <ObjectIDHere>
CustomKeyIdentifier : {63, 220, 93, 146...}
EndDate             : 4/1/2019 8:33:57 AM
KeyId               : <KeyIDHere>
StartDate           : 4/1/2018 8:23:57 AM
Type                : AsymmetricX509Cert
Usage               : Verify
Value               :

## Running the following to show you what end up in Portal vs PowerShell
$cer.Certificate.GetSerialNumberString()
74A999760D7E4263B8D635A06C3FD022 #This is expected Value

$base64ThumbPrint = [System.Convert]::ToBase64String($cer.Certificate.GetSerialNumber())
$base64ThumbPrint
ItA/bKA11rhjQn4NdpmpdA== #This is expected Value

## you can convert between the byte and base64VAlue and get the same thing all day long, now if you try to use the $base64ThumbPrint as the -CustomKeyIdentifier you get at PowerShell:

CustomKeyIdentifier : {73, 116, 65, 47...}
EndDate             : 4/1/2019 8:33:57 AM
KeyId               : 77ad6d7a-c6ca-4cc5-b75f-b3c316daac3e
StartDate           : 4/1/2018 8:33:58 AM
Type                : AsymmetricX509Cert
Usage               : Verify
Value               : {77, 73, 73, 68...}

4974412F624B41313172686A516E344E64706D7064413D3D #This is the thunbprint that shows up in the Portal.... 



```

If I convert the thumbprint to base64 as you see above, it does work, BUT. The thumbprint is converted within the Azure Portal to some other value AND doesn't match anything. If I manually upload the certificate in the Portal, it properly lists the thumbprint as the CustomKeyIdentifier, but then the byte Array at the command line isn't able to convert it to anything legible.

**Comment by Pilosite** [comment]
I have this exact issue also, didn't find a workaround yet :-/

**Comment by josephtingiris** [comment]
This continues to happen, with `az` as well ...

**Comment by billmath** [comment]
Hi @ccassagnol 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill

**Comment by avishnyakov** [comment]
@billgib, how did we go with the work item which you open with the engineering on Nov 18, 2020 regarding this reported bug?

There are at lest 4 tickets on this very problem with not much clarification on fix timeline or other options. Looks that underlying API affect az cli, azure powershell and Terraform provider while Azure Portal UI allows to create secret with quite a long description. 

Also raised this problem with Azure support. 

What else can be done to draw attention to this 2 years old bug?

* https://github.com/Azure/azure-docs-powershell-azuread/issues/296
* https://github.com/Azure/azure-docs-powershell-azuread/issues/202
* https://github.com/MicrosoftDocs/azure-docs/issues/41294
* https://github.com/Azure/azure-cli/issues/10720
