### ISSUE TITLE
Remove-AzureADApplicationPolicy failing with error message

### ISSUE THREAD

**Issue by msft-jaiverma** [Azure/azure-docs-powershell-azuread#204]
Remove-AzureADApplicationPolicy -ID 54844047-18c1-4543-9731-XXX-PolicyId 53cd3660-987e-XX-XX-XXXX is failing with the following error message

Remove-AzureADApplicationPolicy : Error occurred while executing RemoveApplicationPolicy 
Code: Request_ResourceNotFound
Message: Resource '54844047-18c1-XX-XXXX' does not exist or one of its queried reference-property objects are not present.
InnerError:
  RequestId: XX-9d57-4e76-XX-XX
  DateTimeStamp: Mon, 28 May 2018 11:23:43 GMT
HttpStatusCode: NotFound
HttpStatusDescription: Not Found
HttpResponseStatus: Completed
At line:2 char:1
+ Remove-AzureADApplicationPolicy -ID XX-18c1-4543-9731-XX
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AzureADApplicationPolicy], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.RemoveApplicationPolicy
 
However, the policy id and object id are correct

PS C:\Users\jaiverma\Documents\Azure AD Preview\AzureADPreview\2.0.0.127> Get-AzureADApplication -ObjectId XX-4XX-XX-XX

ObjectId                             AppId                                DisplayName
--------                             -----                                -----------
XX1-4419-                       8XX-XX-XX-XXXX            myTestApp  

I tried in different environment and it is not working in any.

**Comment by levixking** [comment]
It wasn't working correctly for me too, either Microsoft's documentation is jumbled or the cmdlet is in the process of being developed.

In the mean time, use "Remove-AzureADServicePrincipalPolicy" instead, it worked for me.

**Comment by billmath** [comment]
Hi @msft-jaiverma msft-jaiverma 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

Bill
