### ISSUE TITLE
Connect-AzureAd dialog hidden vs code

### ISSUE THREAD

**Issue by zippy1981** [Azure/azure-docs-powershell-azuread#207]
If I type `Connect-AzureAd` in AzureAD `console.exe` the dialog box pops up. If I do it from the terminal in `vscode.exe` the dialog is hidden, and I have to Alt+Tab to it. Can we do one of the following to fix this:

1. Have a `-ModalPrompts` switch to force this or any other win32 dialogs to be modal, always on top?
2. Have the connect prompt have its own taskbar icon, separate from powershell.exe so it is visible.
3. Just some how fix the behavior in vscode?

**Comment by tatigo** [comment]
same here, and it was fine till lately

**Comment by billmath** [comment]
Hi @zippy1981 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill
