### ISSUE TITLE
Remove-AzureADOAuth2PermissionGrant example not working

### ISSUE THREAD

**Issue by rkyttle** [Azure/azure-docs-powershell-azuread#213]
https://docs.microsoft.com/en-us/powershell/module/azuread/remove-azureadoauth2permissiongrant

I have a question on Example 1: Remove an OAuth2 permission grant

I don’t see how this will work, at least it is not working in my case.  I am trying to do some work with the Microsoft Graph, and I noticed that the AzureADOAuth2PermissionGrant cmdlets do not work properly when I provide the ObjectID of the Enterprise Application.  When I try to run through the code in your example, that is exactly what is being provided back to me when I run: Get-AzureADServicePrincipal | Where-Object {$_.DisplayName -eq "TestServicePrincipal"}

If I use this value as input into the Get-AzureADOAuth2PermissionGrant command, I get no results.

However, if I go into Azure AD, into the Enterprise Application and click on the Permissions button I can see the permissions currently assigned.  If I click on one of those permissions, I now see a field in the Permission details called Service principal ID.

If I take this ID and plug it into the commands described in your example as the ObjectID, everything works and I get results back.

**Comment by billmath** [comment]
Hi @rkyttle 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill
