### ISSUE TITLE
New-AzureADGroupAppRoleAssignment : Error occurred while executing NewGroupAppRoleAssignment 

### ISSUE THREAD

**Issue by Grant-Rc** [Azure/azure-docs-powershell-azuread#215]
New-AzureADGroupAppRoleAssignment : Error occurred while executing NewGroupAppRoleAssignment 
Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.
HttpStatusCode: Forbidden
HttpStatusDescription: Forbidden
HttpResponseStatus: Completed
At line:27 char:1
+ New-AzureADGroupAppRoleAssignment -ObjectId $AzureGroup.ObjectId -Pri ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureADGroupAppRoleAssignment], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.NewGroupAppRoleAssignment
 
Having limited knowledge on the workings on the command it seems that in Azure (AWS App) you can only set up one account under provisioning that has access to the AWS account to list the roles. Because we are setting up multiple account though the 1 app (maybe not design for that) I get this error. 

Checking the config and all settings are updating as i would expect i can even login to the app view all my AWS accounts and role and login.

**Comment by billmath** [comment]
Hi @Grant-Rc 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

#please-close
