### ISSUE TITLE
Get-AzureADDevice : not all Device properties work with the `-filter` parameter?

### ISSUE THREAD

**Issue by flyinghyrax** [Azure/azure-docs-powershell-azuread#216]
Good morning!

I have been struggling with using the `-filter` parameter with the `Get-AzureADDevice` command. After some experimentation, it appears that the OData filters work with some Device properties, but not others. For example, the following command completes successfully:
`Get-AzureADDevice -Filter "startswith(displayName, '0')" -Top 10`

While the following does not:
`Get-AzureADDevice -Filter "startswith(deviceOSType, 'windows')" -Top 10`

```
Get-AzureADDevice : Error occurred while executing GetDevices
Code: Request_UnsupportedQuery
Message: Unsupported or invalid query filter clause specified for property 'deviceOSType' of resource 'Device'.
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ Get-AzureADDevice -Filter "startswith(deviceOSType, 'windows')" -Top  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADDevice], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.GetDevice
```

If it is just a fact of implementation that some properties are valid when filtering queries while others are not (i.e. if this is not a bug), then it would be helpful for this to be reflected in the documentation. It would be nice to know what properties are valid, with a rationale for the limitations as a nice-to-have.

Thank you all for the great library and keep up the good work!

**Comment by cdtek** [comment]
Has anyone from MS looked into this ? Running the command below also returns an error.

`Get-AzureADDevice -Filter "DeviceTrustType eq 'ServerAD'"`

Get-AzureADDevice : Error occurred while executing GetDevices
Code: Request_UnsupportedQuery
Message: Unsupported or invalid query filter clause specified for property 'deviceTrustType' of resource 'Device'.
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ Get-AzureADDevice -Filter "DeviceTrustType eq 'ServerAD'"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADDevice], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.GetDevi
   ce

**Comment by edyoung** [comment]
I haven't tried this but I reckon you need to use -eq instead of eq. Don't know enough to comment on the general question.

**Comment by cdtek** [comment]
I wish they would have stuck to that format, like the on prem ad cmdlets but no. It's supposed to be 'eq' . Filtering by display names works.

`Get-AzureADDevice -Filter "DisplayName eq 'computername'"`

**Comment by bally-singh** [comment]
Hi... Can we have an update on this please?

Get-AzureADDevice -All 1 -Filter "DisplayName eq 'Computername'"

Will work.

But any other properties will fail, for example:

Get-AzureADDevice -All 1 -Filter "DeviceID eq 'xxxx'"

Get-AzureADDevice : Error occurred while executing GetDevices
Code: Request_UnsupportedQuery
Message: Unsupported or invalid query filter clause specified for property 'deviceId' of resource 'Device'.
RequestId: b7aa04da-e3f7-4272-8573-0cb8ca3bd14e
DateTimeStamp: Thu, 23 May 2019 17:36:42 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed

**Comment by bakerm00** [comment]
can confirm this is still an issue 19 months on

**Comment by pekohub** [comment]
use 
`Get-AzureADDevice -Filter "deviceId eq guid'26ceedbb-0f1a-432a-bf59-e78a2864fdbb'"`

**Comment by billmath** [comment]
Hi @flyinghyrax 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill

**Comment by eschrader** [comment]
FYI the queries are kinda weird, but this complex one works for example:
`Get-AzureADDevice -all $true -Filter ("DeviceTrustType eq 'ServerAd' and DeviceOSType eq 'Windows'") |ft -prop DisplayName,DeviceTrustType,IsManaged,DeviceOSType`
Normally I do ${(condition 1) -and (condition 2)} on my filters (like for GET-ADUser)
`Get-ADUser -Filter {(UserPrincipalName -like 'n*') -OR (UserPrincipalName -like 'o*') -OR (UserPrincipalName -like 'p*')}`
But this Device commandlet seems to prefer a text string for the filter rather than evaluating an expression.

Hope this helps someone else!
