### ISSUE TITLE
Get-AzureADGroup, Get-AzureADUser and most cmdlet implementing -Filter

### ISSUE THREAD

**Issue by lwajswaj** [Azure/azure-docs-powershell-azuread#217]
Every time there's a reference for -Filter parameter, help reads "Specifies an oData v3.0 filter statement. This parameter controls which objects are returned." however there's a certain subset of oData v3.0 filters allowed, not all of them are available. For example: startswith, endswith or substringof are not supported, getting error:

_Message: Unsupported method '{0}' in query._

Only logical operators for oData v3 seem to be supported however the documentation doesn't make any reference to which ones are actually supported or not.

**Comment by lesterw1** [comment]
The -filter parameter is incredibly week and pretty much useless for any real queries since there is no 'contains' operator such as the OData substringof() function.  For example:

Get-AzureADUser -Filter "substringof('#EXT#@', UserPrincipalName)

would return the list of external users (as denoted by the #EXT#@ in the UserPrincipalName).  Unfortunately, to do this now, you have to return all entries and then do a Where-Object to filter the results.  This blows up Azure Runbooks which don't have enough memory.

WISH LIST: Please add support for the substringof() $filter.

**Comment by moorereason** [comment]
For the record, my testing of AzureAD module 2.0.0.131 shows that the only oData 3.0 string function supported by the `Get-AzureADUser` filter service is `startswith`.  It also appears that the `ne`, `gt`, and `lt` logical operators are not supported.

**Comment by GeorgeCMElliott** [comment]
We still need a way in powershell to search for groups by displayName that is like, contains, or is a substringof() a search substring. Otherwise to lesterw1's point almost a year ago

**Comment by durayakar** [comment]
Please add the link https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/howto/azure-ad-graph-api-supported-queries-filters-and-paging-options instead of o-data filter link. Much more helpful.

**Comment by billmath** [comment]
Hi @lwajswaj 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill

**Comment by stevenwhitej** [comment]
Hi @billmath, and updates on this?  The [Get-AzureADUser](https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureaduser?view=azureadps-2.0) page is still explaining the Filter parameter with a link to this [OData v3 page](https://www.odata.org/documentation/odata-version-3-0/odata-version-3-0-core-protocol/#queryingcollections) and it contains functions that still don't work.  Thanks!

**Comment by leswaters** [comment]
@Billmath The link to the OData v3 page is a good reference, but as @stevenwhitej points out, there are a number of functions and operators that (sadly) don't work yet. Pull request #761 created for the following proposed change:

`-Filter`
Specifies an oData v3.0 filter statement. This parameter controls which objects are returned. Details on querying with oData can be found here. http://www.odata.org/documentation/odata-version-3-0/odata-version-3-0-core-protocol/#queryingcollections. **Not all of the oData v3 functions and operators are supported at this time.**
