### ISSUE TITLE
Allow token policy operations on v2 applications

### ISSUE THREAD

**Issue by spongessuck** [Azure/azure-docs-powershell-azuread#224]
When trying to change token policy on a converged application using Add-AzureADApplicationPolicy, I get the following error message:

Policy operations on v2 application are disabled.

**Comment by didabel** [comment]
I get the same error message.

you have found a solution ?

**Comment by spongessuck** [comment]
@didabel no, we've been working exclusively with v1 apps since I opened this.

**Comment by billmath** [comment]
Hi @spongessuck 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

#please-close
