### ISSUE TITLE
Where can I find the AzureAD module source code?

### ISSUE THREAD

**Issue by KirkMunro** [Azure/azure-docs-powershell-azuread#226]
I've been trying to find the Azure AD module source code, but links from the PowerShell Gallery take me to the docs, and the docs repo doesn't mention where the source code can be found. Is Azure AD still closed source?

**Comment by lesterw1** [comment]
I'd like to know the answer to this as well.

**Comment by billmath** [comment]
Thank you for your issue.  The AzureAD module source code is currently not public.   

Thank you.
