### ISSUE TITLE
Get-AzureADUser does not return StrongAuthentication* data

### ISSUE THREAD

**Issue by darrenjrobinson** [Azure/azure-docs-powershell-azuread#227]
Get-AzureADUser doesn't return Azure MFA StrongAuthentication configuration information for users like Get-MSOLUser currently does?
Or is there another cmdlet that I haven't been able to find?

Get-MsolUser -UserPrincipalName "name@mydomain.com.au" | Where{$_.StrongAuthenticationRequirements -ne $null} | select UserPrincipalName,StrongAuthenticationMethods,StrongAuthenticationPhoneAppDetails,StrongAuthenticationRequirements,StrongAuthenticationUserDetails, StrongAuthenticationProofupTime

**Comment by billmath** [comment]
Hi @darrenjrobinson 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

#please-close
