### ISSUE TITLE
How to Update the SignInNames of an existing user?

### ISSUE THREAD

**Issue by dhuper01** [Azure/azure-docs-powershell-azuread#231]
How to update the signInNames of an existing users. I have tried doing it but it doesn't work out and throwing Request_BadRequest error!
Is there a issue existing with it?

**Comment by billmath** [comment]
Hi @dhuper01 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

Bill
