### ISSUE TITLE
Valid Types

### ISSUE THREAD

**Issue by DeanGross** [Azure/azure-docs-powershell-azuread#238]
What are the valid values for the Type parameter? The documentation states when we should use TokenLifetimePolicy but does not define what other choices are possible. 
When I run get-AzureADPolicy, I get a type = TokenIssuancePolicy so there must be several options for this parameter.

 Please document the string values  that are acceptable.

**Comment by billmath** [comment]
Hi @DeanGross 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill
