### ISSUE TITLE
Get-AzureADUser has no 'pagination' (-Skip) Support

### ISSUE THREAD

**Issue by lesterw1** [Azure/azure-docs-powershell-azuread#241]
The cmdlet **Get-AzureAdUser** has the -Top option, but there is no way to retrieve the next number of entries after that.  At minimum, this should be documented as a limitation of the cmdlet.

The cmdlet needs to add a -Skip (and -SkipToken) support -- functionality which is already supported by the underlying Graph API (see: [https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters](https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters)).  Otherwise, there is no efficient way to go through a large Active Directory (e.g., consider an Azure Automation Runbook which has severe memory limitations).

**Comment by billmath** [comment]
Hi @lesterw1 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill
