### ISSUE TITLE
Import-Module : Could not load file or assembly 'file:///C:\Program Files\WindowsPowerShell\Modules\MSOnline\1.1.183.17\Microsoft.Online.Administration.Automation.PSModule.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.

### ISSUE THREAD

**Issue by Rushirohit** [Azure/azure-docs-powershell-azuread#247]
Hi,

I create GUI tools using powershell and convert them to executable file. I unable to connect to MSOL as i am getting below error. Please suggest.

Import-Module : Could not load file or assembly 'file:///C:\Program Files\WindowsPowerShell\Modules\MSOnline\1.1.183.17\Microsoft.Online.Administration.Automation.PSModule.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.
At C:\Users\rushirohitk\AppData\Local\Temp\IXP000.TMP\ReportingToolIncludeAzure.ps1:43 char:1
+ Import-Module MSOnline
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], BadImageFormatException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by rarenet1976** [comment]
What is the fix.  Same issue

**Comment by thema27** [comment]
Same issue.

**Comment by billmath** [comment]
Hi @Rushirohit 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

Bill
