### ISSUE TITLE
Set-AzureADMSGroup no longer sets the SPOSite title

### ISSUE THREAD

**Issue by fredericklin** [Azure/azure-docs-powershell-azuread#248]
Set-AzureADMSGroup used to set the title property for the SPOSite for UnifiedGroup objects when the group name changed.   This is no longer the case. Is this expected behaviour?

Also should probably fill out the placeholders in this doc :)
https://docs.microsoft.com/en-us/powershell/module/azuread/set-azureadmsgroup?view=azureadps-2.0

**Comment by fredericklin** [comment]
I noticed that site titles will eventually be consistent with the Unified Group display name.  Others take a few minutes while others take hours.  If you can also comment on a timeframe expectation and whether the site titles will reach eventual consistency, that would be great (related to #1555).

**Comment by billmath** [comment]
Hi @fredericklin 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

Bill
