### ISSUE TITLE
Get-AzureADMSGroup not outputing MembershipRule or MembershipRuleProcessingState

### ISSUE THREAD

**Issue by johnathanhall** [Azure/azure-docs-powershell-azuread#251]
In the documentation it says that Get-AzureADMSGroup should be outputting the MembershipRule or MembershipRuleProcessingState; however when I run `Get-AzureADMSGroup -id $groupid` in get:
Id                           : 6b779628-272c-405b-935c-554e67fdab09
OdataType                    : 
Description                  : testing ipads
OnPremisesSyncEnabled        : 
DisplayName                  : Testing
OnPremisesLastSyncDateTime   : 
Mail                         : 
MailEnabled                  : False
MailNickname                 : 5446bd3e-f85e-4dc4-84bb-e120ccca6cbe
OnPremisesSecurityIdentifier : 
ProxyAddresses               : {}
SecurityEnabled              : True
GroupTypes                   : {DynamicMembership}
Visibility                   : 
CreatedDateTime              : 2018-09-05 5:13:23 PM
RenewedDateTime              : 2018-09-05 5:13:23 PM

Has something recently changed as i do remember being able to get the MembershipRule

**Comment by johnathanhall** [comment]
Fixed it my removing AzureAD module, Importing it again, then Connecting again.

**Comment by PlasmatikSteak** [comment]
> 
> 
> Fixed it my removing AzureAD module, Importing it again, then Connecting again.

I seem to have this problem with version 2.0.2.128.
Uninstalled and reinstalled to no avail.
Anybody who can guide me in the right direction?

**Comment by jcrainucdavis** [comment]
I am having the same issue with 2.0.2.130

**Comment by jcrainucdavis** [comment]
Found the solution: Use the AzureADPreview module
