### ISSUE TITLE
AzureAD help typo

### ISSUE THREAD

**Issue by martensnico** [Azure/azure-docs-powershell-azuread#254]
When running Get-Help Connect-AzureAD under "Related Links" it says "Disconnet-AzureAD" instead of "Disconnect-AzureAD". See screenshot for more details.

<img width="929" alt="disconnet-azuread" src="https://user-images.githubusercontent.com/32136609/51674295-8d8d0a00-1fd0-11e9-9516-e4d8b6718646.png">

**Comment by billmath** [comment]
Hi @martensnico 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill
