### ISSUE TITLE
parameters missing in module?

### ISSUE THREAD

**Issue by AlexanderHolmeset** [Azure/azure-docs-powershell-azuread#255]
set-azureadmsgroup PowerShell module is missing the -MembershipRule and -MembershipRuleProcessingState paratmeters. So is the documentation wronge or is there something wronge with the module?

**Comment by MrShannon007** [comment]
I noticed the same thing.  version 2.0.2.4 and 2.0.2.16 do not have the MembershipRule parameter.
`PS> Get-Module AzureAD

ModuleType Version    Name                                ExportedCommands                                                                                                                
---------- -------    ----                                ----------------                                                                                                                
Binary     **2.0.2.4**    AzureAD                             {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-AzureADDirectoryRoleMemb...



PS> Get-Command New-AzureADMSGroup | fl


Name             : New-AzureADMSGroup
CommandType      : Cmdlet
Definition       : 
                   New-AzureADMSGroup -DisplayName <string> -MailEnabled <bool> -MailNickname <string> -SecurityEnabled <bool> [-Description <string>] [-GroupTypes <List[string]>] 
                   [-Visibility <string>] [<CommonParameters>]
                   
Path             : 
AssemblyInfo     : 
DLL              : C:\Program Files\WindowsPowerShell\Modules\AzureAD\2.0.2.4\Microsoft.Open.MS.GraphV10.PowerShell.dll
HelpFile         : Microsoft.Open.MS.GraphV10.PowerShell.dll-Help.xml
**ParameterSets    : {-DisplayName <string> -MailEnabled <bool> -MailNickname <string> -SecurityEnabled <bool> [-Description <string>] [-GroupTypes <List[string]>] [-Visibility <string>] 
                   [<CommonParameters>]}**
ImplementingType : Microsoft.Open.MSGraphV10.PowerShell.NewMSGroup
Verb             : New
Noun             : AzureADMSGroup`

**Comment by johnathon-b** [comment]
Having the same issue.... Why hasn't anyone responded?

Bump

**Comment by billmath** [comment]
Parameter appears to be in the lasted version.
