### ISSUE TITLE
New-AzureADMSInvitation - Must "InviteRedirectUrl" be specified when "SendInvitationMessage" is $false?

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-docs-powershell-azuread#259]
As the title says, must "InviteRedirectUrl" be specified when "SendInvitationMessage" is $false?
For me it looks like "InviteRedirectUrl" is mandatory, but it makes no sense to specify it if you're not to send out the invite anyway.

* ["New-AzureADMSInvitation" documentation on GitHub](https://github.com/Azure/azure-docs-powershell-azuread/blob/master/azureadps-2.0/AzureAD/New-AzureADMSInvitation.md)
* ["New-AzureADMSInvitation" documentation on Microsoft Docs](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsinvitation?view=azureadps-2.0)

**Comment by WithHolm** [comment]
In my testing, this is mandatory. This defines the url the user is sent to after accepting invitation, and the flow when inviting is defined by AzureAD, and not this powershell module. However you can use  `https://localhost` when inviting (probably best when you are inviting other guests from the same tenant)
