### ISSUE TITLE
New-AzureADServicePrincipalPasswordCredential won't accept a SecureString

### ISSUE THREAD

**Issue by erictorbenson** [Azure/azure-docs-powershell-azuread#261]
I'm trying to manually create password secrets for Azure AD service principals. While doing so, I noticed that the behavior I was used to with `New-AzureRMADSpCredential` is no longer there. Previously, I would call this cmdlet with the `-Password` parameter and pass it a `SecureString`.

Apparently, `New-AzureADServicePrincipalPasswordCredential` will assign a random password if you don't specify a -Password switch. But if you pass a `SecureString`, the password is either blank or not what you thought it was. If you pass a `String`, the password you specified is applied (but the password is passed in cleartext on the command line.)

I see the help for the cmdlet shows the expected input as a `String`, so it "works as designed," but wouldn't it be a good idea to force this to be a `SecureString `in case we were logging output somewhere? I'm doing this to make Azure DevOps ARM endpoints and have to specify the password in cases where I don't have the rights to register applications and/or need to hand the credentials off to a third party.

Steps to reproduce:

```
Login-AzAccount
Connect-AzureAD
$spGuid = "<guid of Service Principal you want to add a password to>"
$password = "SuperS3cretAw3somePa55W0rd!!!"
$securepw = $password | ConvertTo-SecureString -AsPlainText -Force
```
Giving it the cleartext String works fine, and I can use the password as-is.

`New-AzureADServicePrincipalPasswordCredential -ObjectID $spGuid -Value $password`

```
CustomKeyIdentifier :
EndDate             : <date>
KeyId               :
StartDate           : <date>
Value               : <cleartext password that was just created>
```
Now, passing in the `SecureString `results in a blank Value, and the password is not usable -- i.e. I can't go into Azure DevOps or similar, enter that password and have it work.

`New-AzureADServicePrincipalPasswordCredential -ObjectID $spGuid -Value $securepw`

```
EndDate             : <date>
KeyId               :
StartDate           : <date>
Value               : 
```

**Comment by jordanmills** [comment]
Shouldn't be hard to go through the Microsoft-Windows-PowerShell log and pull those password parameters right out.

**Comment by billmath** [comment]
Hi @erictorbenson erict

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
