### ISSUE TITLE
Import-Module MSOnline

### ISSUE THREAD

**Issue by milbras** [Azure/azure-docs-powershell-azuread#262]
Windows Server 2012 R2, 64bit. 

I am not able to import MSOnline module running PowerShell(x86). I can install but not import. On the other side with PowerShell - 64bit I am able to install and to import the Module. 

How can I Import MSOnline module for x86 ? 

Import-Module : Could not load file or assembly 'file:///C:\Program Files(x86)\WindowsPowerShell\Modules\MSOnline\1.1.183.17\Microsoft.Online.Administration.Automation.PSModule.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.

When I start the C# code which call process PowerShell it always start powershell 32bit which does not contain MSOnline module. allthough I have specified different. I need to start either PowerShell 64 bit or to import MSOnline Module for 32 bit. Can someone help ?

var startInfo = new ProcessStartInfo()
{
    WorkingDirectory = tempDirectory,
    Verb = "runas",
    FileName = @"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    Arguments = @".\officePS.ps1",
    CreateNoWindow = false,
    UseShellExecute = false,
    ErrorDialog = false
};

startInfo.EnvironmentVariables["PROCESSOR_ARCHITECTURE"] = "AMD64";

**Comment by Yurisleidy** [comment]
Hi milbras, we are having exactly the same problem. Were you able to find a solution? Thanks!

**Comment by billmath** [comment]
Hi @milbras 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

Bill
