### ISSUE TITLE
Get-AzureADGroup -All requires $true explicitly specified

### ISSUE THREAD

**Issue by YuriySamorodov** [Azure/azure-docs-powershell-azuread#267]
While trying to get all groups we noticed it requires ```-All``` parameter. However, it the command would error out without ```$true``` being specified:

![image](https://user-images.githubusercontent.com/5260172/54708172-d6d28380-4b53-11e9-9263-489b43df679e.png)

It looks like ```-All`` parameter lacks for the default value.

Test environment:
```
$Host

Name             : ConsoleHost
Version          : 5.1.17134.590
InstanceId       : 3462812f-bc8a-4465-bf96-c87c821cb148
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
```

**Comment by billmath** [comment]
Hi  @YuriySamorodov 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
