### ISSUE TITLE
$true value is missing in -ForceChangePassword parameter..

### ISSUE THREAD

**Issue by o365tatsuyan** [Azure/azure-docs-powershell-azuread#276]
https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoluserpassword?view=azureadps-1.0#examples

-ForceChangePassword parameter should have "$true" value to enable this command let.

Current: 
Set-MsolUserPassword -UserPrincipalName "davidchew@contoso.com" -ForceChangePassword

Should update to 
Set-MsolUserPassword -UserPrincipalName "davidchew@contoso.com" -ForceChangePassword $true.

**Comment by sudeepku** [comment]
@o365tatsuyan thanks for your feedback. I am closing this as duplicate since you have  already logged this issue in https://github.com/Azure/azure-docs-powershell-azuread/issues/276

**Comment by sudeepku** [comment]
reopened. I closed the issue by accident.

**Comment by billmath** [comment]
Hi @sudeepku 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill
