### ISSUE TITLE
Get-AzureADAdministrativeUnitMember

### ISSUE THREAD

**Issue by JBines** [Azure/azure-docs-powershell-azuread#279]
Is limited to 100 members is missing the -all 

I have reverted to using the Get-MsolAdministrativeUnitMember for membership population for my scripts :(

**Comment by JBines** [comment]
@sudeepku  can you let us know if the azure ad preview is actively being maintained?

**Comment by andersgreen** [comment]
I hope there is a view limitation of 100 not a hardlimit to populate the unit with maximum 100 objects.

**Comment by ChrisAtMAF** [comment]
This is now fixed and Get-AzureADAdministrativeUnitMember supports the -All switch in module 2.0.2.105 - although documentation has not yet been updated https://github.com/MicrosoftDocs/azure-docs/issues/52650

**Comment by JBines** [comment]
Great news funny that this issue was raised a year before that one but was not actioned. Anyway time to update our script finally!!
