### ISSUE TITLE
Get-MSOLDomain has an error in Example #2

### ISSUE THREAD

**Issue by sudeepku** [Azure/azure-docs-powershell-azuread#280]
Originally reported by @marcuslongridge at https://github.com/MicrosoftDocs/feedback/issues/1330  

IMPORTANT: You can get your feedback addressed faster if you use the comment section for the article in which you encountered a problem.

Link to article:
https://docs.microsoft.com/en-us/powershell/module/msonline/get-msoldomain?view=azureadps-1.0

Problem:
What's wrong with the article?
Example # 2 should read "Get-MsolDomain -Domainname "contoso.com"" Instead of "Get-MsolDomain -Name "contoso.com""

**Comment by billmath** [comment]
Hi @sudeepku 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
