### ISSUE TITLE
Microsoft.Open.AzureAD.Model.AssignedLicenses accepts different object types

### ISSUE THREAD

**Issue by andrew951** [Azure/azure-docs-powershell-azuread#281]
It seems odd for the AddLicenses and RemoveLicenses to accept different object types. AddLicenses accepts Microsoft.Open.AzureAD.Model.AssignedLicense and RemoveLicenses accepts String. Can we standardize this so that both accept string or both accept the object since it can be slightly confusing?

**Comment by danielmeridew** [comment]
AddLicenses allows to specify disabled plans, RemoveLicenses does not and just required the string name of the license to revoke. It makes complete sense.

**Comment by billmath** [comment]
Hi @andrew951 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
