### ISSUE TITLE
Azure AD : Add-AzureADApplicationPolicy

### ISSUE THREAD

**Issue by didabel** [Azure/azure-docs-powershell-azuread#292]
J'utilise AzureADPreview version 2.0.2.17 pour associer une stratégie de durée de vie de jeton à une application enregistrée dans Azure AD, alors en utilisant Add-AzureADApplicationPolicy avec la commande suivante :
Add-AzureADApplicationPolicy -Id $app.ObjectId -RefObjectId $policy.Id
j'obtient l'erreur suivante 

Add-AzureADApplicationPolicy : Error occurred while executing AddApplicationPolicy
Code: Request_BadRequest
Message: Policy operations on v2 application are disabled.
InnerError:
  RequestId: f002dbe4-86b4-4906-83a5-058fd8f33c62
  DateTimeStamp: Thu, 23 May 2019 14:32:54 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
Au caractère Ligne:1 : 1
+ Add-AzureADApplicationPolicy -Id xxxddf73-50fe-4968-b2b7-xxxxxxxxxxxxx ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzureADApplicationPolicy], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.Add
   ApplicationPolicy

Des solutions pour résoudre ce problème ?
Merci.

**Comment by billmath** [comment]
Hi @didabel 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
