### ISSUE TITLE
Get-AzureADDevice -searchstring should validatenotnullorempty

### ISSUE THREAD

**Issue by einbahn** [Azure/azure-docs-powershell-azuread#295]
If I am passing a variable to the `-searchstring` parameter, and the variable happens to be null, then the cmdlet should error instead of returning everything in the tenant. For example, if I have some code like this:
```powershell
$intunedevice = get-intunemanageddevice -filter "devicename eq '$devicename'" 
get-azureaddevice -searchstring $intunedevice.devicename | remove-azureaddevice 
```
The above will erase all the devices (along with their bitlocker recovery keys and other crucial info) from the tenant if `$intunedevice` happens to be null. Very dangerous! Also the fact that `remove-azureaddevice` removes everything without asking for confirmation is also dangerous. It seems like to me if I'm passing nulls around, that shouldn't result in the erasure of all the devices in your tenant.

**Comment by billmath** [comment]
Hi @einbahn 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

Bill
