### ISSUE TITLE
App Registration Client Secret Description Encoding Issue

### ISSUE THREAD

**Issue by crowcoder** [Azure/azure-docs-powershell-azuread#296]
When I run this command (from cloud shell) I get an improperly encoded Description for the Client secret:
`az ad app create --display-name "SomeAppName" --credential-description "secret" --password "test" --end-date '2299-12-31'`

This is what it looks like in the portal:
![image](https://user-images.githubusercontent.com/4210624/58968956-e3469f80-8784-11e9-880a-7562f188cfda.png)

If I use a longer value for Description I get an error, presumably because the encoding increases the byte length beyond 32:

> When present, application key identifier cannot be empty and can be at most 32 bytes.\r\nParameter name: applicationKeyIdentifierValue"},"requestId":"3aeda8d8-763d-422f-8f44-30d56c2c1f4f","date":"2019-06-05T15:12:58"}}
> msrest.exceptions : When present, application key identifier cannot be empty and can be at most 32 bytes.
> Parameter name: applicationKeyIdentifierValue
> cli.azure.cli.core.util : When present, application key identifier cannot be empty and can be at most 32 bytes.

This is a partial debug output that shows the request body and 400 response because "customKeyIdentifier" is too long:

```
msrest.http_logger : Request body:
msrest.http_logger : {"availableToOtherTenants": false, "passwordCredentials": [{"startDate": "2019-06-05T15:12:57.866006Z", "endDate": "2299-12-31T00:00:00.000Z", "keyId": "d1fe0aae-d4c7-457a-9187-dee5538ec92d", "value": "test", "customKeyIdentifier": "//53AGgAYQB0ACAAaQBzACAAZwBvAGkAbgBnACAAbwBuAA=="}], "displayName": "ForTest", "identifierUris": []}
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : https://graph.windows.net:443 "POST /xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/applications?api-version=1.6 HTTP/1.1" 400 294
msrest.http_logger : Response status: 400
```

**Comment by josephtingiris** [comment]
Me too

**Comment by josephtingiris** [comment]
Looks related ... https://github.com/Azure/azure-docs-powershell-azuread/issues/202

**Comment by josephtingiris** [comment]
For me, the length of the values for `--display-name` + `--credential-description` can't be more than 40 characters.  As long as the concatenation of those values <= 40 then it works.

**Comment by fgheysels** [comment]
This issue still exists.  Very strange, since it is perfectly possible to create clientsecrets with descriptions that have a lenght > 16 characters via the portal.
How is the description being encoded ?  Is it being base64 encoded and is the length of the base64 encoded string checked ?

**Comment by billmath** [comment]
Hi @crowcoder 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

Bill

**Comment by HoLengZai** [comment]
@billmath 
Do you have any update on this issue after 3 months?

I might find a workaround after multiple trying, hope it will help someone
Using Azure CLI + Powershell (i guess same if you use Bash), it looks like this:
```
az ad app create `
--display-name "my-registered-app" `
--reply-urls "http://localhost" `
--available-to-other-tenants FALSE `
--credential-description "MaxCharacters_15" `
--end-date "2023-03-19" `
--native-app FALSE `
--oauth2-allow-implicit-flow FALSE `
--password "t12345678dfghdgdfsgfgfdgdfgdgdgdgfdgdgdsdfdsfsdfdsfsdfsfsdfsdfsfsfsdfgdfgfdgdgdf9" `
--required-resource-accesses "@D:\\Tmp\\my_requiredResourceAccess_manifest.json"
```

So as soon as the **"--credential-description" value is <=15 characters**, the command will run without any issue
Indeed through the Azure Portal, there is no max length for the Description and it works, so the azure cli should not limit the description length to 16 characters.

**Comment by Noel-Jones** [comment]
HoLengZai, you are a genius. It never occurred to me that the description was too long. Been tearing my hair out wondering why it worked last week but refused to work this week.
