### ISSUE TITLE
Newest version (2.0.2.25) is not signed.

### ISSUE THREAD

**Issue by jordanmills** [Azure/azure-docs-powershell-azuread#307]
Running "Update-Module azuread", it throws an error about it not being signed.  There's no catalog (which seems to be the case for previous versions) and Microsoft.Open.AzureAD16.Graph.PowerShell.dll and AzureAD.psd1 are not signed (which is not the same as previous versions).

PackageManagement\Install-Package : The version '2.0.2.25' of the module 'AzureAD' being installed is not catalog signed. Ensure that the version '2.0.2.25' of the module 'AzureAD' has the catalog file 'AzureAD.cat' and signed with the same publisher 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module 'AzureAD' with version '2.0.2.16' under the directory 'C:\Program
Files\WindowsPowerShell\Modules\AzureAD\2.0.2.16'. If you still want to install or update, use -SkipPublisherCheck parameter.

**Comment by L1ghtman2k** [comment]
I faced the same problem, I just added -SkipPublisherCheck like this: 
`Install-Module -Name AzureAD -Force -SkipPublisherCheck`

**Comment by jordanmills** [comment]
Do you want ants?  Because that's how you get ants.

**Comment by billmath** [comment]
@jordanmills Sorry for the delay on this.  I have just recently started working on this documentation.  I can let you know that the latest version 2.0.2.26 is signed.  Thanks!
