### ISSUE TITLE
Get-AzureADMSDeletedDirectoryObject Requires an Object Id

### ISSUE THREAD

**Issue by DougChandler** [Azure/azure-docs-powershell-azuread#313]
There is currently no way to retrieve all soft deleted users. The Get-AzureADMSDeletedGroup has an optional Id parameter to return all deleted groups.
This command seems to be very immature, the Id should check all ID fields (immutableId, UPN, email address, etc.) and should be optional.
There should also be a parameter for the object type (User/Group/etc.).
Other parameters such as -Filter, -All, -Top etc. should be added.

**Comment by billmath** [comment]
Hi @DougChandler 

Sorry for the delay in response.  I have opened a work item for this so that engineering can take a look and possibly address this.  At this point, I am going to go ahead and close this issue and will post any update I have here.  Thanks!

Bill
