### ISSUE TITLE
New-AzureADMSGroup doc issue

### ISSUE THREAD

**Issue by FrankHu-MSFT** [Azure/azure-docs-powershell-azuread#317]
per git issue : https://github.com/MicrosoftDocs/azure-docs/issues/34263#issuecomment-510978402

for link  : https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0/AzureAD/New-AzureADMSGroup.md

The documentation seems to be wrong here and we are currently engaging to fix this as soon as possible.

The MembershipRule is not currently supported in the New-AzureADMSGroup cmdlet of the AzureAD module.

This is because the underlying property in the Microsoft Graph (membershipRule) is only available on the "beta" endpoint. So this capability is only available in the AzureADPreview module.

You can install the AzureADPreview module side-by-side with the AzureAD module:

Install-Module AzureADPreview -Scope CurrentUser -AllowClobber

To be sure you're using the cmdlet from the correct module, unload the AzureAD module, and import the AzureADPreview module:

# Unload the AzureAD module (or continue if it's already unloaded)
Remove-Module AzureAD -ErrorAction SilentlyContinue
# Load the AzureADPreview module
Import-Module AzureADPreview
Then you should find you're able to create your dynamic group:

C:\> New-AzureADMSGroup -DisplayName "DisplayName" `
                        -MailNickname "Nickname" `
                        -MailEnabled $false `
                        -SecurityEnabled $true `
                        -GroupTypes @("DynamicMembership") `
                        -MembershipRule 'user.userType eq "Guest"' `
                        -MembershipRuleProcessingState "On"

Id                                   DisplayName        Description
--                                   -----------        -----------
<ID> <Dynamic-Group>

**Comment by billmath** [comment]
MembershipRule is no longer a parameter for the 2.0 version.  Closing.

**Comment by jspern** [comment]
It has been two years and the documentation is still not fixed. The example still uses the MembershipRule parameter.
