### ISSUE TITLE
$notAfter variable undefined

### ISSUE THREAD

**Issue by jflieben** [Azure/azure-docs-powershell-azuread#319]
$notAfter variable in the PS example is not defined (and thus won't work)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2f44fc7-086a-5a43-0fe3-7072b2885c37
* Version Independent ID: 9a026134-ee4b-5bff-82cd-f25d624e121d
* Content: [View user accounts with Office 365 PowerShell](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-user-accounts-with-office-365-powershell)
* Content Source: [Enterprise/powershell/view-user-accounts-with-office-365-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/blob/live/Enterprise/powershell/view-user-accounts-with-office-365-powershell.md)
* Service: **o365-administration**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by billmath** [comment]
This is an issue with the O365 documentation.  This is not the repository for the above article.
