### ISSUE TITLE
Can we use IN operator in AzureADUser cmdlt to filter user

### ISSUE THREAD

**Issue by Girishvtm** [Azure/azure-docs-powershell-azuread#322]
Can we use IN operator in AzureADUser cmdlt to filter user like Get-AzureADUser -All $true -Filter "Department" IN ('IT','HR','Fin').

**Comment by moorereason** [comment]
There is no `IN` operatorin the [oData filter syntax](https://www.odata.org/documentation/odata-version-3-0/odata-version-3-0-core-protocol/#queryingcollections).  You need to do something like this:

```
Get-AzureADUser -Filter "Department eq 'IT' or Department eq 'HR' or Department eq 'Fin'"
```

**Comment by Girishvtm** [comment]
Yes, but there is a limit that only 10 OR can be used in a condition.

**Comment by billmath** [comment]
Hi @Girishvtm 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
