### ISSUE TITLE
Example 1 in Doc for Set-MsolUserPassword doesn't work

### ISSUE THREAD

**Issue by NickDorak** [Azure/azure-docs-powershell-azuread#323]
In this doc: https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-1.0/MSOnline/Set-MsolUserPassword.md
Example 1 doesn't work. 
Set-MsolUserPassword : Missing an argument for parameter 'ForceChangePassword'. Specify a parameter of type 'System.Nullable`1[System.Boolean]' and try again.
Need to add $True to end of example.

**Comment by billmath** [comment]
Hi @NickDorak 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
