### ISSUE TITLE
New-AzureADMSGroupLifecyclePolicy : Code: Unauthorized Message: Request does not contain scope or roles claim.

### ISSUE THREAD

**Issue by Sambsamb** [Azure/azure-docs-powershell-azuread#332]
What are the minimum required permissions to invoke this cmdlet?
I'm running this cmdlet 

New-AzureADMSGroupLifecyclePolicy -GroupLifetimeInDays 365 -ManagedGroupTypes All -AlternateNotificationEmails sam.b@domain.com -Verbose

under a service principal who has the 'owner' role on the current subscription. I'm getting the message:

New-AzureADMSGroupLifecyclePolicy : Error occurred while executing NewGroupLifecyclePolicy 
Code: Unauthorized
Message: Request does not contain scope or roles claim.

Currently loaded modules:

Get-Module | FT Name,Version -a 

Name                            Version  
----                            -------  
Az.Accounts                     1.5.2    
AZSBTools                       1.160.100
AzureADPreview                  2.0.2.27 
ImportExcel                     5.4.5    
ISE                             1.0.0.0  
Microsoft.PowerShell.Management 3.1.0.0  
Microsoft.PowerShell.Security   3.0.0.0  
Microsoft.PowerShell.Utility    3.1.0.0  
Microsoft.WSMan.Management      3.0.0.0  
MicrosoftTeams                  1.0.1    
PackageManagement               1.0.0.1  
pki                             1.0.0.0  
PowerShellGet                   1.0.0.1

**Comment by billmath** [comment]
Hi @Sambsamb 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
