### ISSUE TITLE
Get-AzureADMSLifecyclePolicyGroup: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by OlveMM** [Azure/azure-docs-powershell-azuread#333]
Get-AzureADMSLifecyclePolicyGroup throws error:

```
Get-AzureADMSLifecyclePolicyGroup : Object reference not set to an instance of an object.

    + CategoryInfo          : NotSpecified: (:) [Get-AzureADMSLifecyclePolicyGroup], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.Open.MSGraphBeta.PowerShell.GetLifecyclePolicyGroup
````
Both locally and from Azure Automation.
This started happening sometime after the 19th of August.

**Comment by netracksolutions** [comment]
Looks like this happened on the 23/08/2019 in our tenant, we had automation running successfully before this date and then it started failing with the same error as above.

**Comment by netracksolutions** [comment]
Looks like its working again now....

**Comment by OlveMM** [comment]
Yep, tested ok here as well.. Thanks for the update.
