### ISSUE TITLE
Add and Remove Licenses in Same Transaction/Command?

### ISSUE THREAD

**Issue by aakash-shah** [Azure/azure-docs-powershell-azuread#338]
Hello!  At https://docs.microsoft.com/en-us/powershell/module/azuread/set-azureaduserlicense?view=azureadps-2.0, the page includes an example of how to add and remove a license.  The example uses 2 separate lines to do this by first adding a license, and then subsequently by removing the license not needed.

However per this page, it appears that this we can specify entries in _both_ AddLicenses and RemoveLicenses and have Set-AzureADUserLicense process both the additions and removals in the same line.  Is there a reason why this was not shown in the example?

I ask this since I have heard some people report that it is not recommend to add and remove licenses very closely since it can cause problems.  However, I see that the web console has the ability to replace licences as per https://docs.microsoft.com/en-us/office365/admin/subscriptions-and-billing/assign-licenses-to-users?view=o365-worldwide#move-users-to-a-different-subscription, but it doesn't detail how to do this in PowerShell.  So I'm trying to get confirmation whether:

1. We can technically add and remove licenses within a single line/command, and
2. It is or is not recommended to add and remove licenses within a single line/command.

Thanks!

**Comment by billmath** [comment]
Hi @aakash-shah 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
