### ISSUE TITLE
Remove-AzureADGroupMember documentation incomplete

### ISSUE THREAD

**Issue by jflieben** [Azure/azure-docs-powershell-azuread#342]
https://docs.microsoft.com/en-us/powershell/module/azuread/remove-azureadgroupmember?view=azureadps-2.0 should mention that this command ONLY works on Azure AD standard (security) groups, or at least specifically mention that it does not work with distribution groups.

**Comment by billmath** [comment]
@jflieben 

Thank you for your issue.  This content is auto-generated and only includes what the developers add.  I have created a work item to have them check to see if they want to add this.  Thank you!

Bill
