### ISSUE TITLE
Get-AzureADServiceAppRoleAssignment returns nothing for a Service Principal I know has App Roles

### ISSUE THREAD

**Issue by TWolverson** [Azure/azure-docs-powershell-azuread#344]
1) Connect-AzureAD -TenantId [id of my tenant]

I am the owner of the tenant, it's my MSDN free credits subscription

2) Get-AzureADServicePrincipal -SearchString "name of my app registration"

returns 1 record, from which I take the ObjectId

3) GetAzureADServiceAppRoleAssignment -ObjectId [objectid of my service principal]

returns nothing, even though I know this service principal has app roles assigned. I've also tried passing the Id _of the role_, which returns Error occurred while executing GetServicePrincipalAppRoleAssignments 
Code: Request_ResourceNotFound

What am I doing wrong?

**Comment by TWolverson** [comment]
My mistake - I was trying to list app roles when the permissions I had assigned were actually OAuth2Permission objects and not in the appRoles section of the manifest. Adding appRoles to the manifest and assigning those works the way I expected.

**Comment by billmath** [comment]
Sounds like this was resolved.  Thanks!
