### ISSUE TITLE
Get-MsolDevice shows duplicate information and other devices are not showed

### ISSUE THREAD

**Issue by davortsan** [Azure/azure-docs-powershell-azuread#345]
When I execute **Get-MsolDevice -All -RegisteredOwnerUpn**, there are multiple devices that are not returned and there are duplicate information too. 
Thanks!

**Comment by davortsan** [comment]
Sorry, there is n error in the command…. **Get-MsolDevice -All -ReturnRegisteredOwners** is the command...

**Comment by billmath** [comment]
Hi @davortsan 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
