### ISSUE TITLE
Revoke-AzureADSignedInUserAllRefreshToken & access tokens revokation?

### ISSUE THREAD

**Issue by thi-baut** [Azure/azure-docs-powershell-azuread#350]
Hi,

The "Revoke-AzureADSignedInUserAllRefreshToken" documentation mentions that "The cmdlet also invalidates <tokens> issued to session cookies in a browser for the user." 

Can we please clarify what are the <tokens> mentioned above: only OAuth 2.0 refresh tokens or also OAuth 2.0 access tokens?

Thanks,

**Comment by billmath** [comment]
Hi @thi-baut 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
