### ISSUE TITLE
Password-less 

### ISSUE THREAD

**Issue by lousimonetti** [Azure/azure-docs-powershell-azuread#359]
Using the Connect-AzureAD command, there is no option for the user Login with a Security Key. Is there a plan to enable FIDO2 and security key authentication in the module?

**Comment by billmath** [comment]
Hi @lousimonetti 

Thank you for your issue submission.  Unfortunately, this is not a documentation issue and these issues are specifically for problems with the documentation.

Thanks!

Bill
