### ISSUE TITLE
AzureAD 2.0.2.52 is not signed by a trusted Publisher

### ISSUE THREAD

**Issue by KSchlobohm** [Azure/azure-docs-powershell-azuread#360]
Related to Issue [307](https://github.com/Azure/azure-docs-powershell-azuread/issues/307) the AzureAD module now appears to be signed by an untrusted publisher.

![Untrusted Publisher](https://user-images.githubusercontent.com/23503973/68253037-8e85aa00-ffec-11e9-807c-9af7bc44f2c3.png)

**Comment by SoftwareEngineerChris** [comment]
Not signed by a trusted publisher as of 2.0.2.76. Would make me feel more secure if it was.

**Comment by billmath** [comment]
This has been resolved.  Thank you.
