### ISSUE TITLE
The Get-AzureADServicePrincipalOAuth2PermissionGrant example is wrong

### ISSUE THREAD

**Issue by alexanderdondokov** [Azure/azure-docs-powershell-azuread#365]
The Powershell example is missing a $ sign in declaration of ServicePrincipalId variable

**$**ServicePrincipalId = (Get-AzureADServicePrincipal -Top 1).ObjectId
Get-AzureADServicePrincipalOAuth2PermissionGrant -ObjectId $ServicePrincipalId

**Comment by billmath** [comment]
Hi @alexanderdondokov 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
