### ISSUE TITLE
Get-MsolRoleMember help file Example #1 does not use the cmdlet

### ISSUE THREAD

**Issue by dbird03** [Azure/azure-docs-powershell-azuread#368]
Example # 1 in the Get-MsolRolemember help file uses the Get-MsolRole cmdlet, but it doesn't use the Get-MsolRoleMember cmdlet.

[Get-MsolRoleMember help file](https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-1.0/MSOnline/Get-MsolRoleMember.md)

**Comment by billmath** [comment]
Hi @dbird03 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
