### ISSUE TITLE
JsonReader Error using Set-AzureADObjectSetting and Set-AzureADDirectorySetting (AzureADPreview)

### ISSUE THREAD

**Issue by WayneJSawyer** [Azure/azure-docs-powershell-azuread#369]
Using AzureADPreview (versions 2.0.2.53, 2.0.2.62, 2.0.2.77), and trying to set tenant-wide O365 Group Naming Convention ("PrefixSuffixNamingRequirement") or changing the Group Creation enabled ("EnableGroupCreation"), or changing "AllowGuests" setting for a specific group, we are seeing the following error when the script executes.

**Error reading JToken from JsonReader. Path '', line 0, position 0.**

This occurs in any script calling Set-AzureADDirectorySetting or Set-AzureADObjectSetting, even if following Microsoft example documentation

Seems like it might be related to a missing dependency or a specific version of PowerShell and/or Windows.

Fails on a Win 10 device with PSVersion = 5.1.17763.771

Works on a different Win 10 device with PSVersion = 5.1.18362.145

Not sure if there are other dependencies, but need to be able to run it on the 17763 version of PowerShell

**Comment by billmath** [comment]
Hi @WayneJSawyer 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
