### ISSUE TITLE
Trying to find a way to get all SKU size and vCPUs across multiple Azure subscriptions

### ISSUE THREAD

**Issue by nguyenjm92** [Azure/azure-docs-powershell-azuread#371]
Hi all,

I'm fairly new to PowerShell and I'm trying to write out a PowerShell script that collects the current SKU size and vCPU size from VMs across multiple subscriptions. I have already connected to my account with Connect-AzureRmAccount so everything else is what I pasted.

I run into an issue when I try to set the context of each subscription. I get all the subscriptions that is associated with my account that look like what I specified in the Where-Object piece. 

I run a foreach loop with each subscription and try to set the context for each one. I run into an issue where it gives me this error:

Set-AzureRmContext : Please provide a valid tenant or a valid subscription.

If I provide the subscription manually, it sets the context to that subscription. But not when I run it through the foreach loop.

`$AllSubscriptions = Get-AzureRmSubscription | select Name | sort Name
$ProductionSubscriptions = $AllSubscriptions | Where-Object {($_.Name -like "example1*") -or ($_.Name -like "example2*")}

Write-Host = $ProductionSubscriptions

foreach ($ProductionSub in $ProductionSubscriptions) {
    
    $ProductionSub
    
    $AzureRmContext = Set-AzureRmContext -Subscription $ProductionSub

}`

Once that works out, I'm also trying to figure out how I would grab all the resources and VMs and then place them into Get-AzureRmVmSize.

**Comment by billmath** [comment]
Hi @nguyenjm92 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
