### ISSUE TITLE
Azure automation runbook cannot find assembly - Microsoft.Online.Administration.StrongAuthenticationRequirement

### ISSUE THREAD

**Issue by Shadoxity** [Azure/azure-docs-powershell-azuread#372]
There seems to be an issue with modules that get loaded to azure automation runbooks. 

I am trying to use a powershell to enable MFA on accounts but it appears to be impossible. It seems like there is something missing in the module or azure automation.

Running the following, it fails to load the assembly type
$auth = New-Object -TypeName Microsoft.Online.Administration.StrongAuthenticationRequirement
$auth.RelyingParty = "*"
$auth.State = "Enabled"
$auth.RememberDevicesNotIssuedBefore = (Get-Date)

Works fine in powershell in local.
AzureAd, MSOnline modules installed in azure automation account.
Please help!

New-Object : Cannot find type [Microsoft.Online.Administration.StrongAuthenticationRequirement]: verify that the 
assembly containing this type is loaded.
At line:10 char:9
+ $auth = New-Object -TypeName Microsoft.Online.Administration.StrongAu ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
 
The property 'RelyingParty' cannot be found on this object. Verify that the property exists and can be set.
At line:11 char:1
+ $auth.RelyingParty = "*"
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'State' cannot be found on this object. Verify that the property exists and can be set.
At line:12 char:1
+ $auth.State = "Enabled"
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'RememberDevicesNotIssuedBefore' cannot be found on this object. Verify that the property exists and can 
be set.
At line:13 char:1
+ $auth.RememberDevicesNotIssuedBefore = (Get-Date)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

**Comment by Shadoxity** [comment]
Trying to manually import modules did not work. However forcing an import-module msonline at the start of the script even though it was already loaded seemed to fix it.

**Comment by billmath** [comment]
Hi  @Shadoxity 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
