### ISSUE TITLE
Set-AzureADApplication: can't change RequiredResourceAccess for app when allowPublicClient = true

### ISSUE THREAD

**Issue by sadomovalex** [Azure/azure-docs-powershell-azuread#373]
If we set allowPublicClient to true for AAD app:
![allowPublicClient](https://1.bp.blogspot.com/-D8zAzXWtLiU/XgXmeUAhl8I/AAAAAAAAH7Q/hGr7l4K6rPAR29zBbEpgcDk-kKe4AloTwCLcBGAsYHQ/s1600/2019-12-27_13-57-39.png
)
and then will try to add more permissions e.g. to Graph API:
```powershell
$tokensApp = Get-AzureADApplication | Where-Object { $_.AppId -eq "..." }
$requiredResourceAccess = $tokensApp.RequiredResourceAccess
$graphPermissions = $requiredResourceAccess | Where-Object { $_.ResourceAppId -eq "00000003-0000-0000-c000-000000000000" }
# add Sites.Read.All delegated permission
$perm = New-Object -TypeName "Microsoft.Open.AzureAD.Model.ResourceAccess"-ArgumentList "205e70e5-aba6-4c52-a976-6d2d46c48043","Scope"
$graphPermissions.ResourceAccess.Add($perm)

Set-AzureADApplication -ObjectId $tokensApp.ObjectId -RequiredResourceAccess $requiredResourceAccess
```

Then Set-AzureADApplication will throw the following error:

> Set-AzureADApplication : Error occurred while executing SetApplication
> Code: Request_BadRequest
> Message: Property requiredResourceAccess.resourceAccess is invalid.
> Details: PropertyName  - requiredResourceAccess.resourceAccess, PropertyErrorCode  - GenericError
> HttpStatusCode: BadRequest
> HttpStatusDescription: Bad Request
> HttpResponseStatus: Completed
> At line:1 char:1
> + Set-AzureADApplication -ObjectId $tokensApp.ObjectId -RequiredResourc ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Set-AzureADApplication], ApiException
>     + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.SetApplication

![error](https://1.bp.blogspot.com/-5quqInMCnG4/XgXn329KThI/AAAAAAAAH7c/d4pxkE_orBUtMMOdl4iClX5G43mG0X-XQCLcBGAsYHQ/s1600/2019-12-27_14-00-23.png)

When allowPublicClient is set to false this code works properly and successfully changes configured permissions list.

**Comment by attilabalazsy** [comment]
Hi,

I'm having similar issues. Once I set the publicClient=True, I'm not able to add Graph application permissions. I've tried to hack it, by creating the app as Public=True, to have the correct Authentication Platform created, then changing the IsPublic to false and set the Application permissions. The problem with this hack is, that changing the PublicClient value will change the Auth Platform as well.

It is really saddening, that there are PS commands to manage the apps, but are allowing only one case ...

Any suggestion here?

Thanks,
Attila

**Comment by billmath** [comment]
Hi @sadomovalex 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

**Comment by srudin** [comment]
As always Microsoft is extremly helpful with problems that occur because there stuff is not working as it should. Almost one year until a response is posted and then it is a copy/paste template saying to get help from somewhere else. Thank you very much.

Oh and yes, I do have the same problem as the other people who were posting on this thread.

**Comment by TanmayDharmaraj** [comment]
I echo @srudin 's sentiment. Adding my 2 cents here with a different error i found. Almost certain this will not be worked up on by Microsoft considering its been closed and not fixed yet. 
I am using a slightly "funky" identifier URI but can observe the same code posted by op not working when switching public client off and on.

```
$tokensApp = Get-AzureADApplication -ObjectId "b1b0de21-add0-4ee2-badc-d1024275de54"
$tokensApp.IdentifierUris 
>> urn:tst:service-name:portal

```
I get the below error, 

```
Set-AzureADApplication : Error occurred while executing SetApplication
Code: Request_BadRequest
Message: Property identifierUris is invalid.
RequestId: e7c317ac-4b9f-436e-ac1d-4bfa92ec44cd
DateTimeStamp: Mon, 25 Jan 2021 09:00:01 GMT
Details: PropertyName  - identifierUris, PropertyErrorCode  - GenericError
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ Set-AzureADApplication -ObjectId $tokensApp.ObjectId -RequiredResourc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzureADApplication], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.SetAppl
   ication
```

**Comment by sadomovalex** [comment]
for those who is interested: for original problem we found the following workaround using 2 another cmdlets Get-AzureADMSApplication and Set-AzureADMSApplication:
```
$azureAdMsApps = Get-AzureADMSApplication 
$azureAdMsApp = $azureAdMsApps | Where-Object { $_.AppId -eq $appId }
Set-AzureADMSApplication -ObjectId $azureAdMsApp.Id -IsFallbackPublicClient $value | Out-Null
````
