### ISSUE TITLE
New-AzureRmADApplication/Set-AzureRmADApplication: not possible to add reply url for Public client/Native app

### ISSUE THREAD

**Issue by sadomovalex** [Azure/azure-docs-powershell-azuread#375]
With New-AzureRmADApplication and Set-AzureRmADApplication it is possible to set reply urls for Azure AD app:

```powershell
$replyUrls = @()
$replyUrls += "url1"
$replyUrls += "url2"
...
New-AzureRmADApplication -DisplayName ... -ReplyUrls $replyUrls
````

However all specified reply urls will be added with Type = "Web":
![](https://4.bp.blogspot.com/--HwBe9k6Rko/Xg3k2m4bEJI/AAAAAAAAH74/Dq7sxnarMKgFwUXzaYfKyVBqy_KVIIC-QCLcBGAsYHQ/s1600/2020-01-02_15-40-24.png)

I.e. it is not possible to specify "Public client/native" type for reply url.

**Comment by billmath** [comment]
Hi @sadomovalex 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
