### ISSUE TITLE
When a web proxy blocks usage of the Get-AzureADUser cmdlet...

### ISSUE THREAD

**Issue by DGDC** [Azure/azure-docs-powershell-azuread#378]
This is to report and record for those searching on an error message an error that occurs when a web proxy blocks usage of the Get-AzureADUser cmdlet.

Some organizations place restrictions on which user-agents are allowed to operate using web proxies that block unauthorized clients. This is commonly done to restrict usage of unapproved browser software.

The Get-AzureADUser cmdlet identifies itself using the user-agent string "Swagger-Codegen/1.4.0.0/csharp" or similar. If the client-agent is blocked then the web proxy is likely to return an error message such as "You are not using an approved web browser..." Such errors are invalid return values and will result in a cmdlet error. For example, `Get-AzureADUser : Unexpected character encountered while parsing value: <. Path '', line 0, position 0.`

If this occurs then the Get-AzureADUser cmdlet will need to be approved for use and specifically allowed by the web proxy. Alternatively, a local proxy can be used to impersonate an approved user-agent by altering the user-agent string within the web request. The Fiddler Web Debugger supports such a configuration (Rules > User-Agents).

Note that the Invoke-WebRequest cmdlet -UserAgent parameter is not applicable workaround as the Get-AzureADUser cmdlet does not invoke such a request.

Projects should consider how their code and component code identifies itself and behaves in regards to an environment's security configuration. In this case not many organizations will understand how adoption of Azure AD and thus PowerShell cmdlets will require web proxy approval for the Swagger-Codegen user-agent.

**Comment by billmath** [comment]
Hi @DGDC 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
