### ISSUE TITLE
What are valid ProviderId's for Get-AzureADMSPrivilegedResource / Is AzureAD Roles supported

### ISSUE THREAD

**Issue by andyjballgit** [Azure/azure-docs-powershell-azuread#380]
found this - https://gotoguy.blog/tag/azure-ad-pim/

Also any ETA on when the *ADMNSPriv* functions will be release

**Comment by billmath** [comment]
Hi @andyjballgit 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
