### ISSUE TITLE
All Assignments not Being Returned

### ISSUE THREAD

**Issue by claboy-coh** [Azure/azure-docs-powershell-azuread#381]
I have users that are not returned when using Get-AzureADServiceAppRoleAssignment -All.
However, they do show up in the GUI and they are returned when using Get-AzureADServiceAppRoleAssignment -All | ? {$_.PrincipalId -eq "specific-principle-id-here"}

**Comment by billmath** [comment]
Hi @claboy-coh 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

#please-close
