### ISSUE TITLE
New-AzureADApplicationProxyApplication Internal and External URL Type is incorrect

### ISSUE THREAD

**Issue by bloader-nrma** [Azure/azure-docs-powershell-azuread#382]
Details for Internal and External URL values is wrong when parsing variables to the cmdlet, string is not an accepted type when using variables.  

When a variable is used instead of a inline string the object must be of the [System.URI] class otherwise you will receive the below error which is not very informative and without access to the source code for the module makes it extremely difficult to diagnose.  

New-AzureADApplicationProxyApplication : Error occurred while executing NewApplication 
Code: Request_BadRequest
Message: One or more properties contains invalid values.
RequestId: 
DateTimeStamp: 
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed

At line:3 char:9
+         New-AzureADApplicationProxyApplication  -DisplayName "$($AppP ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureADApplicationProxyApplication], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.MS.GraphV10.PowerShell.Custom.Cmdlet.NewApplicationProxyApplication

**Comment by billmath** [comment]
Hi @bloader-nrma 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
