### ISSUE TITLE
New-AzureADServicePrincipal and applicationID parameter creates different object?

### ISSUE THREAD

**Issue by SidBarker** [Azure/azure-docs-powershell-azuread#383]
Hello everyone!

When i trying to run code below
```
$ServicePrincipalName = "MY SPN name"
$ScopeSubscriptionId = "Subscription ID"

$AzureAdApplication = New-AzADApplication -DisplayName $ServicePrincipalName -HomePage "https://$ServicePrincipalName.local" -IdentifierUris "https://$ServicePrincipalName.com" -ErrorAction Stop

$sp = New-AzADServicePrincipal -ApplicationId $AzureAdApplication.ApplicationId -Scope /subscriptions/$ScopeSubscriptionId -ErrorAction Stop
```

I'am unable to retrive secret property from "$sp" object. I totaly know that it's secret string and should be accesed like this:

```
$BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($sp.Secret)
$UnsecureSecret = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)
```

When I delete ApplicationId parameter from second line, everything works correctly. <confused>
```
$sp = New-AzADServicePrincipal -DisplayName $ServicePrincipalName -Scope /subscriptions/$ScopeSubscriptionId -ErrorAction Stop
```

Any ideas why it works like this? Although I observed that this behavior occurred on last days.

**Comment by billmath** [comment]
Hi @SidBarker 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
