### ISSUE TITLE
Anglebrackets are not escaped, leading to missing content

### ISSUE THREAD

**Issue by henriksen** [Azure/azure-docs-powershell-azuread#384]
**Link to article:**
https://docs.microsoft.com/en-us/powershell/azure/active-directory/using-extension-attributes-sample?view=azureadps-2.0

**Problem:**
There's a paragraph with text that's supposed to say
> Note that the Name of the new property is generated from the format "Extension_" + &lt;objectID of your placeholder application&gt; + "_" + &lt;the name of your new property&gt;.

But since the anglebrackets aren't encoded properly it reads as: 
> Note that the Name of the new property is generated from the format "Extension_" + + "_" + . 

There's a PR for this that's been untouched for a while: #208

**Comment by billmath** [comment]
@henriksen Thank you for raising this issue and sorry for the delay.  I have fixed this and you should see it live by tomorrow.  Thanks!

Bill
