### ISSUE TITLE
Set-AzureADUserExtension inconsistent behavior with ExtensionAttribute1-15

### ISSUE THREAD

**Issue by jaffadog** [Azure/azure-docs-powershell-azuread#389]
Set-AzureADUserExtension can be used to update extensionAttribute1 thorugh extensionAttribute15 of cloud accounts - including guest accounts. For example, the following works - where the credentials used have at least the User Administrator role:

```
$credential = (Get-Credential)
Connect-AzureAD -Credential $Credential
$user = (Get-AzureADUser -Top 1 -Filter "userType eq 'Guest'")
Set-AzureADUserExtension -ObjectId $user.ObjectId -ExtensionName "extensionAttribute11" -ExtensionValue "test3"
```

But the following does not work - where the service principal used has Directory.ReadWrite.All app permissions from both Microsoft Graph and AAD Graph:

````
Connect-AzureAD -TenantId $tenant -ApplicationId$app -CertificateThumbprint $thumb
$user = (Get-AzureADUser -Top 1 -Filter "userType eq 'Guest'")
Set-AzureADUserExtension -ObjectId $user.ObjectId -ExtensionName "extensionAttribute11" -ExtensionValue "test3"
````

Results in the following error:

````
Set-AzureADUserExtension : Error occurred while executing SetUser 
Code: Request_BadRequest
Message: Attempt made to write to non-existent property 'extensionAttribute11' of resource 'User'.
RequestId: 7ea02b13-c030-44f3-a03b-0fbe01a069a4
DateTimeStamp: Thu, 27 Feb 2020 14:21:04 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ Set-AzureADUserExtension -ObjectId $userid -ExtensionName "extensionA ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzureADUserExtension], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD.Graph.PowerShell.Custom.SetAzureADUserExtension
````

Is this a permissions issue?

**Comment by billmath** [comment]
Hi @jaffado

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

**Comment by ChrisAtMAF** [comment]
@jaffadog - just seen your issue here & was looking at this myself. I wonder if you've tried the Mail permissions and/or User permissions with your service principal? It's only that extensionAttribute* are technically Exchange attributes, so might need those permissions as well?

Let us know if you get it to work.

https://docs.microsoft.com/en-us/graph/permissions-reference#mail-permissions
https://docs.microsoft.com/en-us/graph/permissions-reference#user-permissions
