### ISSUE TITLE
Get-AzureADApplicationServiceEndpoint: how to get endtpoints!

### ISSUE THREAD

**Issue by swinster** [Azure/azure-docs-powershell-azuread#395]
Hi,

We have an Azure AD app, and we need to get the `OAuth 2.0 authorization` and `OAuth 2.0 token` endpoint associated with the App. 

Running 

```
Get-AzureADApplicationServiceEndpoint -ObjectId  <ObjectId_of_Azure_App>
```

Does not error, but returns no information (result is `$null`). How do we get the endpoints?

**Comment by swinster** [comment]
![image](https://user-images.githubusercontent.com/8142964/77685183-f2f0d800-6f92-11ea-81fd-69b82b521695.png)

**Comment by billmath** [comment]
Hi @swinster 

Thank you for your issue submission.  Unfortunately, this appears to be a support/consult issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
