### ISSUE TITLE
Set-AzureADUser has unicode U+b200 in it

### ISSUE THREAD

**Issue by Mister-JJ** [Azure/azure-docs-powershell-azuread#398]
I learned my lesson on copying code from online, I'm not sure which one I copied, but one of the Set-AzureADUser examples has a zero width space between the "-" and the "A" and throws an error if it is tried to run in ISE, shows up as a "?" and regular Powershell.

**Comment by billmath** [comment]
Hi @Mister-JJ 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
