### ISSUE TITLE
Invalid link in documentation

### ISSUE THREAD

**Issue by jonwbstr** [Azure/azure-docs-powershell-azuread#400]
The sentence "For more information, please refer to [this link](https://msdn.microsoft.com/powershell/gallery/readme) For more detailed info..." points to a broken link, and seems to be missing a period on this page

https://docs.microsoft.com/en-us/powershell/module/Azuread/?view=azureadps-2.0 on [github](https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0/AzureAD/AzureActiveDirectory.md)

Also, I was wondering if there was a particular reason the above page doesn't have a button for submitting issues with the page.

Thanks!

**Comment by ruffy91** [comment]
Can confirm that the link is still not working

**Comment by billmath** [comment]
@jonwbstr Thank you for the issue and sorry for the delay.  This has been fixed and you should see it live by tomorrow. 

Thanks!

Bill

#please-close
