### ISSUE TITLE
Get-AzureADServicePrincipalOwner

### ISSUE THREAD

**Issue by csmurthy** [Azure/azure-docs-powershell-azuread#402]
This command is not returning all the owners.

**Comment by billmath** [comment]
Hi @csmurthy 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

#please-close
