### ISSUE TITLE
SupportedServices are not defined

### ISSUE THREAD

**Issue by PsychoData** [Azure/azure-docs-powershell-azuread#403]
I was reviewing https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0/AzureAD/Set-AzureADDomain.md 
And I cannot find a list of the SupportedServices. 

I want to set this up and get the verification records associated with them, but I cannot find what the SupportedServices are. 

From some random blog posts and checking my other customer tenants I have found that 'Email' and "OfficeCommunicationsOnline' are working options but I don't know if there are more. These should be listed (and preferably validate-set for Auto completion)

**Comment by billmath** [comment]
Hi @PsychoData 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  You are correct and this should have been added to the source.  The cmdlt reference is auto-generated, so I need to get the devs to update it.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
