### ISSUE TITLE
Get-AzureADPolicy - Request_InvalidRequestUrl Error

### ISSUE THREAD

**Issue by mikepugh** [Azure/azure-docs-powershell-azuread#404]
This cmdlet appears to be broken, receiving this error:

`Message: Request url was invalid. The request should be like /tenantdomainname/Entity or $metadata. Tenant domain name can be any of
the verified, unverified domain names or context id.`

I'm running v2.0.2.89 of AzureADPreview

**Comment by billmath** [comment]
Hi @mikepugh 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

#please-close
