### ISSUE TITLE
Could not load AzureADDirectorySetting in Cloud Shell

### ISSUE THREAD

**Issue by Icaruslau** [Azure/azure-docs-powershell-azuread#407]
**I have indeed tried reinstalling the latest AzureADPreview but still getting no hit to get the AzureADDirectorySetting CMDlet:**

PS /home/lauic_a/clouddrive> AzureADpreview\connect-azureAD
AzureADpreview\connect-azureAD: The module 'AzureADpreview' could not be loaded. For more information, run 'Import-Module AzureADpreview'.
PS /home/lauic_a/clouddrive> import-module AzureADpreview -verbose
VERBOSE: Loading module from path '/home/lauic_a/.local/share/powershell/Modules/AzureADPreview/2.0.2.89/AzureADPreview.psd1'.
VERBOSE: Loading 'FormatsToProcess' from path '/home/lauic_a/.local/share/powershell/Modules/AzureADPreview/2.0.2.89/AzureAD.Format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module AzureADPreview.
VERBOSE: Loading module from path '/home/lauic_a/.local/share/powershell/Modules/AzureADPreview/2.0.2.89/Microsoft.Open.Azure.AD.CommonLibrary.dll'.
Import-Module: Assembly with same name is already loaded
PS /home/lauic_a/clouddrive> import-module AzureADpreview
Import-Module: Assembly with same name is already loaded
PS /home/lauic_a/clouddrive> AzureADpreview\connect-azureAD
AzureADpreview\connect-azureAD: The module 'AzureADpreview' could not be loaded. For more information, run 'Import-Module AzureADpreview'.
PS /home/lauic_a/clouddrive> connect-azureAD

**Also got no result by listing out the CMDlet:**

PS /home/lauic_a/clouddrive> man Get-AzureADDirectory*
No manual entry for Get-AzureADDirectory*

**When I tried to import, it said the AzueADPreview has already been loaded:**

PS /home/lauic_a/clouddrive> import-module AzureADpreview -verbose
VERBOSE: Loading module from path '/home/lauic_a/.local/share/powershell/Modules/AzureADPreview/2.0.2.89/AzureADPreview.psd1'.
VERBOSE: Loading 'FormatsToProcess' from path '/home/lauic_a/.local/share/powershell/Modules/AzureADPreview/2.0.2.89/AzureAD.Format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module AzureADPreview.
VERBOSE: Loading module from path '/home/lauic_a/.local/share/powershell/Modules/AzureADPreview/2.0.2.89/Microsoft.Open.Azure.AD.CommonLibrary.dll'.
Import-Module: Assembly with same name is already loaded

**Comment by billmath** [comment]
Hi @Icaruslau 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the module and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

**Comment by benoittgt** [comment]
AzureADpreview can only be used in PowerShell not cloud shell. See https://docs.microsoft.com/en-us/answers/questions/645848/get-azureadpolicy-is-not-working-under-version-ver-1.html
