### ISSUE TITLE
Automatically set Random Password when Password Parameter not specified

### ISSUE THREAD

**Issue by mwe-microsoft** [Azure/azure-docs-powershell-azuread#408]
With MSOnline I use to create Accounts using Azure Automation.

In MSOnline, when I don't specify a password, a random password is set and displayed in the result. 
In my code I pick this result and send the password to the users via an Alternate Email- Address.

Is this possible in New-AzureAdUser?

The switch from MSOnline to Azure AD Module is making easy, straight- through things as complicate as possible. Password- Setting and Licenses Assingment are only two examples!

**Comment by billmath** [comment]
Hi @mwe-microsoft 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
