### ISSUE TITLE
Get-AzureADAuditSignInLogs - How to export more than 1000 lines?

### ISSUE THREAD

**Issue by pdenzil** [Azure/azure-docs-powershell-azuread#409]
Get-AzureADAuditSignInLogs - How to export more than 1000 lines?

**Comment by geoffblack** [comment]
Hard to believe this has been open two weeks without a response. This is a huge gaping hole. It's impossible to collect more than 1,000 sign-in log records in one run of the cmdlet and there's no paging available. `-All $true` simply doesn't work; it doesn't seem to do anything. `-Top [n]` with values greater than 1,000 doesn't have any effect, either. With Azure Graph API, the service provides a `nextLink` property which contains a URL used to page through records if you didn't get all in the first call.

**Comment by V3ertigo83** [comment]
Agree about this being a problem, please address. There's also a typo in your code where -All $TRUE is wrapped in your filter string where it should likely be outside.

**Comment by Jared-Harrington-Gibbs** [comment]
I also ran into this issue.
A fix would be appreciated.

## Test Environment Info

PSVersion

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17763.1007}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Commandlet version

```powershell
Get-Command Get-AzureADAuditSignInLogs |select CommandType,Name,Version,Source|fl

CommandType : Cmdlet
Name        : Get-AzureADAuditSignInLogs
Version     : 2.0.2.102
Source      : AzureADPreview
```

System Version

```powershell
Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion"|select ProductName,ReleaseId,@{name="OS Build";e={$_.CurrentBuildNumber+"."+$_.UBR}}

ProductName           ReleaseId OS Build
-----------           --------- --------
Windows 10 Enterprise 1809      17763.1098
```

## Issue Example

Create time value

```powershell
$aMonthAgo=[DateTime]::Today.AddMonths(-1).AddHours(-4).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssK")

echo $aMonthAgo
2020-05-29T00:00:00Z

```

Create second time value

```powershell
$rightNow=[DateTime]::Now.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssK")

echo $rightNow
2020-06-30T01:09:39Z
```

Run the query

```powershell
$logs = Get-AzureADAuditSignInLogs -Filter "createdDateTime gt $aMonthAgo and createdDateTime lt $rightNow" -all $True

$logs | Measure-Object
Count    : 1000
Average  :
Sum      :
Maximum  :
Minimum  :
Property :
```

Results of report created via gui

```powershell
$test = Import-Csv C:\Users\jared\Downloads\SignIns_2020-05-30_2020-06-29.csv

$test | Measure-Object
Count    : 250000
Average  :
Sum      :
Maximum  :
Minimum  :
Property :
```
**Note:**  
I've also tested using `-all $True` without any filter, using `-Top 1500` with a filter, using `-Top 1500` without a filter, and using the command just on it's own.
Everything returns only 1000 results.

**Comment by billmath** [comment]
Hi @pdenzil 

Thank you for your issue submission.  Sorry for the delay on this.  I have recently take over this portion of the repo, so issues and PRs should be addressed more efficiently going forward.  I have created a work item to track this issue and will be sending it to engineering.  I need to find the correct team that owns this cmdlt and find out if this is possible.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill

**Comment by Jared-Harrington-Gibbs** [comment]
Hi @billmath 

Can we please leave this issue open until it's resolved?
I cannot understand why starting an investigation into this issue would qualify it as closed.

P.S. Thanks for your work. 👍
