### ISSUE TITLE
New-AzureADMSGroup and Set-AzureADMSGroup cmdlets do not work

### ISSUE THREAD

**Issue by arindam-laha** [Azure/azure-docs-powershell-azuread#413]
Unable to create a dynamic group in Azure AD ; it looks like the issue was also reported in 2019, however it still doesn't work, pls see the link below.
(pls note I have installed the AzureADPreview module)

[https://techcommunity.microsoft.com/t5/azure-active-directory/creating-dynamic-groups-azure-ad-in-powershell-membershiprule/m-p/439031/highlight/false#M2772](url)

`New-AzureADMSGroup -Description "Retail Officers" -DisplayName "Office 365 group for all Retail Officers" -MailEnabled $true -SecurityEnabled $false -MailNickname "RetailOfficers" -GroupTypes "DynamicMembership" -MembershipRule "(User.department -eq "Retail")" -MembershipRuleProcessingState "On"
New-AzureADMSGroup : A parameter cannot be found that matches parameter name 'MembershipRule'.
At line:1 char:213
+ ... tailOfficers" -GroupTypes "DynamicMembership" -MembershipRule "(User. ...
+                                                   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzureADMSGroup], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Open.MSGraphV10.PowerShell.NewMSGroup`

**Comment by Protecon** [comment]
Put in single quotes around the membership rule if you have not done so already. I know this post is fairly old, but for others who may need it

-MembershipRule '(User.department -eq "Retail")'

**Comment by billmath** [comment]
Hi @arindam-laha 

Thank you for your issue submission.  I have created a work item to track this issue and investigate it.  I am going to need to test it and if any changes are required we need to get them added to the source code.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
