### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Keldandorin** [Azure/azure-docs-powershell-azuread#414]
Hi alot of the documentation says AzureResources as ProviderId.
For me I only get a error message saying

Get-AzureADMSPrivilegedRoleDefinition : Error occurred while executing GetAzureADMSPrivilegedRoleDefinitions 
Code: UnauthorizedAccessException
Message: The tenant has not onboarded to PIM.

But using aadrole works.. If that is correkt please update documentation

**Comment by billmath** [comment]
Hi @Keldandorin 
Thank you for your issue submission.  I have created a work item to track this issue and investigate it.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
