### ISSUE TITLE
Remove-AzureADApplication doesn't work

### ISSUE THREAD

**Issue by agrabhi** [Azure/azure-docs-powershell-azuread#418]
Remove-AzureADApplication : Error occurred while executing RemoveApplication
Code: Request_BadRequest
Message: Value cannot be null.
Parameter name: requestContext
RequestId: b7155ce4-fc50-4612-ac5c-2fbe21144649
DateTimeStamp: Sat, 30 May 2020 19:00:40 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ Remove-AzureADApplication -objectId "fb135fd4-8ba9-4540-8fe4-5ff175ce ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AzureADApplication], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.RemoveA
   pplication

**Comment by billmath** [comment]
Hi @agrabhi 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

#please-close
