### ISSUE TITLE
Set-AzureADPolicy example 1 error

### ISSUE THREAD

**Issue by Samuliizzio** [Azure/azure-docs-powershell-azuread#422]
In [Set-AzureADPolicy example 1](https://github.com/Azure/azure-docs-powershell-azuread/blob/master/azureadps-2.0-preview/AzureAD/Set-AzureADPolicy.md#example-1-update-a-policy) there is an error. It is showing -ObjectId but the correct one is -Id

It should be like below:

_Example 1: Update a policy
PS C:\>Set-AzureADPolicy -Id <object id of policy> -DisplayName <string>_

**Comment by billmath** [comment]
Hi @Samuliizzio 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  This documentation is auto-generated based on what the developers have coded so we need to get it changed in the source.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
