### ISSUE TITLE
cmdlet does not work when  specifying the values of arguments when asked but works when specifying altogether with the cmdlet

### ISSUE THREAD

**Issue by ankitjoshi8518** [Azure/azure-docs-powershell-azuread#429]
I assigned the object ID's to 2 different variables and then provided it when asked. It didn't work.

when specifying the same values along with the cmdlet, it worked. How the execution is different in both the cases?

PS C:\Users\Ankit> $abhi=Get-AzureADUser -SearchString abhi

PS C:\Users\Ankit> Add-AzureADGroupMember 
cmdlet Add-AzureADGroupMember at command pipeline position 1
Supply values for the following parameters:
ObjectId: $group.objectid
RefObjectId: $abhi.objectid
Add-AzureADGroupMember : Error occurred while executing AddGroupMember 
Code: Request_BadRequest
Message: The request URI is not valid. Since the segment 'Microsoft.DirectoryServices.Group' refers to a collection, this must be the last 
segment in the request URI. All intermediate segments must refer to a single resource.
RequestId: 108c5cb0-0af5-42d5-bd63-8bf3bbe746e4
DateTimeStamp: Fri, 19 Jun 2020 13:57:51 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ Add-AzureADGroupMember
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzureADGroupMember], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.AddGroupMember
 

#THE BELOW CMDLET JUST WORKED FINE

PS C:\Users\Ankit> Add-AzureADGroupMember -ObjectId $group.ObjectId -RefObjectId $abhi.ObjectId

**Comment by billmath** [comment]
Hi @ankitjoshi8518 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

#please-close
