### ISSUE TITLE
Get-AzureADUser undocumented API permissions

### ISSUE THREAD

**Issue by SvenSowa** [Azure/azure-docs-powershell-azuread#436]
I tried to search AAD with Connect-AzureAD and Get-AzureADUser with a service principal/certificate. Kept getting:
Get-AzureADUser : Error occurred while executing GetUsers
Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.
due to undocumented api being used (seems like older Azure AD Graph) and permissions required for the service principal.
The combination that was working:
Azure Active Directory Graph
Application
Directory.Read.All

Two questions arise. Can the documentation be updated? Will this commandlet be migrated to the Microsoft Graph?

**Comment by billmath** [comment]
@SvenSowa 

Thank you for raising this issue.  First, the documentation for the cmdlt is auto-generated so it would need to be added to the source code.  Second, we are in the process of moving alot of cmdlts to Microsoft Graph.  I would assume that this one would eventually be migrated, as Get-AzureADUser is a cmdlt that is used quite often.  I currently do not have a timeline though.  The  migration and deprecation of Azure AD Graph API to Microsoft Graph API needs to occur first and I am not sure when this is going to be completed.

Thanks!

Bill
