### ISSUE TITLE
No cmdlet to enumerate roles set to an application

### ISSUE THREAD

**Issue by hausec** [Azure/azure-docs-powershell-azuread#438]
On the Azure Portal in AAD, there is an option in preview to set roles to a specific application within AAD, however there are no cmdlets within AzureAD PowerShell to enumerate this info.

https://i.imgur.com/oyV7Oky.png

**Comment by billmath** [comment]
Hi @hausec 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
