### ISSUE TITLE
Setting extension attributes on a group?

### ISSUE THREAD

**Issue by sbest-gcm** [Azure/azure-docs-powershell-azuread#439]
I followed the example in https://github.com/Azure/azure-docs-powershell-azuread/blob/live/docs-conceptual/azureadps-2.0/using-extension-attributes-sample.md to create an extension attribute. Instead of attaching it to users, I wanted to attach it to groups.

Creating the attribute worked fine and I'm able to retrieve it:
```
ObjectId                             Name                                                                TargetObjects
--------                             ----                                                                -------------
xxxxxxxx-2669-4d54-af0d-29205a3187c9 extension_XXXXXXXXbb4f4661b23282cb4b68ccf9_SourceExpansionGroupName {Group}
```
But the command from the example to set a value did not work. The ObjectId I used is an AAD group, I've double-checked that it's correct.

```
Set-AzureADUserExtension -ObjectId "xxxxxxxx-b9cc-4fa8-9410-07f0e8c9b53d" -ExtensionName "extension_475e15dbbb4f4661b23282cb4b68ccf9_SourceExpansionGroupName" -ExtensionValue "TestSourceExpansionGroupName"
```

Got this error:
```
Set-AzureADUserExtension : Error occurred while executing SetUser
Code: Request_ResourceNotFound
Message: Resource 'xxxxxxxx-b9cc-4fa8-9410-07f0e8c9b53d' does not exist or one of its queried reference-property objects are not present.
RequestId: fcd63dc4-93f3-4622-81f7-3483f568b0b8
DateTimeStamp: Tue, 14 Jul 2020 15:14:22 GMT
HttpStatusCode: NotFound
HttpStatusDescription: Not Found
HttpResponseStatus: Completed
At line:3 char:1
+ Set-AzureADUserExtension -ObjectId "xxxxxxxx-b9cc-4fa8-9410-07f0e8c9b ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzureADUserExtension], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD.Graph.PowerShell.Custom.SetAzureADUserExtension
```

I couldn't find a corresponding cmdlet for setting a group extension attribute. How can I do that?

Thanks

**Comment by billmath** [comment]
Hi @sbest-gcm 

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

#please-close
