### ISSUE TITLE
Server error on download page for Azure Active Directory Connection

### ISSUE THREAD

**Issue by Noer024** [Azure/azure-docs-powershell-azuread#45]
Appears to be a server error when attempting to retrieve the download.

**Comment by Noer024** [comment]
Correct page appears to be https://www.microsoft.com/en-us/download/details.aspx?id=47594

**Comment by TaraMeyer** [comment]
@Noer024 - thank you for reporting and providing the correct link,  I have updated and the change will be live within the hour.
