### ISSUE TITLE
Version release history page is not up to date

### ISSUE THREAD

**Issue by cpunella** [Azure/azure-docs-powershell-azuread#453]
Hi team,

the "version release history" [()](https://docs.microsoft.com/en-us/powershell/azure/active-directory/ad-pshell-v2-version-history?view=azureadps-2.0) page is showing as latest version the "2.0.2.85 - Preview" instead in production there is the 2.0.2.106 GA (https://www.powershellgallery.com/packages/AzureAD/2.0.2.106).

Can you please update it with release notes?

Thanks

**Comment by billmath** [comment]
Hi @cpunella 

Thank you for your issue submission.  I have recently taken over the documentation for this and noticed that this was an issue. 
 I need to get with engineering and see if they can pull together a list of the updates that were added with each version.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
