### ISSUE TITLE
The sample for Get-AzureADServicePrincipal doesn't work

### ISSUE THREAD

**Issue by bubbletroubles** [Azure/azure-docs-powershell-azuread#462]
On the page
https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0/AzureAD/Get-AzureADServicePrincipal.md

If you follow the instructions for  "Example 2: Retrieve a service principal by ID", the output is 

```
Get-AzureADServicePrincipal: A positional parameter cannot be found that accepts argument '00b2f27e-e3b9-4570-9b92-ddb50529c863'.
```
It looks like it needs a -filter argument in the sample.

**Comment by billmath** [comment]
Hi @bubbletroubles 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
