### ISSUE TITLE
Issues in azure-docs-powershell-azuread are not actioned

### ISSUE THREAD

**Issue by bubbletroubles** [Azure/azure-docs-powershell-azuread#463]
The issues raised in the azure-docs-powershell-azuread area are not actioned or monitored. 

### Steps to reproduce:
1. Create an issue in the azure-docs-powershell-azuread area
1. Wait
1. It never gets triaged or actioned (unless the original issue creator comes back and closes their own issue)

**Comment by ruffy91** [comment]
Can reproduce this on my machine

**Comment by billmath** [comment]
@ruffy91 

Thank you for your issue.  Yes this appears to have been the case.  I currently am taking over from the docs side and working with engineering to rectify this situation.  You should see issues and PRs being worked going forward.  We have a backlog, so it may take a couple weeks.  Thank you again!

Bill
