### ISSUE TITLE
Conditional Access and -Credential problem

### ISSUE THREAD

**Issue by A41-Frech** [Azure/azure-docs-powershell-azuread#465]
Hello guys,
I have problem with all PowerShell Azure / cloud cmdlets.

I have recently activated conditional access for my service accounts. If I connect the service account directly via Connect-AzureAD it works like a charm.

It looks like the -Credential parameter could not sent the valid compliant status / Azure AD hybrid joined status of a device.

`$User = "POWERSHELLCLOUDUSER@MYTENANT.com"
$string = ConvertTo-SecureString "MYPASSWORD" -AsPlainText -Force
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $string
Connect-AzureAD -Credential $Credential`

> AADSTS53001: Device is not in required device state: domain_joined. Conditional Access policy requires a domain joined device, and 
the device is not domain joined.

Another error from MicrosoftTeams cmdlet

> Connect-MicrosoftTeams : One or more errors occurred.: AADSTS53001: Device is not in required device state: domain_joined. Conditional Access policy requires a domain joined device, 
and the device is not domain joined.
Trace ID: 0ea6e100-ae37-4c6d-9cce-c8c343c73b00
Correlation ID: ff183e63-8085-4012-9f55-cad916dd0ad9
Timestamp: 2020-08-03 14:51:07Z
At line:1 char:1
+ Connect-MicrosoftTeams -Credential $Credential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-MicrosoftTeams], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Open.Teams.CommonLibrary.AadAuthenticationFailedException,Microsoft.Open.Teams.CommonLibrary.ConnectMicrosoftTeams

How can I workaround this problem?

Best regards
Robin

**Comment by billmath** [comment]
Hi @A141-Frech

Thank you for your issue submission.  Unfortunately, this appears to be a problem with the cmdlt and a support issue.  Issues in this repo are for documentation issues.  You can try one of the following links for additional help.

Microsoft Support:  https://support.microsoft.com/ 
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

#please-close
