### ISSUE TITLE
Get-AzureADUser parameter name is misleading

### ISSUE THREAD

**Issue by vainolo** [Azure/azure-docs-powershell-azuread#47]
The command `Get-AzureADUser -ObjectId` searches by UserPrincipalName and by ObjectId. IMHO this is confusing.

**Comment by TaraMeyer** [comment]
@vainolo - I'm checking with the product team to see who will own this issue.  Stay tuned.

**Comment by RobdeJong** [comment]
Hi - we're currently investigating how to optimize search capabilities in Azure AD PowerShell V2 and this issue is part of that investigation.

Thanks for your feedback,

Rob

**Comment by TaraMeyer** [comment]
@RobdeJong - any update on this?

**Comment by RobdeJong** [comment]
No update – we will probably not fix it, does not seem like a big problem.

Thanks,

Rob

**Comment by TaraMeyer** [comment]
@RobdeJong  thank you for the update.  Is there anything we add to the docs to make this clearer for the users? Like a note about the parameter or something?

**Comment by TaraMeyer** [comment]
Closing this issue as it has been labeled as won't be fixed
