### ISSUE TITLE
New-AzureADPolicy documentation syntax issue

### ISSUE THREAD

**Issue by bubbletroubles** [Azure/azure-docs-powershell-azuread#490]
On the page at https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0-preview/AzureAD/New-AzureADPolicy.md

The example has the parameter -IsTenantDefault, but the section below which details each parameter has the switch -IsOrganizationDefault

Which one is used?

**Comment by billmath** [comment]
Hi @bubbletroubles 

Thank you for your issue submission.  I have created a work item to track this issue and will be sending it to engineering.  The documentation for the syntax is auto-generated and the fix needs to be in the source code.  At this point, I am going to go ahead and close this issue.  I will post an update as soon as I have any additional information.

Thank you!

Bill
