### ISSUE TITLE
Get-AzureADMSConditionalAccessPolicy only return 5 Conditionnal Access Policy

### ISSUE THREAD

**Issue by SimonT-STHS** [Azure/azure-docs-powershell-azuread#494]
Hi.

I'm very happy about the new Get-AzureADMSConditionalAccessPolicy policy but I have an issue with where it only return 5 policies in the PowerShell. We are 3 in our company who made the test and we always have a maximum of 5 policies return by the Command. Why? Is this a limitation of the graph API?

**Comment by billmath** [comment]
Hi @SimonT-STHS 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
