### ISSUE TITLE
get-azureadauditsigninlogs do not return non-interactive sign in logs

### ISSUE THREAD

**Issue by limjianan** [Azure/azure-docs-powershell-azuread#501]
when I am doing an audit using get-azureadauditsigninlogs -filter "UserPrincipalname eq 'Sync_SERVERNAME_xxxxx@xxxx.onmicrosoft.com'"

I found that it does not return non-interactive sign in logs

In Azure AD, there is "User sign-ins (non-interactive)" which has that result, did I miss anything or there is a feature missing?

**Comment by MichaelLaMontagne** [comment]
Same issue.

**Comment by billmath** [comment]
Hi @limjianan 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
