### ISSUE TITLE
Error Adding a Service Principal for a Multitenant App - New-AzureADServicePrincipal: Could not load file or assembly 'RestSharp, Version=106.3.1.0,

### ISSUE THREAD

**Issue by iamnicoj** [Azure/azure-docs-powershell-azuread#503]
When trying to execute a PowerShell command to create a new Service principal for a Multitenant App from Tenant A to Tenant B, where the Tenant B Admin is trying to give consent and register the app from Tenant A using this command:

    New-AzureADServicePrincipal -AppId "TENANT A APP ID GUID"

I am getting this error:

> New-AzureADServicePrincipal: Could not load file or assembly 'RestSharp, Version=106.3.1.0, Culture=neutral, PublicKeyToken=598062e77f915f75'. Could not find or load a specific file. (0x80131621)

The PS command is being executed directly in the Azure Portal PowerShell CLI window, on the Tenant B subscription

**Comment by billmath** [comment]
Hi @iamnicoj 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
