### ISSUE TITLE
Including specific IncludeApplications in Conditions results in Internal Server Error with New-AzureADMSConditionalAccessPolicy and Set-AzureADMSConditionalAccessPolicy

### ISSUE THREAD

**Issue by christiandekker** [Azure/azure-docs-powershell-azuread#504]
Including specific IncludeApplications in Conditions results in Internal Server Error with New-AzureADMSConditionalAccessPolicy and Set-AzureADMSConditionalAccessPolicy. 

For example, when I try the example from https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsconditionalaccesspolicy?view=azureadps-2.0#example-1--creates-a-new-conditional-access-policy-in-azure-ad-that-require-mfa-to-access-exchange-online-

```PowerShell
$conditions = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessConditionSet
$conditions.Applications = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessApplicationCondition
$conditions.Applications.IncludeApplications = "00000002-0000-0ff1-ce00-000000000000"
$conditions.Users = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessUserCondition
$conditions.Users.IncludeUsers = "all"
$controls = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessGrantControls
$controls._Operator = "OR"
$controls.BuiltInControls = "mfa"
New-AzureADMSConditionalAccessPolicy -DisplayName "MFA policy" -State "Enabled" -Conditions $conditions -GrantControls $controls
```

This results in:
```PowerShell
New-AzureADMSConditionalAccessPolicy : Error occurred while executing NewAzureADMSConditionalAccessPolicy 
Code: Internal Server Error
Message: There was an internal server error while processing the request. Error ID: 7afc07c5-b5c2-4df7-af63-f2851d18f650
InnerError:
  RequestId: 2b549fb9-1727-4072-b2da-c6eff5e31d22
  DateTimeStamp: Thu, 15 Oct 2020 14:00:48 GMT
HttpStatusCode: InternalServerError
HttpStatusDescription: Internal Server Error
HttpResponseStatus: Completed
At line:9 char:1
+ New-AzureADMSConditionalAccessPolicy -DisplayName "MFA policy" -State ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureADMSConditionalAccessPolicy], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphV10.Client.ApiException,Microsoft.Open.MSGraphV10.PowerShell.NewAzureADMSConditionalAccessPolicy
```

The only way to make the above sample work, is if I set the IncludeApplications property to 'Office365' or 'All'
```PowerShell
$conditions.Applications.IncludeApplications = 'Office365'
$conditions.Applications.IncludeApplications = 'All'
```
It just seems the GUID-ids for the IncludeApplications are not accepted by the Graph API.
Using Fiddler I can't see anything wrong with the JSON in the request that is posted to the /identity/conditionalaccess/policies endpoint:
```json
{
  "displayName": "MFA policy",
  "state": "Disabled",
  "conditions": {
    "applications": {
      "includeApplications": [
        "00000002-0000-0ff1-ce00-000000000000"
      ]
    },
    "users": {
      "includeUsers": [
        "all"
      ]
    }
  },
  "grantControls": {
    "operator": "OR",
    "builtInControls": [
      "mfa"
    ]
  }
}
```

I've reproduced this error in the latest versions of both the AzureAD (2.0.2.118)  and AzureADPreview (2.0.2.119) modules.

**Comment by billmath** [comment]
Hi @christiandekker 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

**Comment by Fraglessxd** [comment]
Hi, did you ever get this resolved?
Experiencing the same issue right now.
