### ISSUE TITLE
GetAzureADMSGroup does not return MembershipRules in a dynamic group

### ISSUE THREAD

**Issue by vjyram** [Azure/azure-docs-powershell-azuread#507]
According to the documentation in the link https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmsgroup?view=azureadps-2.0, We can expect the below details when we use the Get-AzureADMSGroup command.
MembershipRule                :(Membership rule)
MembershipRuleProcessingState : On

But when I used the below command, I got the below mentioned result without any MembershipRule attribute/property. Is the below expected?
**Command**
$GroupData = Get-AzureADMSGroup -Id "(Id of the group from Azure AD)"
Write-Host $GroupData

**Result**
class MsGroup {
  Id: (Id of the group from Azure AD)
  OdataType: 
  Description: 
  OnPremisesSyncEnabled: 
  DisplayName: (Displayname of the group)
  OnPremisesLastSyncDateTime: 
  Mail: 
  MailEnabled: False
  MailNickname: (MailNickName)
  OnPremisesSecurityIdentifier: 
  ProxyAddresses: System.Collections.Generic.List`1[System.String]
  SecurityEnabled: True
  GroupTypes: System.Collections.Generic.List`1[System.String]
  Visibility: 
  CreatedDateTime: 3/12/2019 1:07:51 PM
  RenewedDateTime: 3/12/2019 1:07:51 PM
}

**Comment by billmath** [comment]
MembershipRule is currently only supported in AzureADPreview module not the AzureAD module.  Thank you.
