### ISSUE TITLE
Set-AzureADUserPassword - Automatically generate random password

### ISSUE THREAD

**Issue by para0056** [Azure/azure-docs-powershell-azuread#514]
The following doc outlines how to reset a user's password using the `Set-MsolUserPassword` cmdlet:
[doc](https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoluserpassword?view=azureadps-1.0)

Resetting a user password using this cmdlet is very convenient since it can randomly generate the new password.

With Microsoft encouraging their customers to move to the the newer Azure Active Directory V2 PowerShell module, I looked at the equivalent cmdlet:
`Set-AzureADUserPassword`.
[doc](https://docs.microsoft.com/en-us/powershell/module/azuread/set-azureaduserpassword?view=azureadps-2.0)

However, there does not appear to be an option to have this cmdlet randomly generate the new password.

Is there another cmdlet in the Azure AD V2 PowerShell module that should be used to reset an AzureAD user password, while automatically generating a random password value?

Thanks in advance.

**Comment by billmath** [comment]
@para0056  Unfortunately I don't have a good answer for this.  And with the move toward cmdlets based on MS graph, this could change again.  You may want to try one of the following:

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

Thanks!

Bill
