### ISSUE TITLE
Get-AzureADUser cuts results over 100 hits

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-docs-powershell-azuread#515]
Is this only me, or am I just noticing here that the cmdlet cuts off all hits over 100?

`(Get-AzureADUser).Count`
Result: `100`

Comparing with **Get-AzADUser**

`(Get-AzADUser).Count`
Result: `7890`
```
Get-Command Get-AzureADUser

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-AzureADUser                                    0.0.0.10   AzureAD.Standard.Preview
```

**Comment by Gill-Bates** [comment]
RTFM: `(Get-AzureADUser -all $true).Count` solved the issue!

**Comment by billmath** [comment]
Looks like this is resolved.
