### ISSUE TITLE
Set-AzureADUser: Wrong example and clear values

### ISSUE THREAD

**Issue by jaebischer** [Azure/azure-docs-powershell-azuread#53]
Hi,

The example for Set-AzureADUser in https://docs.microsoft.com/en-us/powershell/azuread/v2/set-azureaduser is not valid:
```
PS C:\> $user = Get-AzureADUser -ObjectId TestUser@example.com 
PS C:\> $user.DisplayName = 'YetAnotherTestUser' 
PS C:\> Set-AzureADUser -ObjectId TestUser@example.com -User $user
```

There is no **User** parameter.

Other question: How can I clear existing values? i.e. I’d would like to remove the mobile number for an existing user. I tried the following commands (without success):
```
Set-AzureADUser -ObjectId "xxx" -Mobile ""
Set-AzureADUser -ObjectId "xxx" -Mobile $null 
```

Thanks for your support,
Jon

**Comment by TaraMeyer** [comment]
@RobdeJong - are you able to assist us with this issue?

**Comment by RobdeJong** [comment]
Yes, fixed this and pushed new .md into repo

Thanks,

Rob

**Comment by Zwos** [comment]
same question for me, see also #63 
apparently the bug is still there...
