### ISSUE TITLE
MailNickname and UserPrincipalName seem required, per GraphAPI. Add Federated Example of user creation

### ISSUE THREAD

**Issue by PsychoData** [Azure/azure-docs-powershell-azuread#533]
Migrated from incorrectly created PR https://github.com/Azure/azure-docs-powershell-azuread/pull/239  since I couldn't find any mention of issue created. 

It seems like MailNickName and UserPrincipalName are required? 
Without the code it's hard to know for sure, but whatever API the Cmdlet is using seems to require the MailNickname and UserPrincipalName parameters, and the examples use them, even though the Docs page don't list them as required, and the `get-help New-AzureADUser -ShowWindow` also shows them as not required.  

I know MailNickName is linked to the SamAccountName on premises in many cases, and `-UserPrincipalName` might be important for the sign in name, wondering if maybe it would create the field from the UPN. It doesn't matter much, just one or two more params to pass, but we should update the docs to show it as required if it's being required by the API, or setup param sets if there is a case where it is not required, or adjust the API (and the param sets) to calculate it from some other field (and update the docs to reflect the formulaic nature if not provided) 

Wish I could be more help other than "This doesn't look right" but I can't access the code :( 
oh,, just as I was writing this up I found the Azure AD Graph API [users documentation](https://msdn.microsoft.com/Library/Azure/Ad/Graph/api/users-operations#CreateUser) that it seems to be using.  so it's showing that the required params are 
accountEnabled, displayname, mailNickname, passwordProfile, userPrincipalName and ImmutableID if UPN is for a federated domain

anywho, example of it being required
```powershell
$PasswordProfile = New-Object -TypeName Microsoft.Open.AzureAD.Model.PasswordProfile
$PasswordProfile.Password = "P@ssw0rd"

New-AzureADUser -AccountEnabled $true -PasswordProfile $PasswordProfile -DisplayName "Joe Bob" 
```
results in
```
New-AzureADUser : Error occurred while executing NewUser
Code: Request_BadRequest
Message: Property mailNickname value is required but is empty or missing.
RequestId: a4a70c1b-c0e3-44d0-8fd3-ac8ac5e388e0
DateTimeStamp: Sun, 04 Nov 2018 04:53:47 GMT
Details: PropertyName  - mailNickname, PropertyErrorCode  - PropertyRequired
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed

At C:\Users\KevinC\Downloads\Untitled-1.ps1:4 char:1
+ New-AzureADUser -AccountEnabled $true -PasswordProfile $PasswordProfi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureADUser], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.NewUser
```

A working version looks like the below 
```powershell
$PasswordProfile = New-Object -TypeName Microsoft.Open.AzureAD.Model.PasswordProfile
$PasswordProfile.Password = "P@ssw0rd"

New-AzureADUser -AccountEnabled $true -PasswordProfile $PasswordProfile -DisplayName "Joe Bob" -MailNickName "joebob" -UserPrincipalName "joebob@absurdcanoe.onmicrosoft.com"
``` 
and works Splendidly, If I add either only mailnickname or userprincipalname then it complains about the absence of the other very similar to the above error.

You can see some of the generated output I saw that seemed to be off here - https://github.com/Azure/azure-docs-powershell-azuread/pull/239/files

**Comment by billmath** [comment]
Hi @PsychoData 

I have opened a work item for this so that engineering can take a look and possibly address this. Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again. We need to get engineering to change this in the code. At this point, I am going to go ahead and close this issue and will post any update I have here. Thanks!

Bill
