### ISSUE TITLE
Command missing: New-AzureAdContact, Set-AzureAdContact

### ISSUE THREAD

**Issue by DEberhardt** [Azure/azure-docs-powershell-azuread#552]
Hello,

the following commands are missing:
* New-AzureAdContact (AzureAd)
* Set-AzureAdAccount (AzureAd)
* New-Contact (ExchangeOnlineManagement)
* Remove-Contact (ExchangeOnlineManagement)

```
PS C:\> Get-command -noun AzureADContact

CommandType     Name                                               Version    Source               
-----------     ----                                               -------    ------               
Cmdlet          Get-AzureADContact                                 2.0.2.129  AzureAdPreview       
Cmdlet          Remove-AzureADContact                              2.0.2.129  AzureAdPreview       


PS C:\> Get-command -noun Contact

CommandType     Name                                               Version    Source               
-----------     ----                                               -------    ------               
Function        Get-Contact                                        1.0        tmp_hcroih1x.2yk     
Function        Set-Contact                                        1.0        tmp_hcroih1x.2yk     


PS C:\> Get-command -noun MailContact

CommandType     Name                                               Version    Source               
-----------     ----                                               -------    ------               
Function        Get-MailContact                                    1.0        tmp_hcroih1x.2yk     
Function        New-MailContact                                    1.0        tmp_hcroih1x.2yk     
Function        Remove-MailContact                                 1.0        tmp_hcroih1x.2yk     
Function        Set-MailContact                                    1.0        tmp_hcroih1x.2yk     

```

If someone could tell me how I can create Contact objects (for use in Teams!) in AzureAd or in a specific Global Address List, I would appreciate it. I need to cover the full lifecycle: New/Get/Set/Remove
I am trying to solve a migration issue moving from Skype to Teams and create Contact Objects for Analog Devices we have in the organisation.

Thanks,
David

**Comment by DEberhardt** [comment]
Cross-promoted in **office-docs-powershell** as well: https://github.com/MicrosoftDocs/office-docs-powershell/issues/7016

**Comment by billmath** [comment]
@DEberhardt 

I have opened a work item for this so that engineering can take a look and possibly address this. Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again. We need to get engineering to change this in the code. At this point, I am going to go ahead and close this issue and will post any update I have here. Thanks!

Bill

**Comment by DEberhardt** [comment]
Thank you, Bill. 
I've also created a UserVoice entry for it - albeit a more generic one pertaining to the PowerShell CmdLets for Teams:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/42449707-powershell-commands-for-contact-objects-common-ar
