### ISSUE TITLE
Its not an issue but need help in sending outlook mail using powershell script

### ISSUE THREAD

**Issue by vishnuprakash9845** [Azure/azure-docs-powershell-azuread#555]
I am an automation engineer

I have have automated few test cases and getting the test results. This test results I wanted to forward to team using outlook using powershell. I tried many ways to do it, but not working. 

I want an powershell script to send outlook mail to people who I configure.

Can anyone please help me out in this.

**Comment by billmath** [comment]
@vishnuprakash9845 

Thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/
