### ISSUE TITLE
Unable to create new app registration with SignInAudience

### ISSUE THREAD

**Issue by midway500** [Azure/azure-docs-powershell-azuread#562]
I am trying to use the **New-AzureADApplication** command to register a new application in my B2C directory and from the documentation ([New-AzureADApplication](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadapplication?view=azureadps-2.0)) it appears that I can pass in a value to the *-SignInAudience* parameter but I've got an error saying that the parameter is read only.   Please help.

> *Connect-AzureAD* -Tenant MyB2CTenant.onmicrosoft.com
**new-azureadapplication -DisplayName testb2c -SignInAudience AzureADandPersonalMicrosoftAccount -IdentifierUris @("api://testb2c")**
>
>new-azureadapplication : Error occurred while executing NewApplication
Code: Request_BadRequest
Message: Property 'signInAudience' is read-only and cannot be set.
RequestId: 06d0b6ba-6cdb-4818-a802-6f3e651c106a
DateTimeStamp: Sun, 17 Jan 2021 00:54:27 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:8
\+  $app = new-azureadapplication -DisplayName testb2c -SignInAudience Az ...
\+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   \+   CategoryInfo          : NotSpecified: (:) [New-AzureADApplication], ApiException
   \+  FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.NewAppl
   ication

My environment:
* The directory is an Azure AD B2C directory
* I am trying to register an application for sign-in using user flow (hence the SignInAudience)

**Comment by billmath** [comment]
@midway500 

I have opened a work item for this so that engineering can take a look and possibly address this. Unfortunately, these examples are coded in the source and generated automatically, so any updates would get overwritten once we update this again. We need to get engineering to change this in the code. At this point, I am going to go ahead and close this issue and will post any update I have here. Thanks!

Bill
