### ISSUE TITLE
$conditions.userRiskLevels

### ISSUE THREAD

**Issue by shaunsat** [Azure/azure-docs-powershell-azuread#567]
This property doesn't seem to work:
$conditions.userRiskLevels = @('low', 'medium', 'high')

**Comment by msewaweru** [comment]
Hello @shaunsat , thanks for highlighting this and apologies for the delayed feedback. Could you please add a link to article you are referring to.

**Comment by shaunsat** [comment]
Hi @msewaweru that would be in the New-AzureADMSConditionalAccessPolicy cmdlet

**Comment by msewaweru** [comment]
> Hi @msewaweru that would be in the New-AzureADMSConditionalAccessPolicy cmdlet

Thanks @shaunsat, I will check this out and if need be forward it to the relevant team for resolution.

**Comment by davidspooner** [comment]
Hi @shaunsat, Can you provide some more details on what is not working for you with the userRiskLevel.  I have been testing this and it appears to function as expected.  Here is an example I used to test. Can you test and provide the output of the error?

$conditions = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessConditionSet
$conditions.Applications = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessApplicationCondition
$conditions.Applications.IncludeApplications = "All"
$conditions.Users = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessUserCondition
$conditions.Users.IncludeUsers = "all"
$conditions.userRiskLevels = @('high', 'medium')
$controls = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessGrantControls
$controls._Operator = "OR"
$controls.BuiltInControls = "mfa"
New-AzureADMSConditionalAccessPolicy -DisplayName "test powershell risk" -State "disabled" -Conditions $conditions -GrantControls $controls

**Comment by shaunsat** [comment]
Hi @davidspooner,

I did post this a year ago so maybe something got updated?

Maybe try this (you will have to add your variables):

$conditions = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessConditionSet
$conditions.Applications = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessApplicationCondition
$conditions.Applications.IncludeApplications = "All"
$conditions.Users = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessUserCondition
$conditions.Users.IncludeUsers = "All"
$conditions.Users.excludeUsers = $EmerAcc
$conditions.userRiskLevels = @('high')
$conditions.Platforms = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessPlatformCondition
$conditions.Platforms.IncludePlatforms = "windows"
$conditions.Locations = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessLocationCondition
$conditions.Locations.IncludeLocations = "AllTrusted"
$conditions.ClientAppTypes = @("browser", "mobileAppsAndDesktopClients")
$controls = New-Object -TypeName Microsoft.Open.MSGraph.Model.ConditionalAccessGrantControls
$controls._Operator = "OR"
$controls.BuiltInControls = "block"

New-AzureADMSConditionalAccessPolicy -DisplayName "DeniedHighRiskUK-User" -State "enabledForReportingButNotEnforced" -Conditions $conditions -GrantControls $controls

**Comment by davidspooner** [comment]
@shaunsat Thank for the example.  I was able to test what you supplied and was not able to generate any errors.  The policy was created successfully, and the risk condition was set as expected.  I agree with you, it is possible that the issue was resolved previously and therefore is no longer an issue.  I will close out this thread but please don't hesitate to reach out to me directly if you find this is still an issue and we can reopen and dig into this further.  Thank you
