### ISSUE TITLE
In use anymore?

### ISSUE THREAD

**Issue by danmyhre** [Azure/azure-docs-powershell-azuread#570]
It is unclear if this is even in use anymore. Appears to be very dated.

https://github.com/Azure/azure-docs-powershell-azuread/blob/master/azureadps-1.0/MSOnline/Get-MsolCompanyAllowedDataLocation.md

Doesn't seem to relate to Multi-Geo

**Comment by msewaweru** [comment]
Hello @danmyhre, thanks for the issues and apologies for the delayed response. Kindly note that most of the efforts are going into documenting the new Microsoft Graph PowerShell SDK and the MSOnline and Azure AD modules will soon be deprecated. We however update this documents when there is a customer issue that needs to be resolved.

Kindly let me know if you have encountered any issues or gap in the documentation when working with this cmdlet. I will proceed to close this issue and you can reopen it with any further feedback. Thanks.
