### ISSUE TITLE
Description missing for new versions of Azure AD module

### ISSUE THREAD

**Issue by Alexey-Zheltov** [Azure/azure-docs-powershell-azuread#576]
Page below have not been updated for last 6-7 months, therefore no information on updates in newer versions of Azure AD module:

https://docs.microsoft.com/en-us/powershell/azure/active-directory/ad-pshell-v2-version-history?view=azureadps-2.0

**Comment by msewaweru** [comment]
Hello @Alexey-Zheltov thanks for highlighting this issue and apologies for the delayed response. We have made updates for the last releases of Azure AD and Azure AD Preview modules save for the Azure AD version 2.0.2.140. We shall endeavor to continually update this page with any new releases.

Also not that we asking our customers to migrate to the new [Microsoft Graph PowerShel](https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0) as most of the efforts are currently on that module.

I will proceed to close this issue. Feel free to reopen it with any follow up comments.
