### ISSUE TITLE
New-AzureADServicePrincipalKeyCredential creates inactive certificate

### ISSUE THREAD

**Issue by amarbut24** [Azure/azure-docs-powershell-azuread#577]
We are writing custom claims using Powershell.
When we do the SAML Signing Certificate gets removed

This is documented here - https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-claims-mapping#custom-signing-key

We have successfully generated a new Key Credential using Azure Key Vault + New-AzureADServicePrincipalKeyCredential.
However the certificate that is generated is "inactive" 

![image](https://user-images.githubusercontent.com/49489138/110431008-1147ca80-8062-11eb-8a03-48ff662a6eda.png)

Hoping there is a programatic way to make this certificate "active" as its the last step in our automation.

**Comment by madansr7** [comment]
@amarbut24  you can set the `preferredTokenSigningKeyThumbprint` property to the thumbprint of the certificate you want Azure AD to use to sign the SAML response.

**Sample request**

```http

PATCH https://graph.microsoft.com/v1.0/servicePrincipals/f47a6776-bca7-4f2e-bc6c-eec59d058e3e

Content-type: servicePrincipals/json
{
    "preferredTokenSigningKeyThumbprint": "AC09FEF18DDE6983EE2A164FBA3C4DD7518BD787"
}

```
