### ISSUE TITLE
Get-AzureADAuditSignInLogs: 'Connect-AzureAD first' even if already connected

### ISSUE THREAD

**Issue by Gill-Bates** [Azure/azure-docs-powershell-azuread#590]
When I try to use `Get-AzureADAuditSignInLogs` under PS `7.13`. I receive following error, even when I previously conncted successfully:

`$PSVersiontable`
```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```
ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Binary     2.0.2.129  azureadpreview
```

![image](https://user-images.githubusercontent.com/25774289/113138251-d4689100-9225-11eb-85f0-09371bca5b83.png)

**Comment by msewaweru** [comment]
Hello @Gill-Bates, please update to the latest Azure AD Preview version and retry this. I'm able to run this cmdlet without being asked to reconnect.

I will proceed to close this issue Feel free to reopen it with ay further feedback.
