### ISSUE TITLE
Get-AzureADAuditSignInLogs with filter "userPrincipalName eq" not working

### ISSUE THREAD

**Issue by reikor0x** [Azure/azure-docs-powershell-azuread#593]
Using the cmdlet Get-AzureADAuditSignInLogs with the filter statement -Filter "userPrincipalName eq 'admin@contoso.com'" do not produce any result.

I had to change the filter in -Filter "startswith(userPrincipalName,'admin@contoso.com')" to get results

**Comment by msewaweru** [comment]
Hello @reikor0x thanks for highlighting this and apologies for the delayed response.

I have created a [PR](https://github.com/Azure/azure-docs-powershell-azuread/pull/754) to remove the example that is not working as I follow up on what changed.

I will proceed to close this issue. Feel free to reopen it with any follow up feedback.
