### ISSUE TITLE
Get-AzureADUser -All seems not to be worked

### ISSUE THREAD

**Issue by takeosaga** [Azure/azure-docs-powershell-azuread#599]
I think that -All option of "Get-AzureADUser" is not worked.
![image](https://user-images.githubusercontent.com/53897973/116052253-66907780-a6b4-11eb-9a99-aa16fa990dcf.png)

**Comment by Gelenkwurm35** [comment]
You have to Type in a Boolean, so please use $true :)

**Comment by msewaweru** [comment]
Please use this command as Get-AzureADUser -All $true.

Proceeding to close this issue #please-close.

Feel free to reopen the issue should you have any followup on this issue.
