### ISSUE TITLE
Get-azureaduser filter 

### ISSUE THREAD

**Issue by Narfmeister** [Azure/azure-docs-powershell-azuread#603]
Using this document for Get-AzureAdUser: https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureaduser?view=azureadps-2.0

The -filter parameter advises to use this reference document: https://www.odata.org/documentation/odata-version-3-0/odata-version-3-0-core-protocol/#queryingcollections

However the parameter does not appear to implement many of the features. 
startswith works, endswith returns UnsupportedQuery. 
As does trim() and potentially others.

Is this expected functionality or in need of revising? Ideally would like to be able to use some of these functions for filtering.

AzureAD module ver: 2.0.2.130

**Comment by msewaweru** [comment]
Hello @Narfmeister, you are right. Not all filter operators are currently supported in  the Azure AD PowerShell module. We are however working to ensure that most of these operators are supported in the Microsoft Graph PowerShell module that will replace the Azure AD PowerShell module. See [Advanced query capabilities in Microsoft Graph](https://docs.microsoft.com/en-us/graph/aad-advanced-queries#error-handling-for-advanced-queries-on-directory-objects).

**Comment by Narfmeister** [comment]
@msewaweru 

In that could could you please update the documentation to reflect the features that it does have. 
Otherwise it's misleading to state that you use x standard when in fact you don't or its only partially implemented.

**Comment by msewaweru** [comment]
@Narfmeister , thanks for your comment. Feature parity between the two modules is still ongoing work.

I will get the current doc updated to represent the supported parameters. Thanks.
