### ISSUE TITLE
Misleading Documentation

### ISSUE THREAD

**Issue by magichappens89** [Azure/azure-docs-powershell-azuread#607]
I found the whole documentation of this module currently confusing as the title and the whole document makes the reader assume that the module is using the Graph API as its "Azure Active Directory PowerShell for Graph". However when you use the newest version you can see that the calls in the background are still partially calling Azure AD Graph which is misleading.

### Reproduce
Only by running `Connect-AzueAD` and decrypting the token from the respective library via  `[Microsoft.Open.Azure.AD.CommonLibrary.AzureSession]::AccessTokens['AccessToken'].AccessToken` you can see that the audience is already the old API for this token.
`"aud": "https://graph.windows.net",`

Furthermore when you execute a cmdlet while running a fiddler log you can see that the final API call for `Get-AzureADUsers` goes to `https://graph.windows.net/<mytenantid>/users/`

However if you call one of the newer endpoints that are not supported by AzureAD Graph its calling GraphAPI as expected. Running `Get-AzureADMSGroup` calls `graph.microsoft.com/beta/groups`. But since the audience in the access token is different there seems to be some kind of transformation going on in the background. There are calls against portal.azure.com with "DelegationToken?feature" I don´t understand.

### Expectation
I expect the access token of `Connect-AzureAd` to have the audience of the Graph API. Furthermore I expect every command to run against this API rather than using legacy endpoints. Otherwise I would expect a clear documentation on this page how the operation works and which commands use which endpoint.

**Comment by msewaweru** [comment]
Hello @magichappens89. Thanks for highlighting this issue.

We will update the overview of this docset to highlight the difference in the two types of cmdlets you mentioned in your example.
The Azure AD cmdlets have been build on Azure AD Graph endpoint (these cmdlets follow the format Verb-AzureAD...). we have another set of cmdlets formatted as Verb-AzureADMS.. which call the Microsoft Graph API and this as in a bid to bring in the Microsoft Graph endpoint here. We are however working on a separate module Microsoft Graph PowerShell SDK that will primarily be based on the Microsoft Graph API.

We will update the documentation to highlight this difference.

I have created a work item to track this issue:
<html>
<body>


ID | Title | Assigned To | State | Area Path | Tags | Comment Count
-- | -- | -- | -- | -- | -- | --
1461603 | Issue #607: Update the overview article with that explains the differences between AzureAD and AzureADMS cmdlets. | Eunice Waweru | New | Technical Content\azure-ad-powershell |   | 0


</body>
</html>

I will proceed to close this issue.
