### ISSUE TITLE
AzureADMSConditionalAccessPolicy outdated API call for conditionalAccessDeviceStates resource type

### ISSUE THREAD

**Issue by josefzilak** [Azure/azure-docs-powershell-azuread#609]
New-AzureADMSConditionalAccessPolicy : Error occurred while executing NewAzureADMSConditionalAccessPolicy 
Code: BadRequest
Message: The server could not process the request because it is malformed or incorrect.
InnerError:
  **Message: 1088: 'includeDeviceStates' and 'excludeDeviceStates' are no longer supported. Please use 'includeDevices' and 'excludeDevices' going forward.** For examples, please see API documentation at https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevicestates?view=graph-rest-beta

**Comment by davidspooner** [comment]
Hi, josefzilak, I have raised this with the PM that owns this, the DeviceStates is a deprecated features and is being replaced by devicefitlers.  We will make sure the necessary behaviours and documentation are updated appropriately.

**Comment by davidspooner** [comment]
Engineering are working on the updates for this which will include updates the API, PowerShell etc. including updated documentation to address this behavior.  This should be released in the coming weeks. Closing this thread but please reach out if you have any questions.
