### ISSUE TITLE
Allow Connect-AzureAD's session to have an unique identifier which can be used to disconnect via Disconnect-AzureAD

### ISSUE THREAD

**Issue by vivere-dally** [Azure/azure-docs-powershell-azuread#612]
In the `Az.Accounts` module, there are two cmdlets: `Connect-AzAccount` and `Disconnect-AzAccount`. I'm using them as follows:
```powershell
$contextName = (New-Guid).Guid
$result = Connect-AzAccount -Subscription $SubscriptionId -Credential $credential -ContextName $contextName -Scope Process
# ...
# code
# ...
Disconnect-AzAccount -ContextName $contextName
```

This allows me to be connected to Azure in multiple contexts with different accounts. I would like to have the same feature with `Connect-AzureAD` and `Disconnect-AzureAD`. I saw that `Disconnect-AzureAD` takes no parameters, so I assumed that it removes all contexts created by `Connect-AzureAD`.

What would be the usage for this feature?
I have a Jenkins Job used for automation, and that job gets triggered a lot of times. If there are two or more jobs running at the same time, a scenario where one build connects and the other disconnects thus causing the build that just connected to fail, can happen.

Is there a way to scope the Context to the current PowerShell session or to have the same workflow as `Az.Accounts`?

**Comment by msewaweru** [comment]
Hello @psignoret, could you please help to answer this query?

**Comment by psignoret** [comment]
@msewaweru I'm not familiar with the details for how Connect-AzureAD or Disconnect-AzureAD work with regards to PowerShell sessions.

**Comment by msewaweru** [comment]
> @msewaweru I'm not familiar with the details for how Connect-AzureAD or Disconnect-AzureAD work with regards to PowerShell sessions.

Thanks @psignoret. I will try get the owner of this cmdlet to address it.

**Comment by msewaweru** [comment]
@DerrickJKimani, could you direct me to the owner of this cmdlet?

**Comment by msewaweru** [comment]
Hello @vivere-dally , apologies for the delay in getting you a response to this issue.

I would recommend that you try [Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0) as Azure AD PowerShell is planned for deprecation and all investments are currently in this new module.

I will proceed to close this issue. Feel free to reopen it with any follow-up feedback.
