### ISSUE TITLE
Get-AzureADApplication Not Returning All Application

### ISSUE THREAD

**Issue by jhugery** [Azure/azure-docs-powershell-azuread#614]
When running Get-AzureADApplication -All:$true  I would expect it to return all Applications listed under enterprise application.  It does not.  Here is a list of application from ERRnterpprise apps.
![image](https://user-images.githubusercontent.com/11261719/119501980-092d2c00-bd2f-11eb-87ec-57e28a3a0f02.png)
Here is the output from Get-AzureADApplication
![image](https://user-images.githubusercontent.com/11261719/119502113-32e65300-bd2f-11eb-9162-8541f9a53b35.png)
Why the discrepancy?

**Comment by heckshmek** [comment]
Run the cmd below to get a list of all integrated apps (enterprise apps):

`Get-AzureADServicePrincipal -All:$true | ? {$_.Tags -eq "WindowsAzureActiveDirectoryIntegratedApp"}Get-AzureADServicePrincipal -All:$true | ? {$_.Tags -eq "WindowsAzureActiveDirectoryIntegratedApp"}`

**Comment by msewaweru** [comment]
Hi @jhugery, `Get-AzureADApplication` returns applications that have been registered in your Azure tenant. To return all Enterprise applications run `Get-AzureADServicePrincipal`.

Proceeding to close this issue. Feel free to reopen it with any follow-up issues.
