### ISSUE TITLE
New-AzureADUserAppRoleAssignment - ErrorAction Preference does not take effect.

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-docs-powershell-azuread#62]
Hi,

**## Add the user to an existing Role.**
New-AzureADUserAppRoleAssignment -ObjectId 2c2528-408-bf437d761882 -PrincipalId 2c2528d-bf437d761882 -ResourceId fdb0db8d-adc8-b01badcbec8d -Id 7e883-419a-b03e-3512c0ec0e8d

**_I could not find a way to check if a user is already assigned to a role_**, i wanted to suppress any error which may come from the above and it does not take effect.

**## Add the user to an existing Role (Suppress if there are errors)**
New-AzureADUserAppRoleAssignment -ObjectId 2c2528-408-bf437d761882 -PrincipalId 2c2528d-bf437d761882 -ResourceId fdb0db8d-adc8-b01badcbec8d -Id 7e883-419a-b03e-3512c0ec0e8d -**_ErrorAction SilentlyContinue_**

__New-AzureADUserAppRoleAssignment : Error occurred while executing NewUserAppRoleAssignment
Code: Request_BadRequest
Message: One or more properties are invalid.
HttpStatusCode: BadRequest
HttpStatusDescription: **Bad Request**
HttpResponseStatus: Completed
At line:1 char:1
+ New-AzureADUserAppRoleAssignment -ObjectId 7d761882  ..._
+_ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureADUserAppRoleAssignment], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.NewUserAppRoleAssignment

**## Please help for a way to find whether a user is already assigned to a role / or to suppress errors from trying to create duplicates**

Also, please let me know the github path where i can log issues on AzureAD module.

Thanks,
Pradebban Raja

**Comment by TaraMeyer** [comment]
@RobdeJong have you seen this issue?

**Comment by TaraMeyer** [comment]
@Pradebban - Rob is researching the issue now.  Thank you for reporting.

**Comment by Pradebban** [comment]
@TaraMeyer and @RobdeJong - Thanks for the quick response.

**Comment by Pradebban** [comment]
Is there a way to find whether a user is already assigned to a role in an application ?

**Comment by jeevansd** [comment]
@Pradebban and @TaraMeyer, Today we identified a bug in our service which was causing the app role assignment issue. We revoked the changes in the production and now it is working. Can you please try again?
You can check the app role assignment from Azure AD app management portal. 
1. Go to https://portal.azure.com
2. Then click on Azure AD  
3. Click on the Enterprise Application or App Registration blade
4. No search for your application and click on it
5. In the application blade look for Users and Groups section and on clicking of that it shows the assigned users

**Comment by Pradebban** [comment]
@jeevansd , I am looking for powershell way of getting the role assignment info for an application and user.

**Comment by TaraMeyer** [comment]
@jeevansd - is there any further updates on this issue?

**Comment by Pradebban** [comment]
@jeevansd @TaraMeyer , this is a blocker in our automation. Any one of the below should be existing.

1. Powershell way of **getting** the role assignment info for an application and user
2. Able to suppress error from New-AzureADUserAppRoleAssignment with silentlycontinue

Thanks!

**Comment by RobdeJong** [comment]
Hi – for 1, can you try this script? It will return all app role assignments for all users and all applications:


# Get all service principals, and for each one, get all the app role assignments,
# resolving the app role ID to it's display name. Output everything to a CSV.
Get-AzureADServicePrincipal | % {

  # Build a hash table of the service principal's app roles. The 0-Guid is
  # used in an app role assignment to indicate that the principal is assigned
  # to the default app role (or rather, no app role).
  $appRoles = @{ "$([Guid]::Empty.ToString())" = "(default)" }
  $_.AppRoles | % { $appRoles[$_.Id] = $_.DisplayName }

  # Get the app role assignments for this app, and add a field for the app role name
  Get-AzureADServiceAppRoleAssignment -ObjectId ($_.ObjectId) | % {
    $_ | Add-Member "AppRoleDisplayName" $appRoles[$_.Id] -Passthru
  }
} | Export-Csv "app_role_assignments.csv" -NoTypeInformation
For 2 – this is not yet implemented. As a work around, can you please user Try-Catch, as in:

Try { New-AzureADUserAppRoleAssignment <your parameters> }
Catch {}

Thanks,

Rob

**Comment by RobdeJong** [comment]
BTW – for 2, you could also use

$ErrorActionPreference = "SilentlyContinue"
 before the new-azureaduserapproleassignment and


$ErrorActionPreference = "Stop"
 after it.

Thanks,

Rob

From: Rob de Jong
Sent: Tuesday, March 21, 2017 5:37 PM
To: 'Azure/azure-docs-powershell-azuread' <reply@reply.github.com>; Azure/azure-docs-powershell-azuread <azure-docs-powershell-azuread@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-docs-powershell-azuread] New-AzureADUserAppRoleAssignment - ErrorAction Preference does not take effect. (#62)

Hi – for 1, can you try this script? It will return all app role assignments for all users and all applications:


# Get all service principals, and for each one, get all the app role assignments,
# resolving the app role ID to it's display name. Output everything to a CSV.
Get-AzureADServicePrincipal | % {

  # Build a hash table of the service principal's app roles. The 0-Guid is
  # used in an app role assignment to indicate that the principal is assigned
  # to the default app role (or rather, no app role).
  $appRoles = @{ "$([Guid]::Empty.ToString())" = "(default)" }
  $_.AppRoles | % { $appRoles[$_.Id] = $_.DisplayName }

  # Get the app role assignments for this app, and add a field for the app role name
  Get-AzureADServiceAppRoleAssignment -ObjectId ($_.ObjectId) | % {
    $_ | Add-Member "AppRoleDisplayName" $appRoles[$_.Id] -Passthru
  }
} | Export-Csv "app_role_assignments.csv" -NoTypeInformation
For 2 – this is not yet implemented. As a work around, can you please user Try-Catch, as in:

Try { New-AzureADUserAppRoleAssignment <your parameters> }
Catch {}

Thanks,

Rob

**Comment by Pradebban** [comment]
@RobdeJong thanks for all the leads and responses.
I was able to figure out a way to check if i am assigned to a particular role in the app.

Get-AzureADServiceAppRoleAssignment -**ObjectId** "888f656ahidden8eab0d374" | ? {$_.**Id** -eq "ab7fa6f0hidden55abef57c0"} | ? {$_.**PrincipalId** -eq "5f2735hidden1afe9a1"}

**where:**
ObjectId = Application ID
Id = Application's Specific Role ID
PrincipalId = User ID

If nothing returns the user is not assigned to the specific role in an application.

Thanks!

**Comment by RobdeJong** [comment]
Thanks for your input and feedback. I also updated the contents of https://docs.microsoft.com/en-us/powershell/azuread/v2/new-azureaduserapproleassignment to clarify the value of the ID parameter and I added an example to create a new user role assignment.

Thanks,

Rob

**Comment by Pradebban** [comment]
@RobdeJong , do we have an update on ErrorAction not taking effect ?

Thanks!

**Comment by TaraMeyer** [comment]
@RobdeJong is this issue resolved or are we still waiting on a fix for the ErrorAction as @rajaprad  asks above?

**Comment by RobdeJong** [comment]
I filed a bug for the ErrorAction not taking effect

**Comment by TaraMeyer** [comment]
@RobdeJong - thank you for the update!

**Comment by jeevansd** [comment]
@RobdeJong Do you have an update on this issue? If this is fixed then we should close this request also.

**Comment by RobdeJong** [comment]
No, it’s not fixed

**Comment by billmath** [comment]
Looks like this has been resolved.
