### ISSUE TITLE
Open-AzureADMSPrivilegedRoleAssignmentRequest - more examples needed?

### ISSUE THREAD

**Issue by DEberhardt** [Azure/azure-docs-powershell-azuread#627]
Hello,

I find the one example does not show the full capability of this command
- Example 1 adds a new eligible role by an Admin
- Example 2 (below) enables an eligible Role by a User
- Example 3 (below) disables an active Role by a User

### Example 2
```powershell
    $Duration = 4 # Number in Hours
    $Date = Get-Date
    $start = $Date.ToUniversalTime()
    $end = $Date.AddHours($Duration).ToUniversalTime()

    $schedule = New-Object Microsoft.Open.MSGraph.Model.AzureADMSPrivilegedSchedule
    $schedule.Type = 'Once'
    $schedule.StartDateTime = $start.ToString('yyyy-MM-ddTHH:mm:ss.fffZ')
    $schedule.endDateTime = $end.ToString('yyyy-MM-ddTHH:mm:ss.fffZ')

Open-AzureADMSPrivilegedRoleAssignmentRequest -ProviderId AzureResources -Schedule $schedule -ResourceId "e5e7d29d-5465-45ac-885f-4716a5ee74b5" -RoleDefinitionId "9f8c1837-f885-4dfd-9a75-990f9222b21d" -SubjectId "a25004a3-eceb-4ad4-b4aa-9485356bc55b" -AssignmentState "Active" -Type "UserAdd"
```

Create a role assignment request activating the Admin Role

### Example 3
```powershell
    $Duration = 0 # Disables the role immediately
    $Date = Get-Date
    $start = $Date.ToUniversalTime()
    $end = $Date.AddHours($Duration).ToUniversalTime()

    $schedule = New-Object Microsoft.Open.MSGraph.Model.AzureADMSPrivilegedSchedule
    $schedule.Type = 'Once'
    $schedule.StartDateTime = $start.ToString('yyyy-MM-ddTHH:mm:ss.fffZ')
    $schedule.endDateTime = $end.ToString('yyyy-MM-ddTHH:mm:ss.fffZ')

Open-AzureADMSPrivilegedRoleAssignmentRequest -ProviderId AzureResources -Schedule $schedule -ResourceId "e5e7d29d-5465-45ac-885f-4716a5ee74b5" -RoleDefinitionId "9f8c1837-f885-4dfd-9a75-990f9222b21d" -SubjectId "a25004a3-eceb-4ad4-b4aa-9485356bc55b" -AssignmentState "Active" -Type "UserRemove"
```

Create a role assignment request disabling the Admin Role

I am sure there are a few things I have not yet grasped when working with this command, but these two use-cases would be good to document.

Before I submit a PR, any other examples that should be covered?

**Comment by msewaweru** [comment]
@rkarim-ms, please review the examples that have been proposed to addition to the cmdlet and advise.

**Comment by msewaweru** [comment]
@DEberhardt - thank you for your contribution. I have created a PR with the suggested examples and will be merged soon.

**Comment by adlpena-ctc** [comment]
Hi there!

Can I use Open-AzureADMSPrivilegedRoleAssignmentRequest to configure the member role for PIM Enabled Groups? If yes, what the proper ProviderId should I be using?

I understand that 
- for Entra ID Roles it is "aadRoles"
- for Azure Resources it is "AzureResources"

How about for PIM Enabled Groups?

Cheers,
Allan

**Comment by DEberhardt** [comment]
Hello,

I never figured out how to do that for groups. This wasn't available in AzureAD, and it isn't very well documented in Microsoft Learn either.
This should help (hopefully): https://stackoverflow.com/questions/71622254/how-to-activate-privileged-access-groups-using-powershell/71755463?noredirect=1#comment126829002_71755463

Good luck!

Cheers,
David
