### ISSUE TITLE
Get-AzureADAuditSignInLogs does not include 'non-interactive' sign ons

### ISSUE THREAD

**Issue by ChrisTav424** [Azure/azure-docs-powershell-azuread#628]
Get-AzureADAuditSignInLogs does not include 'non-interactive' sign ons

This page should be amended 
https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0-preview/AzureAD/Get-AzureADAuditSignInLogs.md 
to reflect that fact it doesn't include non-interactive sign ons or the cmdlet Get-AzureADAuditSignInLogs should be amended to include 'non-interactive' sign ons

**Comment by djcabrera** [comment]
Bump - I just noticed this behavior a moment ago and found your comment.  Thanks for catching.

**Comment by bmilbauer** [comment]
Stop ignoring this pls - this will have real-world consequences for investigation of security incidents and conditional access gaps.

**Comment by ChrisTav424** [comment]
This is an embarrassment, 12 months to update some documentation or fix the problem.

Unfortunately seems to be classic Microsoft I've actually come to expect now...

**Comment by VirgoCluster** [comment]
Bump #3 - I need this to find unused serviceaccounts...

**Comment by ztrhgf** [comment]
I've created PowerShell function `Get-AzureAuditAggregatedSignInEvent`  hosted at https://gist.github.com/ztrhgf/96445c23b25c1682238b8b52e9218430

PS: needs module Microsoft.Graph.Intune to work
