### ISSUE TITLE
Set-AzureADUser help Example 1 contains invalid parameter

### ISSUE THREAD

**Issue by Zwos** [Azure/azure-docs-powershell-azuread#63]
Set-AzureADUser -ObjectId TestUser@example.com -User $user
=> -User is not a valid parameter

Should this not be something like this:
Set-AzureADUser -ObjectId $user.ObjectId -UserPrincipalName $user.UserPrincipalName

**Comment by TaraMeyer** [comment]
@Zwos - what is the source of this error, meaning can you please provide us a screenshot?

**Comment by Zwos** [comment]
PS C:\WINDOWS\system32> get-help Set-AzureADUser -Examples

NAME
    Set-AzureADUser

SYNOPSIS
    Updates a user.


    Example 1: Update a user

    PS C:\> $user = Get-AzureADUser -ObjectId TestUser@example.com
    PS C:\> $user.DisplayName = 'YetAnotherTestUser'
    PS C:\> Set-AzureADUser -ObjectId TestUser@example.com -User $user

    This command updates the specified user's property.

PS C:\WINDOWS\system32> Get-Module AzureAD

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     2.0.0.71   AzureAD                             {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDevic...


The bug in the documentation is still present in version 2.0.0.71
See also bug #53, which was marked as closed

Tom

**Comment by RobdeJong** [comment]
Thanks – I’ll push an update to the bits, not sure why these are out of sync.

Thanks,

Rob

**Comment by RobdeJong** [comment]
I verified the bits and noticed this change has been applied there last month as well. @Zwos - can you please verify the version of the module you are using and update to the latest version?

/Rob

 Example 1: Update a user

 PS C:\> $user = Get-AzureADUser -ObjectId TestUser@example.com
 PS C:\> $user.DisplayName = 'YetAnotherTestUser'
 PS C:\> Set-AzureADUser -ObjectId TestUser@example.com -User $user

 This command updates the specified user's property.

**Comment by TaraMeyer** [comment]
@Zwos can you please confirm that this issue is resolved?

**Comment by Zwos** [comment]
confirmed solved in version 2.0.0.115

Tom

**Comment by TaraMeyer** [comment]
@Zwos  - thank you very much!
