### ISSUE TITLE
Get-AzureADUser : Unable to filter certain UserPrincipalName

### ISSUE THREAD

**Issue by Pradebban** [Azure/azure-docs-powershell-azuread#64]
### Cmdlet(s)

Get-AzureADUser

### PowerShell Version

4.0

### Module Version

6.3.9600.17400

### OS Version

6.3.9600.17400

### Description

Get-AzureADUser with filter does not work for certain ids.
**The same works for few ids randomly.** 
**I think it works only for the first few users in AzureAD**

PS C:\Windows\system32> Get-AzureADUser | ? {$.UserPrincipalName -eq "Pradebban@hidden.onmicrosoft.com"}
PS C:\Windows\system32> Get-AzureADUser | ? {$.UserPrincipalName -eq "Pradebban@hidden.onmicrosoft.com"} -Verbose
PS C:\Windows\system32> Get-AzureADUser | ? {$_.UserPrincipalName -eq "Pradebban@hidden.onmicrosoft.com"} -debug (No result)
PS C:\Windows\system32> Get-AzureADUser -ObjectId "pradebban@hidden.onmicrosoft.com"

DeletionTimeStamp :
ObjectId : f405c38c-9980--daa1e112b7ad
ObjectType : User
AccountEnabled : True
AssignedLicenses : {}
AssignedPlans : {}
City :
Country :
Department :
DirSyncEnabled :
DisplayName : Pradebban Raja
FacsimilieTelephoneNumber :
GivenName : Pradebban
ImmutableId :
JobTitle :
LastDirSyncTime :
Mail :
MailNickName : Pradebban
Mobile :
OnPremisesSecurityIdentifier :
OtherMails : {v-pradr@microsoft.com}
PasswordPolicies : None
PasswordProfile :
PhysicalDeliveryOfficeName :
PostalCode :
PreferredLanguage :
ProvisionedPlans : {}
ProvisioningErrors : {}
ProxyAddresses : {}
SipProxyAddress :
State :
StreetAddress :
Surname : Raja
TelephoneNumber :
ThumbnailPhoto :
UsageLocation :
UserPrincipalName : Pradebban@hidden.onmicrosoft.com
UserType : Member

### Debug Output

None ( Nothing comes up when using -Debug flag )

### Script/Steps for Reproduction

Connect to Azure AD
Run - Get-AzureADUser | ? {$_.UserPrincipalName -eq "Pradebban@hidden.onmicrosoft.com"}

Thanks,
Pradebban Raja

**Comment by RobdeJong** [comment]
My assumption (without testing this) is that the cmdlet only returns 100 objects if neither -Top or -All parameters are used. Can you try Get-AzureADUser -All $True | ? {$_.UserPrincipalName -eq "Pradebban@hidden.onmicrosoft.com"} to see if that resolves the issue?

BTW - I noticed that an earlier update to explain the default value for -Top did not make it to the content, I will push that change again.

**Comment by Pradebban** [comment]
@RobdeJong, Yes i was able to get the results with -Top 200.
Thanks for the help.
