### ISSUE TITLE
Documentation error: Parameter descriptions missing for New-AzureADApplicationPasswordCredential

### ISSUE THREAD

**Issue by jeffreymcclain** [Azure/azure-docs-powershell-azuread#646]
Microsoft Documentation: https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadapplicationpasswordcredential?view=azureadps-2.0

Corresponding GitHub file: https://github.com/Azure/azure-docs-powershell-azuread/blob/master/azureadps-2.0/AzureAD/New-AzureADApplicationPasswordCredential.md

Note that the description for some of the parameters is "@{Text=}". 
This should be replaced with the actual parameter descriptions.

**Comment by msewaweru** [comment]
Hello @jeffreymcclain. Thanks for raising this issue. I have created a work item that will be actioned to resolve this error.
<html>
<body>


ID | Title | Assigned To | State | Area Path | Tags | Comment Count
-- | -- | -- | -- | -- | -- | --
1461597 | Issue: Parameter descriptions missing for New-AzureADApplicationPasswordCredential | Eunice Waweru | New | Technical Content\azure-ad-powershell |   | 0


</body>
</html>

I will proceed to close this issue and will update it once the work is completed.
