### ISSUE TITLE
Multiple PowerShell cmdlets

### ISSUE THREAD

**Issue by stuartmaxwell** [Azure/azure-docs-powershell-azuread#649]
On most of the documentation pages, there are a number of different cmdlets provided for each command, without explaining which cmdlets should be used in which environments.

For example: https://docs.microsoft.com/en-us/powershell/module/azuread/connect-azuread?view=azureadps-2.0

This lists 3 different cmdlets for `Connect-AzureAD` each of which have slightly different parameters, but there is no explanation why there are three different commands.

If we look at the source code here: https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0/AzureAD/Connect-AzureAD.md
We can see that the first one is for "UserCredential (Default)", the second is for "ServicePrincipalCertificate", and the third is for "AccessToken", but none of this information exists in the rendered documentation page. Also, we don't know why there is three different cmdlets nor how you would end up with a specific version of the cmdlet installed in your environment.

Another example: https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureaddirectoryrole?view=azureadps-2.0

This lists 2 different cmdlets for `Get-AzureADDirectoryRole`, and one has a `-Filter` parameter and the other has an `-ObjectId` parameter, but there is no information given as to why there are two different cmdlets with different parameters.

Again, we need to look a the source code here: https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0/AzureAD/Get-AzureADDirectoryRole.md
And we can see that the first cmdlet is titled `GetQuery (Default)` and the second one is titled `GetById`, but again - no explanation is given in the docs about why there are two cmdlets with different commands. 

This is especially confusing because the version of `Get-AzureADDirectoryRole` installed in the Cloud Shell (part of AzureAD.Standard.Preview`) does not have the filter option. Perhaps there is a logical explanation for this but it does not exist in the docs.

**Comment by msewaweru** [comment]
Hello @stuartmaxwell, thanks for your query and apologies for the delayed response.

To explain your query, these are not multiple cmdlets but multiple parameter variants and how to use them. Picking the example of the `Get-AzureADDirectoryRole` cmdlet the 2 parameter variants can be explained as below and also based on the examples provided which have made use of both the variants:
1. The first variant means you can run the cmdlet without providing any parameter and in that case it will return all directory roles. All parameters contained within `[]` are optional for each of the variants.
2. The second variant, gives you an option of running the cmdlet by providing the `-ObjectId` in which case it will only return the directory roles for the specified object.
Note that these variants are not to be run in different environments. They only provide options that can be used with the cmdlet depending on the expected result and the info you have at the time of running it.

Please let me know if this answers your question. Feel free to reopen this issue if you have follow up questions.
