### ISSUE TITLE
Set-AzureADMSConditionalAccessPolicy - Sudden error: "Use the Canary endpoint to create or update this policy."

### ISSUE THREAD

**Issue by DFryatt** [Azure/azure-docs-powershell-azuread#659]
Using this for a staged rollout of MFA.
Each morning a scheduled task runs and updates a CA policy by removing a particular mail-enabled security group from the `$Policy.Conditions.Users.ExcludeGroups`
This last worked properly on July 16, 2021 but it may or may not have worked up until today (July 20, 2021). 

I have done the usual troubleshooting (updated the AzureAD module, tried on another machine, etc.) but no joy.

```
$policy = Get-AzureADMSConditionalAccessPolicy -PolicyId $policyID
$group = Get-DistributionGroup -Identity $rec.Identity

$policy.Conditions.Users.ExcludeGroups.Remove($group.ExternalDirectoryObjectId)

try{
    Set-AzureADMSConditionalAccessPolicy -PolicyId $policy.ID -Conditions $policy.Conditions
    }
catch{
    $_
    }
```
Error message:
```
Set-AzureADMSConditionalAccessPolicy : Error occurred while executing SetAzureADMSConditionalAccessPolicy 
Code: BadRequest
Message: 1038: The policy you are trying to create or update contains preview features. Use the Canary endpoint to create or update this policy.
InnerError:
  RequestId: c73d7b6b-ce47-4865-87ff-28c4f54c3eb0
  DateTimeStamp: Tue, 20 Jul 2021 14:10:57 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
```

Any insight on the matter would be appreciated.

**Comment by davidspooner** [comment]
HI DFryatt, Is this still an issue for you?  If so, would you mind sharing the policy that you are running the set against.  Preview features are only available on the Beta endpoint.  The error here is suggesting the Canary needs to be used hence i am curious what conditions in the policy are configured?

**Comment by davidspooner** [comment]
Hi @DFryatt , I have not been reproduce the above error.  If this is still an issue for you, please provide additional details. I will temporarily archive this request, but please feel free to contact me and we can reopen if it is still an issue. Thanks
