### ISSUE TITLE
New-AzureADUserAppRoleAssignment Parameters confusing/misleading.

### ISSUE THREAD

**Issue by rajaprad** [Azure/azure-docs-powershell-azuread#66]
Below are the parameters.

**New-AzureADUserAppRoleAssignment -ObjectId -Id -PrincipalId -ResourceId**

Where:
1, ObjectId - Azure AD UserID
2. PrinicipalId - Azure AD UserID (Duplicate)
3. Id - Role ID in the Application.
4. ResourceId - Application's Objectid

This should be something like below,

**New-AzureADUserAppRoleAssignment -AppID -AppRoleId -UserId** 

Where:
1. **AppID** - Application's Objectid
2. **AppRoleId** - Role ID in the Application.
3. **UserId** -Azure AD UserID

Please make them generic and easy to understand, as there is no example for these in msdn.
[https://docs.microsoft.com/en-us/powershell/azuread/v2/new-azureaduserapproleassignment](url)

Further the explanation is **vague** in MSDN

Example: 

**-Id
Specifies an ID.**

**Comment by TaraMeyer** [comment]
@RobdeJong - do you want update the docs as suggested above?

**Comment by RobdeJong** [comment]
Hi – I pushed an update to add additional examples and clarification for the use of parameters

Thanks,

Rob

**Comment by TaraMeyer** [comment]
@RobdeJong -merging now.

**Comment by RobdeJong** [comment]
Thanks!

Thanks,

Rob

**Comment by Pradebban** [comment]
@TaraMeyer , @RobdeJong Is the below considered or a better representation/naming for the parameter to make like easy and standard - rather than making additional documentation on some bad/non-standard naming for the parameters ?

New-AzureADUserAppRoleAssignment -AppID -AppRoleId -UserId

Where:

AppID - Application's Objectid
AppRoleId - Role ID in the Application.
UserId -Azure AD UserID

**Comment by RobdeJong** [comment]
Are you proposing to change the parameter names in this cmdlet?

Thanks,

Rob

**Comment by Pradebban** [comment]
Yes, that is correct.

thanks!

**Comment by RobdeJong** [comment]
Ah, OK. We decided to keep the parameter names as close as possible to the names of properties in the underlying API and we’re using a pretty descriptive naming convention for these names, so we cannot change the parameter names unless we would also change these in Graph API. Given that we have not heard any customer evidence that these names are actually confusing or misleading we are currently not planning to change the names.

Thanks,

Rob
