### ISSUE TITLE
add examples of hashtable as value of Azure Powershell TemplateFileObject parameter

### ISSUE THREAD

**Issue by HughDevlin** [Azure/azure-docs-powershell-azuread#672]
For Azure Powershell cmdlets that support the TemplateFileObject parameter, please add an example showing the construction of a params hashtable, in-script, as the value of the parameter

(non-exhaustive) examples of Azure Powershell cmdlets that support the TemplateFileObject parameter

    New-AzResourceGroupDeployment
    Test-AzResourceGroupDeployment

Inspiration:

https://gordon.byers.me/azure/templateparameterobject-parameter-azurermresourcegroupdeployment/

See also these issues which include the technique:

Azure/azure-powershell#7980
#7980

Azure/azure-powershell#1528
#1528

issue moved here from

https://github.com/MicrosoftDocs/feedback/issues/3073

**Comment by msewaweru** [comment]
Hello @HughDevlin, you opened this issue in the wrong repo. Please open it from the [Azure PowerShell repo](https://github.com/Azure/azure-powershell/issues).
