### ISSUE TITLE
New-AzResourceGroupDeployment Example 3 fails

### ISSUE THREAD

**Issue by HughDevlin** [Azure/azure-docs-powershell-azuread#673]
Describe the bug
Azure Powershell
New-AzResourceGroupDeployment
https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azresourcegroupdeployment?view=azps-4.6.1#examples

Example 3 fails`

To Reproduce

    Go to Example 3
    Click on Try it
    try it
    See error:

New-AzResourceGroupDeployment: Missing an argument for parameter 'TemplateParameterObject'. Specify a parameter of type 'System.Collections.Hashtable' and try again.

moved here from

https://github.com/MicrosoftDocs/feedback/issues/3066

**Comment by msewaweru** [comment]
Hello @HughDevlin, you opened this issue in the wrong repo. Please open it from the [Azure PowerShell repo](https://github.com/Azure/azure-powershell/issues).
