### ISSUE TITLE
set-AzureADMSAuthorizationPolicy DefaultUserRolePermissions class issue

### ISSUE THREAD

**Issue by sanderdewit** [Azure/azure-docs-powershell-azuread#683]
I'm running into the following issue when trying to define the defaultuserrolepermisssions

`
$defaultUserRolePermissions = New-Object Microsoft.Open.MSGraph.Model.DefaultUserRolePermissions
$defaultUserRolePermissions.PermissionGrantPoliciesAssigned = $null (Disable user permission to consent)
$defaultUserRolePermissions.defaultUserRolePermissions.AllowedToCreateApps = $false
$defaultUserRolePermissions.defaultUserRolePermissions.AllowedToCreateSecurityGroups= $false
$defaultUserRolePermissions.defaultUserRolePermissions.AllowedToReadOtherUsers = $false
Set-AzureADMSAuthorizationPolicy -Id authorizationPolicy -DefaultUserRolePermissions $defaultUserRolePermissions
`

The following errors occurs;
Set-AzureADMSAuthorizationPolicy : Cannot bind parameter 'DefaultUserRolePermissions'. Cannot convert the "class 
DefaultUserRolePermissions {
  AllowedToCreateApps: False
  AllowedToCreateSecurityGroups: False
  AllowedToReadOtherUsers: False
  PermissionGrantPoliciesAssigned: 
}
" value of type "Microsoft.Open.MSGraph.Model.DefaultUserRolePermissions" to type 
"Microsoft.Open.MSGraph.Model.DefaultUserRolePermissions".

However when I change it based on what is current set. I get only 3 properties returned.
When changes this attribute and modifying it, it works well.
$policy = Get-AzureADMSAuthorizationPolicy

$policy.DefaultUserRolePermissions
AllowedToCreateApps AllowedToCreateSecurityGroups AllowedToReadOtherUsers
------------------- ----------------------------- -----------------------
              False                         False                   False

**Comment by commakoerschgen** [comment]
As of version 2.0.2.140 of AzureAD (*not*$ preview), I get a fourth property `PermissionGrantPoliciesAssigned` for `$policy.DefaultUserRolePermissions`.

Apart from that, have you tried using an empty array instead of null in line 2 of your command?

**Comment by shailja11** [comment]
Can i stop getting notification of all these changes.

**Comment by sanderdewit** [comment]
issue is indeed resolved in newer module version.
