### ISSUE TITLE
Missing samples and information on parameters for Set-MsolDomainFederationSettings

### ISSUE THREAD

**Issue by astaykov** [Azure/azure-docs-powershell-azuread#688]
The documentation about [Set-MsolDomainFederationSettings](https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-1.0/MSOnline/Set-MsolDomainFederationSettings.md) does not provide information on which parameters are mandatory, which are optional. Neither does it provide information on expected or valid values for `PreferredAuthenticationProtocol` (beside that it should of type `AuthenticationProtocol` that is not referenced for more details).

Last, but not least, there is no single sample for how to use this command.

**Comment by kjyam98** [comment]
Hi @msewaweru - I'm not familiar with this command... @Justinha can you assist?

**Comment by fabnord** [comment]
@msewaweru @Justinha any update on this one?

**Comment by msewaweru** [comment]
@astaykov apologies for the delay in responding to this. To answer the first part, the only mandatory parameter is the DomainName while the rest are optional as per the documentation. Kindly allow me to follow up with the team to answer the rest of the queries.

**Comment by fabnord** [comment]
@msewaweru @Justinha any update on this one? Customer is waiting for a doc fix on this.

**Comment by msewaweru** [comment]
Hello @fabnord, I will create doc update PR to add an example for this cmdlet. To answer part of question the valid values for `PreferredAuthenticationProtocol` are `WsFed` and `Samlp`.
