### ISSUE TITLE
Missing information about the output object type for New-AzureADMSInviation

### ISSUE THREAD

**Issue by astaykov** [Azure/azure-docs-powershell-azuread#689]
The documentation about [New-AzureADMSInvitation](https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0/AzureAD/New-AzureADMSInvitation.md) states the output of this command is an object, but it is lacking any description about the output object - type, properties, methods, etc.

**Comment by msewaweru** [comment]
Thanks @astaykov for highlighting this. 

@jpettere, could you help with what we need to update in docs to resolve this issue?

**Comment by fabnord** [comment]
@msewaweru @jpettere any update on this one?

**Comment by msewaweru** [comment]
@astaykov apologies for delay in responding to this I'm following up with the team to get an update.

**Comment by msewaweru** [comment]
Hi @astaykov , a sample output has been added as part of the example. 

Proceeding to close this issue.
