### ISSUE TITLE
 "Get-AzureADAuditDirectoryLogs" is not recognized error

### ISSUE THREAD

**Issue by TonySh127-ms** [Azure/azure-docs-powershell-azuread#690]
I would like to consult the term 'Get-AzureADAuditDirectoryLogs' is not recognized reason. The command can be found in the ISE and can be tab in the command line. But it still show the not recognized error after enter. Any workaround or solution will be much appreciate. 
reproduce step

- Run command: AzureADPreview\Connect-AzureAD
- Run command: Get-AzureADAuditDirectoryLogs >> Not recognized error

Mitigate method (only can mitigate one time. The window which run install module command cannot be closed):

- Run command: Install-Module -name AzureADPreivew first
- Run AzureADPreview\Connect-AzureAD and Get-AzureADAuditDirectoryLogs will work

But if I close all windows or restart the machine. The command line will be not recognized again. 

collected process mon
![image](https://user-images.githubusercontent.com/68043042/130559037-aee3a43f-8490-4b5a-a569-b0dd56b28df6.png)

**Comment by msewaweru** [comment]
Hello @TonySh127-ms , thanks for your issue submission and apologies for the delayed response.

What version of the Azure AD Preview module are you running? I was able to run the cmdlet but did not encounter the error you indicated. I'm on the latest version 2.0.2.138.
![image](https://user-images.githubusercontent.com/73849846/149479112-d5573e4c-f338-4ce0-a08f-5b56edd14227.png)

Proceeding to close this issue. Feel free to reopen it with any follow up comments.
