### ISSUE TITLE
Get/Set-AzureADMSAuthorizationPolicy: add documentation for stable verison

### ISSUE THREAD

**Issue by commakoerschgen** [Azure/azure-docs-powershell-azuread#713]
These commands are now in the stable version (tested with 2.0.2.140). Please add appropriate documentation.

Note that the syntax has changed heavily in comparison to the preview. I do not know whether the preview commands still use the old syntax.

**Comment by CelesteDG** [comment]
#assign:@mswaweru

**Comment by msewaweru** [comment]
Hello @commakoerschgen, we have added documentation for the 2 cmdlets. I will proceed to close this issue. Feel free to get back to me with further feedback.
