### ISSUE TITLE
New-AzureADMSGroup errors with -Membershiprule

### ISSUE THREAD

**Issue by jishua9** [Azure/azure-docs-powershell-azuread#717]
https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsgroup?view=azureadps-2.0
The powershell comment New-AzureADMSGroup errors saying there is no parameter for -membershiprule.
The example code in the documentation also errors wit the same response. It seems that this feature is not supported on this function anymore

**Comment by homotechsual** [comment]
The parameter doesn't exist on the standard `AzureAD` module - it does exist for `AzureADPreview` it should be removed from examples on the `AzureAD` module

**Comment by alan-hu** [comment]
I am running AzureADPreview v2.0.2.138 and this MembershipRule parameter still isn't recognized?!

**Comment by msewaweru** [comment]
Issue resolved by https://github.com/Azure/azure-docs-powershell-azuread/pull/728
