### ISSUE TITLE
No example for Connect-AzureAD using Service Principal with a Secret Key

### ISSUE THREAD

**Issue by WillParry** [Azure/azure-docs-powershell-azuread#721]
The only example for using Connect-AzureAD using a Service Principal is with a certificate. Sometimes this isn't practical, I could provide some code for an example using a Client Secret as I've had to work that out, which I did with some assistance from users on the PowerShell channel on Slack.com

**Comment by msewaweru** [comment]
Hello @psignoret, could you help us with adding the requested example.

**Comment by WillParry** [comment]
Hi @msewaweru 

Sorry, ADHD, I'm always really busy and so I often want to help out or respond etc. I basically ended up creating a function I'm using do do this, but it's a bit complicated, in that some cmdlets need 'Scope', my function has a switch parameter called -UseScope, so if that's set, then the URL used for getting an access token is "https://graph.microsoft.com/.default" otherwise it's "https://graph.microsoft.com".

I'll try to share shortly, just checking if my code is suitable, generic enough. Thanks for chasing though.

**Comment by WillParry** [comment]
I've extracted the code from my function, as I wasn't too sure about it. It feels a bit long winded for an example in the documentation and could also do with a list of commands that require the access token using the resource and those that require a scope access token.

For example, my full script used resource access token for Get-AzureADMSTrustFrameworkPolicy, Set-AzureADMSTrustFrameworkPolicy and New-AzureADMSTrustFrameworkPolicy and used the scope access token for Get-AzureADApplication and Get-AzureADServicePrincipal

```
$TenantId = # tenant id
$ClientId = # client id
$ClientKey = # client key or password
$UseScope = # true or false - switch in function

$B2CUri = "https://login.microsoftonline.com/$TenantId/oauth2/token"
$xwwwform = "application/x-www-form-urlencoded"
$granttype = "client_credentials"
$GraphResource = "https://graph.microsoft.com"
$GraphScope = "https://graph.microsoft.com/.default"

# Setting Request Body with scope for Graph
$scopeRequestBody = @{
    grant_type    = $granttype
    client_id     = $ClientId
    client_secret = $ClientKey
    scope         = $GraphScope
}

# Setting Request Body with resource for Graph
$requestBody = @{
    grant_type    = $granttype
    client_id     = $ClientId
    client_secret = $ClientKey
    resource      = $GraphResource
}

# Making the Web Request with Scope and Resource for Graph API and setting the response variables
$ScopeResponse = Invoke-WebRequest -Uri $B2CUri -Method Post -ContentType $xwwwform -Body $scopeRequestBody -UseBasicParsing
$ResourceResponse = Invoke-WebRequest -Uri $B2CUri -Method Post -ContentType $xwwwform -Body $requestBody -UseBasicParsing

# Setting the Access token variables for Graph API from the responses using scope and resource requests
$ScopeAccessToken = $ScopeResponse.Content | ConvertFrom-Json | Select-Object -ExpandProperty access_token
$ResourceAccessToken = $ResourceResponse.Content | ConvertFrom-Json | Select-Object -ExpandProperty access_token

# Making an initial connection to Azure AD B2C using the Graph API Scope access token to enable the script
# to query Azure AD B2C for the Azure AD Domain and the in use credential
$ctx = Connect-AzureAD -MsAccessToken $ScopeAccessToken -TenantId $TenantId -AccountId $ClientId -AadAccessToken $ScopeAccessToken

$CtxTenant = Get-AzureADDomain | Select-Object -ExpandProperty Name
Write-Verbose "Tenant domain for Azure AD B2C is $CtxTenant"

$CtxTenantId = $ctx.TenantId
Write-Verbose "Tenant ID for Azure AD B2C is $CtxTenantId"

$Ctxuser = Get-AzureADServicePrincipal -Filter "appid eq '$ClientId'" | Select-Object -ExpandProperty DisplayName
Write-Verbose "User for Azure AD B2C is $Ctxuser"

# This is just for information
$CtxTenantShort = $CtxTenant.Replace(".onmicrosoft.com", "")
Write-Verbose "Tenant short name for Azure AD B2C is $CtxTenantShort"

# If we haven't called the function with the UseScope switch, then we need to make another connection using the Graph API
# resource access token to replace the connection already make with the scope access token
if (!($true -eq $UseScope)) {
    $ctx = Connect-AzureAD -MsAccessToken $ResourceAccessToken -TenantId $TenantId -AccountId $ClientId -AadAccessToken $ResourceAccessToken
}

return $ctx

```

**Comment by psignoret** [comment]
@msewaweru I suggest asking the owners of the PowerShell module whether they want to include an example using client secret. (In the Microsoft Graph PowerShell examples, for instance, this was deliberately omitted: https://docs.microsoft.com/graph/powershell/app-only)

@WillParry The main issue with the example script as you've shown it that it suggests the poor practice of including highly privileged credentials in a script. While I have no doubt at line 3 you mean "retrieve the client secret from a protected location", it's unfortunately very common for less experienced users to copy-paste the script, paste in their (highly privileged) client secret, and then share the script or store it in an insecure location.

**Comment by WillParry** [comment]
> @WillParry The main issue with the example script as you've shown it that it suggests the poor practice of including highly privileged credentials in a script. While I have no doubt at line 3 you mean "retrieve the client secret from a protected location", it's unfortunately very common for less experienced users to copy-paste the script, paste in their (highly privileged) client secret, and then share the script or store it in an insecure location.

A good point, perhaps I need to update my snippet and or function to make it more secure, I'm not storing any credentials in it of course, these come from the automation that I intended to run my script / function, but I see your point any it would be better if an example were to be provided that it show a very secure way of doing this. Thanks for the feedback.

**Comment by msewaweru** [comment]
@DerrickJKimani, please direct me to the owner of this cmdlet.
