### ISSUE TITLE
Get-AzureADMSPrivilegedRoleSetting -ProviderId AzureResources

### ISSUE THREAD

**Issue by Kaidja** [Azure/azure-docs-powershell-azuread#723]
Hi,

I'm trying to query Azure Resource roles with this command but it fails. Am I missing something important or this cmdlet is broken?

Get-AzureADMSPrivilegedRoleSetting : Error occurred while executing GetAzureADMSPrivilegedRoleSettings 
Code: UnauthorizedAccessException
Message: Attempted to perform an unauthorized operation.
InnerError:
  RequestId: a3421aaf-ce2b-4302-a75c-adda94d3aa72
  DateTimeStamp: Mon, 18 Oct 2021 17:35:49 GMT
HttpStatusCode: Forbidden
HttpStatusDescription: Forbidden
HttpResponseStatus: Completed
At line:1 char:1
+ Get-AzureADMSPrivilegedRoleSetting -ProviderId AzureResources -Filter ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADMSPrivilegedRoleSetting], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.GetAzureADMSPrivilegedRoleSetting

**Comment by msewaweru** [comment]
@Kaidja , from the error it seems the account has no rights to PIM. Is the account you are using a Global administrator or a Privileged role administrator?

**Comment by Kaidja** [comment]
I discovered that the filter was wrong. I had the GA account permissions.

**Comment by msewaweru** [comment]
Proceeding to close this issue.
