### ISSUE TITLE
Error while registering new application in AD using Azure Powershell.

### ISSUE THREAD

**Issue by venkateshtarra** [Azure/azure-docs-powershell-azuread#724]
Hi Team,

I am trying to create FHIR server in Azure and registering API in AD using below command but it is giving error as highlighted.
I have upgraded AZ module version to 6.5 but still getting this error. Can we solve this issue without creating subdomain under registered custom domain name as mentioned in this link.

#16097 (comment)

New-AzureADApplication -DisplayName $FhirServiceAudience -IdentifierUris $FhirServiceAudience -AppRoles $desiredAppRoles
New-AzureAdServicePrincipal -AppId $apiAppReg.AppId | Out-Null

Error:-

"Error occurred while executing NewApplication Code: Request_BadRequest Message: Values of identifierUris property must use a verified domain of the
| organization or its subdomain: 'https://fhirpaas21.azurehealthcareapis.com' RequestId: 0ab2b655-a4cb-47bf-83b1-4a25a891eacb DateTimeStamp: Tue, 26 Oct
| 2021 12:44:59 GMT Details: PropertyName - identifierUris, PropertyErrorCode - HostNameNotOnVerifiedDomain, HostName -
| https://fhirpaas21.azurehealthcareapis.com HttpStatusCode: BadRequest HttpStatusDescription: Bad Request HttpResponseStatus: Completed"

Thanks in advance
Venkatesh Tarra.

**Comment by lithdk** [comment]
I dont really need a valid identifier uri for what I do, so I've used "https://dummy" thus far, which also broke. Am now using
`New-AzureADApplication -DisplayName "xxx" -IdentifierUris ("https://dummy.$((Get-AzureADDomain | where IsVerified -eq $true)[0].name)")`

**Comment by DrReedo** [comment]
> I dont really need a valid identifier uri for what I do, so I've used "https://dummy" thus far, which also broke. Am now using `New-AzureADApplication -DisplayName "xxx" -IdentifierUris ("https://dummy.$((Get-AzureADDomain | where IsVerified -eq $true)[0].name)")`

Did that work @lithdk ?  I am also getting the same problem as my IdentifierUri contains azurewebsites.net which I can't verify in my domain.

**Comment by msewaweru** [comment]
Hello @sureshja, assigning this to you so you can help answer the customer question.

**Comment by msewaweru** [comment]
Hello @venkateshtarra, checking if you saw the previous comment.

I will proceed to close this issue. Feel free to reopen it if the issue persists or if you have any follow up feedback.
