### ISSUE TITLE
unable to use variable in filter for Get-AzureADAuditSignInLogs

### ISSUE THREAD

**Issue by githubnoobie916** [Azure/azure-docs-powershell-azuread#727]
Trying to process a list of users using the script below but it doesnt seem to work correctly. When there are 2 users in the list there are no results and if there are 15 users I get an error message.

```
$csv = import-csv -Path "C:\Users\myaccountname\Documents\listofUPNsforsigninlogs.csv"

foreach ($row in $csv) {
    Get-AzureADAuditSignInLogs -Filter "UserPrincipalName eq '$row.UserPrincipalName'" -Top 1 |
    select CreatedDateTime, UserPrincipalName, IsInteractive, AppDisplayName, IpAddress, TokenIssuerType, @{Name = 'DeviceOS'; Expression = {$_.DeviceDetail.OperatingSystem}}
}

```

Error message I get when there are over 15 users in the list:

```
Get-AzureADAuditSignInLogs : Error occurred while executing GetAuditSignInLogs 
Code: UnknownError
Message: Too Many Requests
InnerError:
  RequestId: 42c1c61e-50e5-4178-b12e-e7aba79faaaa
  DateTimeStamp: Wed, 27 Oct 2021 22:52:06 GMT
HttpStatusCode: 429
HttpStatusDescription: Too Many Requests
HttpResponseStatus: Completed
At line:6 char:5
+     Get-AzureADAuditSignInLogs -Filter $filter -Top 1 |
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADAuditSignInLogs], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.GetAuditSignInLogs
```

**Comment by SomeoneElseWhoCodes** [comment]
I was running into this issue tonight and after lots of searching I came across this page and a post on spiceworks.

The following works:
Get-AzureADAuditSignInLogs -Filter "UserPrincipalName eq '**user@domain**'" -Top 1 | Select UserPrincipalName,IPAddress,CreatedDateTime

This works too:
Get-AzureADAuditSignInLogs -Top 1 -Filter "startsWith(userPrincipalName ,'**user@domain**')" | Select UserPrincipalName,IPAddress,CreatedDateTime

If I replace **user@domain** with a variable like $user.PrincipalUserName from Get-AzureADUser in either of the lines above, I get the following error complaining about the _filter_ parameter:
Get-AzureADAuditSignInLogs : Error occurred while executing GetAuditSignInLogs 
Code: UnknownError
Message: Malformed request. Please reformat your request and try again.
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed

**Quick Specs:**
PSVersion 7.2.0
PSEdition Core
AzureADPreview 2.0.2.149
Windows 11 Pro

**Comment by psignoret** [comment]
You can't embed a variable's property directly into the string like you're trying to do there. 

If you want to include a variable's property in a string, you need to surround the full name with `$()` (my preference):

```powershell
Write-Host "userPrincipalName eq '$($user.UserPrincipalName)'"
```
```none
userPrincipalName eq 'bob@example.com'
```

Or use string concatenation:

```powershell
Write-Host ("userPrincipalName eq '" + $user.UserPrincipalName + "'")
```
```none
userPrincipalName eq 'bob@example.com'
```

Or you use a format string with `-f`:

```powershell
Write-Host ("startsWith(userPrincipalName ,'{0}')" -f $user.userPrincipalName)
```
```none
startsWith(userPrincipalName ,'bob@example.com')
```

Or with `[String]::Format()`:

```powershell
Write-Host [String]::Format("startsWith(userPrincipalName ,'{0}')", $user.userPrincipalName)
```
```none
startsWith(userPrincipalName ,'bob@example.com')
```

**Comment by msewaweru** [comment]
Proceeding to close this issue as there is no feedback from the customer.
