### ISSUE TITLE
Get-AzureADGroup -SearchString error

### ISSUE THREAD

**Issue by tp-matt-wiese** [Azure/azure-docs-powershell-azuread#743]
Running into an issue where I attempt to use -SearchString with that command and receive the following error:

Get-AzureADGroup: Could not load file or assembly 'Microsoft.Data.Services.Client, Version=5.8.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

I am running VSCode on macOS. Most other simple commands work but I fear that other, far more important, operations will be affected.

Name                           Value
----                           -----
PSVersion                      7.2.0                                                
PSEdition                      Core                                                                     
GitCommitId                    7.2.0                                                                                                          
OS                             Darwin 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64
Platform                       Unix                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}                                                               
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0      

thanks in advance for any attention on this

**Comment by msewaweru** [comment]
Hello @tp-matt-wiese and thanks for highlighting this issue. Could share the actual query that you are running. When I run it as below I do not get an error.

![image](https://user-images.githubusercontent.com/73849846/150144638-b858ce43-a987-48c9-962a-08282824b4fb.png)

**Comment by msewaweru** [comment]
@tp-matt-wiese. proceeding to close this issue.

Feel free to reopen it with any follow up feedback based on my earlier response. Thanks.

**Comment by tp-matt-wiese** [comment]
sorry @msewaweru this is still an issue
Please see the screenshot below

<img width="1618" alt="image" src="https://user-images.githubusercontent.com/94641090/154093386-4792f0c8-2047-4234-aaee-6764fb9ceb85.png">

**Comment by msewaweru** [comment]
@tp-matt-wiese , sorry about that. I must have missed some info you provided earlier. I see you are running PowerShell 7. Azure AD PowerShell is not compatible with PowerShell 7. Please use PowerShell 5.1.
