### ISSUE TITLE
MembershipRule and MembershipRuleProcessingState attributes not visible

### ISSUE THREAD

**Issue by uttampcu** [Azure/azure-docs-powershell-azuread#745]
MembershipRule & MembershipRuleProcessingState attributes not available in the latest AzureAD or AzureADPreview modules as of Dec-2-2021

**Comment by msewaweru** [comment]
Hello @uttampcu for highlighting this. This 2 attributes are available on Azure AD Preview. I'm running the latest Azure AD Preview version 2.0.2.138 and I'm able to execute the example 1 in [this article](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadmsgroup?view=azureadps-2.0-preview#examples).

Please let me know what error you are experiencing.

**Comment by msewaweru** [comment]
Hello @uttampcu, proceeding to close this issue. Feel free to reopen it with any follow up feedback based on my earlier response. Thanks.
