### ISSUE TITLE
Get-AzureStorageContainer - Specify Authentication

### ISSUE THREAD

**Issue by RocketRob97** [Azure/azure-docs-powershell-azuread#749]
Hi all,

i am trying to use Get-AzureStorageContainer to get all Containers from a Storage Account with disabled Key authentication.

I have found there is a -DefaultProfile Argument, but i don't know what to pass and if this is even a viable option. Would a REST Call help here? I am not really familiar with REST API and would like to use Powershell Cmdlets if possible.

Thank you!!

Error:

```
Get-AzStorageContainer : Key based authentication is not permitted on this storage account. HTTP Status Code: 403 - HTTP Error Message: Key based authentication is not permitted on this storage account.
ErrorCode: KeyBasedAuthenticationNotPermitted
ErrorMessage: Key based authentication is not permitted on this storage account.
```

**Comment by msewaweru** [comment]
Hi @RocketRob97, I'm not sure which PowerShell module you are running as Get-AzureStorageContainer cmdlet is not part of the AzureAD PowerShell cmdlets.
Issues in this repo are for documentation issues. You can try one of the following links for additional help.
Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

Proceeding to close this issue. feel free to reopen with any follow up feedback.

**Comment by sarahtindal** [comment]
I have the same issue. Unable to use Powershell to list the containers on a storage account with shared key access disabled. The PowerShell cmdlet is Get-AzStorageContainer. 

Error:
Get-AzStorageContainer: Key based authentication is not permitted on this storage account.
Status: 403 (Key based authentication is not permitted on this storage account.)
ErrorCode: KeyBasedAuthenticationNotPermitted
