### ISSUE TITLE
Set-AzureADMSConditionalAccessPolicy issue not updating groups and users on web UI

### ISSUE THREAD

**Issue by Palasito** [Azure/azure-docs-powershell-azuread#750]
Created a function to import AADGroups and assign them to Conditional access policies by name.

After running the function went on to aad.portal.azure.com and endpoint.microsoft.com in order to check the outcome and all the relevant policies were not updated.

![image](https://user-images.githubusercontent.com/59915398/145987143-20421d5b-2286-41e5-8c7d-9b2c55ed321f.png)

Immediately ran "((Get-AzureADMSConditionalAccessPolicy -PolicyId "policyidtocheck").Conditions).Users" and the output was correct. 

![image](https://user-images.githubusercontent.com/59915398/145987974-9273269a-ff82-4fe4-a33b-3961c7527a82.png)

In addition to that I added a test user to one of the groups and after 5-10min the Policies started applying successfully on him.

Been waiting for about 1.5hrs at the moment and the Web UI is still showing that the policies have no users or groups assigned.

I am using version 2.0.2.140 of the AzureAD Module

**Comment by Palasito** [comment]
Update: 2 days later the same issue persists, conditional access policies are working as expected to users but the Web UI is still at "0 users or workload identities selected"

**Comment by davidspooner** [comment]
HI Palasito, I would be happy to look into this further with you. Would you be willing to share more detailed about your function? I assume if you use the group GUID's the Web UI updates correctly?

**Comment by Palasito** [comment]
Hello davidspooner, unfortunately no, I could not make the web UI update correctly.

Function is a part of a bigger powershell script (~500 lines) that basically assigns groups to Conditional Access Policies via a CSV file where the values are:

- DisplayName of CA Policy
- IncludedGroups (The diplayNames of groups to include)
- ExcludedGroups (The DisplayNames of groups to Exclude)

I am attaching the code used(it's trimmed, not whole script, just the part that sets the conditional access policy)

`        $Policy = Get-AzureADMSConditionalAccessPolicy | Where-Object displayName -eq $pol.DisplayName
        $InclGrps = $pol.IncludeGroups -split ";"
        $ExclGrps = $pol.ExcludeGroups -split ";"
        [Microsoft.Open.MSGraph.Model.ConditionalAccessConditionSet]$PolicyConditions = $Policy.Conditions

            foreach ($grp in $InclGrps){
                $inclgrpid = Get-AzureADMSGroup | Where-object displayname -eq "$grp"
                $PolicyConditions.IncludeGroups += $inclgrpid.id
            }

            foreach($grp in $ExclGrps){
                $exclgrpid = Get-AzureADMSGroup | Where-object displayname -eq "$grp" 
                $PolicyConditions.ExcludeGroups += $exclgrpid.Id
            }

        $Conditions.Users = $PolicyConditions

        Set-AzureADMSConditionalAccessPolicy -PolicyId $Policy.Id -Conditions $Conditions`

**Comment by davidspooner** [comment]
Hi @Palasito, Thanks for your patience on this. The developer has been looking into the bug I opened and reviewed the code and we can confirm the current behaviour is a result of the configuration of the policy before you apply the include or exclude groups.

In your example above, the original policy assignment for users was set to none. With PowerShell there currently is no logic that if you include a user or group that it automatically clears the "none" state.  In the UX, when you select the radial button for include user, behind the scenes it also clears the "none" state.

In your script, in addition to the $PolicyConditions.IncludeGroups += $inclgrpid.id, you will also need to clear the "None" state for Users.includeUsers.  To do this you should call the following in your script

$PolicyConditions.Users.IncludeUsers = @()

This will remove the "None" and then allow the specific include and exclude on the policy to be configured. If you don't do this, the policy is technically not valid hence the UI does not update and show correctly. By running the above in your script, it will remove the "None", which will set the policy correctly and it will show correctly in PowerShell, API (Graph) and the UI.

I am discussing with the developers about future changes to include possible logic that would remove the need to clear the IncludeUsers and do it automatically like in the UI.  For now though please use the  Users.IncludeUsers =@() and this should solve the UI problem.

Thanks for your patience and hope this helps. If this does not solve your issue please let me know and we can always reopen this thread. I will archive for the moment but please reach out if you need further assistance.
