### ISSUE TITLE
Get-AzureADAuditSignInLogs is Case Sensitive and Shouldn't Be

### ISSUE THREAD

**Issue by PhrygianMode** [Azure/azure-docs-powershell-azuread#755]
When using the command:

_Get-AzureAdAuditSigninLogs -filter "userprincipalname eq 'First.Last@companyname.com'"_

I have confirmed that the command is case sensitive. If I run the command with any capital letters, the command fails to retrieve any results. Even if the account is setup as 'First.Last' in active directory, it must be run as 'first.last' in PowerShell. This is a nightmare for scripting because I am piping values with uppercase characters and when the script runs, half of the time no results are returned because the case isn't correct. Very frustrating.

**Comment by PhrygianMode** [comment]
This issue was also investigated during Microsoft case #2201120040007940 via support agent with alias 'olosinsk'.

**Comment by msewaweru** [comment]
Hello @PhrygianMode thanks for surfacing this issue. We have been resolving the fact that this filter query does not work as provided in the docs and have instead done [a PR](https://github.com/Azure/azure-docs-powershell-azuread/pull/754) to update that example provided for this cmdlet. We are however following up on finding out why this query does not work as is.

In the meantime, please use and let's know if the issue of case sensitivity persists.
```
Get-AzureADAuditSignInLogs -Filter "startsWith(userPrincipalName ,'First.Last@companyname.com')"

```

**Comment by msewaweru** [comment]
Proceeding to close this issue after [the PR](https://github.com/Azure/azure-docs-powershell-azuread/pull/754) was merged.

**Comment by PhrygianMode** [comment]
> Hello @PhrygianMode thanks for surfacing this issue. We have been resolving the fact that this filter query does not work as provided in the docs and have instead done [a PR](https://github.com/Azure/azure-docs-powershell-azuread/pull/754) to update that example provided for this cmdlet. We are however following up on finding out why this query does not work as is.
> 
> In the meantime, please use and let's know if the issue of case sensitivity persists.
> 
> ```
> Get-AzureADAuditSignInLogs -Filter "startsWith(userPrincipalName ,'First.Last@companyname.com')"
> ```

Hi msewaweru, I appreciate the response.  I used the filter command you proposed and it seems to be working without problems.  I appreciate it!
