### ISSUE TITLE
Docs should call out deprecation and lack of PowerShell 7 support

### ISSUE THREAD

**Issue by billti** [Azure/azure-docs-powershell-azuread#760]
The page at https://docs.microsoft.com/en-us/powershell/module/azuread makes no mention that this module is deprecated. The page at https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview states _"The Microsoft Graph PowerShell SDK is the replacement for the Azure AD PowerShell module and is recommended for interacting with Azure AD"_, so I assume this is the case.

Also, the landing page should be clearer that Windows PowerShell is required, and that the latest PowerShell 7 doesn't work. (I spent a while trying to resolve the issue outlined in https://github.com/PowerShell/PowerShell/issues/10473 before figuring this out).

**Comment by msewaweru** [comment]
Hello @billti thanks for highlighting this issues. We are already working on updating the deprecation content. I will also add a note on the overview page to highlight that Azure AD PowerShell does not work with PowerShell 7.

<html>
<body>


ID | Work Item Type | Title | Assigned To | State | Tags
-- | -- | -- | -- | -- | --
1754771 | Product Backlog Item | Issue: Update the overview page to highlight that Azure AD PowerShell does not work with PowerShell 7. | Eunice Waweru | New |

**Comment by msewaweru** [comment]
@billti, proceeding to close this issue after the merging of the PR #776. The documentation on migration to Microsoft Graph PowerShell is work in progress. Be on the look for the same.
