### ISSUE TITLE
Get-AzureADApplicationProxyApplication

### ISSUE THREAD

**Issue by lightupdifire** [Azure/azure-docs-powershell-azuread#774]
Hello,
When running this PS "Get-AzureADApplicationProxyApplication -ObjectId $item.objectid":

https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0/AzureAD/Get-AzureADApplicationProxyApplication.md

Error received:
Get-AzureADApplicationProxyApplication : Error converting value "aadHeaderBased" to type 'System.Nullable`1[Microsoft.Open.MSGraph.Model.OnPremisesPublishingSingleSignOnObject+SingleSignOnModeEnum]'. Path 'singleSignOnSettings.SingleSignOnMode', line 1, position 948

Tested with Preview and Normal AzureAD version.

Any ideas?

**Comment by msewaweru** [comment]
Hello @lightupdifire , thanks for your query.

Could you share the definition you used for the variable **$item**. There is seems to be a problem with the data type conversion.

You could also try running this as:

`Get-AzureADApplicationProxyApplication -ObjectId $ObjectId`

by replacing $ObjectId with the ObjectId of your application. Let me know how that goes.

**Comment by lightupdifire** [comment]
@msewaweru 
Thanks for the feedback! I think I got this as well, have to give it like a bigger object :)
I try to find all on-prem apps and add a new cert as our thumbprint changed... below code worked, maybe can add a second article to replace the wildcard if the thumbprint is different.

`Write-Host "Reading Azure AD applications. This operation might take longer..." -BackgroundColor "Black" -ForegroundColor "Green"
$App = Get-AzureADApplication -All $true | Select-Object Displayname, ObjectId
$i = 1
$count = $app.count
Foreach ($apps in $app)
{
    Write-Progress -Activity "Getting $($apps.DisplayName) App-proxy information" -Status "$i of $count" -PercentComplete ($i/$count*100)
      try {
            $proxy = Get-AzureADApplicationProxyApplication -ObjectId "$($apps.Objectid)" -ErrorAction Stop
            #####The Above cmdlet is used to get list of App-proxy Applications###########
			if (($proxy.IsOnPremPublishingEnabled -eq $true) -and ($proxy.ExternalUrl -like "*mycustomdomain.com*"))
			{
				Write-Host ("Found on-premise Application with External domain as mycustomdomain.com: $($apps.Displayname)") -BackgroundColor "Black" -ForegroundColor "Yellow"
			
				if ($proxy.VerifiedCustomDomainCertificatesMetadata.Thumbprint -notmatch $certThumbprint)
				{
				Write-Host ("SSL certificate change required for the Azure AD Application Proxy App below: $($apps.Displayname) with ObjectID: $($apps.Objectid)") -BackgroundColor "Black" -ForegroundColor "Green"
				Set-AzureADApplicationProxyApplicationCustomDomainCertificate -ObjectId  $($apps.Objectid) -PFXFilePath $pfxPath -Password $securePassword
				}
			}
          } #End of Try Statement
      catch {   
             $Problem = $PSItem.exception.message         
            } #End of Catch statement
    $i++
} #End of Foreach loop
### End of Core ###`
