### ISSUE TITLE
Azure CLI - How to get Service Principal Membership?

### ISSUE THREAD

**Issue by GYOERFT** [Azure/azure-docs-powershell-azuread#778]
Hello,

is there any Azure CLI Feature similar to "Get-AzureADServicePrincipalMembership" ?

I am collecting permission information of our platform using python and azure-cli-core module and need to get group memberships of service principals. 

any idea?

**Comment by msewaweru** [comment]
Hi @GYOERFT , thanks for your query.

I think it would be easier to get a response on Azure CLI features if you logged this issue in the [Azure CLI repo](https://github.com/Azure/azure-cli/issues).
