### ISSUE TITLE
AzureADPreview Powershell module command Set-AzureADMSPrivilegedRoleSetting not working when executed using a service principal from a Devops Pipeline

### ISSUE THREAD

**Issue by Samix13** [Azure/azure-docs-powershell-azuread#784]
Running the following Powershell commands as an inline Powershell script from a Devops pipeline:

Install-Module AzureADPreview -Force
$token = Get-AzAccessToken -ResourceTypeName AadGraph
Connect-AzureAD -TenantId $token.TenantId -AadAccessToken $token.Token -AccountId $token.UserId -AzureEnvironmentName ((Get-AzContext).Environment).Name
$setting = New-Object Microsoft.Open.MSGraph.Model.AzureADMSPrivilegedRuleSetting
$setting.RuleIdentifier = "MfaRule"
$setting.Setting = "{`"mfaRequired`":true}"
Set-AzureADMSPrivilegedRoleSetting -ProviderId "AzureResources" -Id "8e3af657-a8ff-443c-a75c-2fe8c4bcb635" -UserMemberSettings $setting

And then receiving the following error message:
##[error]Object reference not set to an instance of an object.
##[error]PowerShell exited with code '1'.

The Service Principal running this task has the Azure AD role Privileged role administrator in the tenant.
Note that this Powershell command works as intended running it locally in Powershell from a context of a user logged in to Azure AD. 

![Set-AzureADMSPrivilegedRoleSetting_Error](https://user-images.githubusercontent.com/43829307/156005504-13c8eb19-4bd9-4a08-8693-b0c0c5bbcc45.jpg)

**Comment by rkarim-ms** [comment]
Thank you for reaching out and for your patience with the delayed response. If you are still receiving the error, we would like to request additional details to further investigate the issue, specifically a **correlation ID**. Adding @amanswaika.

We will keep you updated here as we continue to troubleshoot.

On a separate note, we have also released a new PowerShell module for PIM for Azure resources. Configuring role settings for Azure resources can now be done with the Update-AzRoleManagementPolicy module here:

https://docs.microsoft.com/en-us/powershell/module/az.resources/update-azrolemanagementpolicy?view=azps-8.2.0#examples

**Comment by msewaweru** [comment]
@Samix13 - I will proceed to close this issue as there has been no response since the last support update.
