### ISSUE TITLE
"contractType" does not display correctly in Get-AzureADContract.md

### ISSUE THREAD

**Issue by wiseleaf23** [Azure/azure-docs-powershell-azuread#787]
In https://github.com/Azure/azure-docs-powershell-azuread/blob/main/azureadps-2.0/AzureAD/Get-AzureADContract.md, "contractType" does not seem to be displayed correctly; it's not part of the bulleted list:

> DESCRIPTION
> The Get-AzureADContract cmdlet gets a contract from Azure Active Directory. This cmdlet returns a contract object for each contract that is selected by the request. The contract object contains the following attributes:
> 
> +contractType - Type of the contract. Possible values are: ++ "SyndicationPartner", which indicates a partner that exclusively resells and manages O365 and Intune for this customer. They resell and support their customers. ++ "BreadthPartner", which indicates that the partner has the ability to provide administrative support for this customer. However the partner is not allowed to resell to the customer. ++ "ResellerPartner", which indicates a partner that is similar to a syndication partner, except that it doesn't have exclusive access to a tenant. In the syndication case the customer cannot buy additional direct subscriptions from Microsoft or from other partners.
> 
> - customerContextId - The unique identifier for the customer tenant referenced by this partnership. Corresponds to the objectId property of the customer tenant's TenantDetail object.
> - defaultDomainName - A copy of the customer tenant's default domain name. The copy is made when the partnership with the customer is established. It is not automatically updated if the customer tenant's default domain name changes.
>

**Comment by msewaweru** [comment]
Hello @adimitui, could please assist with reviewing this issue and advising the customer? Thanks.

**Comment by msewaweru** [comment]
Hello @wiseleaf23, apologies for the delayed response on this.

I recommend that you try running this in Microsoft Graph PowerShell which is the recommended module for use with Azure AD. Azure AD and MSOnline modules are headed for deprecation and all investments are in the Microsoft Graph PowerShell module. Start here: [Overview of Microsoft Graph PowerShell](https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0).

Proceeding to close this issue.
