### ISSUE TITLE
AzureAD module does not support arm64 architecture

### ISSUE THREAD

**Issue by pszypowicz** [Azure/azure-docs-powershell-azuread#789]
Currently the AzureAD module support only AMD64 architecture.

On apple silicone M1 mac, i'm getting this message:

```
Import-Module -Name AzureAD
Import-Module: The current processor architecture is: MSIL. The module '/Users/xxx/.local/share/powershell/Modules/AzureAD/2.0.2.140/AzureAD.psd1' requires the following architecture: Amd64.
```

When running via rosseta2:
```
import-module -name azuread
Import-Module: The current processor architecture is: MSIL. The module '/Users/xxx/.local/share/powershell/Modules/AzureAD/2.0.2.140/AzureAD.psd1' requires the following architecture: Amd64.
PS /Users/xxx> uname -a
Darwin XXX 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 x86_64
PS /Users/xxx>
```

This should be at least reflected in the docs. Could you please point out to a proper bug tracker for the AzureAD Powershell module? Is there a reason why it is not available in the Github as public repository?

**Comment by msewaweru** [comment]
@kimaniderrick, could you advise on this issue.

**Comment by florian-obradovic** [comment]
Same here - is there any ETA for apple silicon?

**Comment by pszypowicz** [comment]
I just want to share, there is a official microsoft powershell module for interacting with microsoft graph, which is already compiled for arm64 Darwin: https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0

Very useful resource is a cmdlet map, which shows the old and related new cmdlet: https://docs.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-1.0

**Comment by pszypowicz** [comment]
That's why the cmdlet map I shared above is so important, you need to look each command and see if there is an equivalent.

**Comment by florian-obradovic** [comment]
ah, thanks mate !

**Comment by msewaweru** [comment]
@kimhubgit, is this something you can comment on?

**Comment by msewaweru** [comment]
> ah, thanks mate ! There are no commands to work with azure application proxy by now... too bad.

Hi @florian-obradovic apologies for the late response. We are working on following up with the owners of the application proxy cmdlets for a way forward on their migration.

On the ETA for apple silicon, all current investments are on the [Microsoft Graph PowerShell](https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0) and I recommend that you start to migrate your apps to this module. We are working on parity issues to ensure all cmdlets have equivalents, are well documented and examples provided.

Proceeding to close to this issue.
