### ISSUE TITLE
Problem installing AzureADPreview Module

### ISSUE THREAD

**Issue by nimchak** [Azure/azure-docs-powershell-azuread#790]
I have now tried this on two different systems with the same result. 

Actions I have taken to resolve the issue:
-Tried installing on multiple PS versions: Powershell V5.1.22000.282 ;  V5.1.19841.1320 ; V7.2.1
-Tried updating Powershellget to V1.0.0.1 to 2.2.5
-Tried on Windows 10 and windows 11
-Tried using -force with the install

Error during install:
PS C:\WINDOWS\system32> Install-Module -Name AzureADPreview -force
PackageManagement\Install-Package : The following commands are already available on this system:'Add-AzureADApplication
Owner,Add-AzureADDeviceRegisteredOwner,Add-AzureADDeviceRegisteredUser,Add-AzureADDirectoryRoleMember,Add-AzureADGroupM
ember,Add-AzureADGroupOwner,Add-AzureADServicePrincipalOwner,Confirm-AzureADDomain,Connect-AzureAD,Disconnect-AzureAD,E
nable-AzureADDirectoryRole,Get-AzureADApplication,Get-AzureADApplicationExtensionProperty,Get-AzureADApplicationKeyCred
ential,Get-AzureADApplicationLogo,Get-AzureADApplicationOwner,Get-AzureADApplicationPasswordCredential,Get-AzureADAppli
cationServiceEndpoint,Get-AzureADContact,Get-AzureADContactDirectReport,Get-AzureADContactManager,Get-AzureADContactMem
bership,Get-AzureADContactThumbnailPhoto,Get-AzureADContract,Get-AzureADCurrentSessionInfo,Get-AzureADDeletedApplicatio
n,Get-AzureADDevice,Get-AzureADDeviceConfiguration,Get-AzureADDeviceRegisteredOwner,Get-AzureADDeviceRegisteredUser,Get
-AzureADDirectoryRole,Get-AzureADDirectoryRoleMember,Get-AzureADDirectoryRoleTemplate,Get-AzureADDomain,Get-AzureADDoma
inNameReference,Get-AzureADDomainServiceConfigurationRecord,Get-AzureADDomainVerificationDnsRecord,Get-AzureADExtension
Property,Get-AzureADGroup,Get-AzureADGroupAppRoleAssignment,Get-AzureADGroupMember,Get-AzureADGroupOwner,Get-AzureADOAu
th2PermissionGrant,Get-AzureADObjectByObjectId,Get-AzureADServiceAppRoleAssignedTo,Get-AzureADServiceAppRoleAssignment,
Get-AzureADServicePrincipal,Get-AzureADServicePrincipalCreatedObject,Get-AzureADServicePrincipalKeyCredential,Get-Azure
ADServicePrincipalMembership,Get-AzureADServicePrincipalOAuth2PermissionGrant,Get-AzureADServicePrincipalOwnedObject,Ge
t-AzureADServicePrincipalOwner,Get-AzureADServicePrincipalPasswordCredential,Get-AzureADSubscribedSku,Get-AzureADTenant
Detail,Get-AzureADTrustedCertificateAuthority,Get-AzureADUser,Get-AzureADUserAppRoleAssignment,Get-AzureADUserCreatedOb
ject,Get-AzureADUserDirectReport,Get-AzureADUserExtension,Get-AzureADUserLicenseDetail,Get-AzureADUserManager,Get-Azure
ADUserMembership,Get-AzureADUserOAuth2PermissionGrant,Get-AzureADUserOwnedDevice,Get-AzureADUserOwnedObject,Get-AzureAD
UserRegisteredDevice,Get-AzureADUserThumbnailPhoto,New-AzureADApplication,New-AzureADApplicationExtensionProperty,New-A
zureADApplicationKeyCredential,New-AzureADApplicationPasswordCredential,New-AzureADDevice,New-AzureADDomain,New-AzureAD
Group,New-AzureADGroupAppRoleAssignment,New-AzureADMSInvitation,New-AzureADServiceAppRoleAssignment,New-AzureADServiceP
rincipal,New-AzureADServicePrincipalKeyCredential,New-AzureADServicePrincipalPasswordCredential,New-AzureADTrustedCerti
ficateAuthority,New-AzureADUser,New-AzureADUserAppRoleAssignment,Remove-AzureADApplication,Remove-AzureADApplicationExt
ensionProperty,Remove-AzureADApplicationKeyCredential,Remove-AzureADApplicationOwner,Remove-AzureADApplicationPasswordC
redential,Remove-AzureADContact,Remove-AzureADContactManager,Remove-AzureADDevice,Remove-AzureADDeviceRegisteredOwner,R
emove-AzureADDeviceRegisteredUser,Remove-AzureADDirectoryRoleMember,Remove-AzureADDomain,Remove-AzureADGroup,Remove-Azu
reADGroupAppRoleAssignment,Remove-AzureADGroupMember,Remove-AzureADGroupOwner,Remove-AzureADOAuth2PermissionGrant,Remov
e-AzureADServiceAppRoleAssignment,Remove-AzureADServicePrincipal,Remove-AzureADServicePrincipalKeyCredential,Remove-Azu
reADServicePrincipalOwner,Remove-AzureADServicePrincipalPasswordCredential,Remove-AzureADTrustedCertificateAuthority,Re
move-AzureADUser,Remove-AzureADUserAppRoleAssignment,Remove-AzureADUserExtension,Remove-AzureADUserManager,Restore-Azur
eADDeletedApplication,Revoke-AzureADSignedInUserAllRefreshToken,Revoke-AzureADUserAllRefreshToken,Select-AzureADGroupId
sContactIsMemberOf,Select-AzureADGroupIdsGroupIsMemberOf,Select-AzureADGroupIdsServicePrincipalIsMemberOf,Select-AzureA
DGroupIdsUserIsMemberOf,Set-AzureADApplication,Set-AzureADApplicationLogo,Set-AzureADDevice,Set-AzureADDomain,Set-Azure
ADGroup,Set-AzureADServicePrincipal,Set-AzureADTenantDetail,Set-AzureADTrustedCertificateAuthority,Set-AzureADUser,Set-
AzureADUserExtension,Set-AzureADUserLicense,Set-AzureADUserManager,Set-AzureADUserPassword,Set-AzureADUserThumbnailPhot
o,Update-AzureADSignedInUserPassword'. This module 'AzureADPreview' may override the existing commands. If you still
want to install this module 'AzureADPreview', use -AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Pack
   ageManagement.Cmdlets.InstallPackage

I would appreciate any help.

-NJ

**Comment by nimchak** [comment]
I believe I have figured this out.  I had to first uninstall the standard AzureAD Module to be able to install AzureADPreview.  They do not play well together.

What I did:
remove-module AzureAD
Restarted Powershell
Uninstall-Module AzureAD

I was then able to install-Module AzureADPReview

**Comment by msewaweru** [comment]
Hello @nimchak, thanks for highlighting the issue and I'm glad you have been able to fix it. On this article, [Install Azure AD PowerShell](https://docs.microsoft.com/en-us/powershell/azure/active-directory/install-adv2?view=azureadps-2.0), we recommend not to install both the Preview and GA version on the same computer. Thanks.
