### ISSUE TITLE
New-AzureADMSGroup no parameter for IsAssignableToRole

### ISSUE THREAD

**Issue by thecmdradama** [Azure/azure-docs-powershell-azuread#821]
Hi guys, 

When running the cmdlet New-AzureADMSGroup with parameter IsAssignableToRole I get this error:
`New-AzureADMSGroup: A parameter cannot be found that matches parameter name 'IsAssignableToRole'.`

This is with version 2.0.2.140 of the AzureAD module.

**Comment by msewaweru** [comment]
Thanks, @thecmdradama for highlighting this.

Please note that the -IsAssignableToRole parameter is only available in the Azure AD Preview version and not on the Azure AD module. Please retry using this version. Thanks.
