### ISSUE TITLE
 Get-AzureADUserThumbnailPhoto fails to return information for some users who have a photo icon in azure AD webportal

### ISSUE THREAD

**Issue by rbarbrow** [Azure/azure-docs-powershell-azuread#823]
Get-AzureADUserThumbnailPhoto fails to return information for some users who have a photo icon in azure AD web portal

**Comment by msewaweru** [comment]
Hello @rbarbrow, thanks for raising this issue. I will be working to find out more information about it and get back to you.

**Comment by msewaweru** [comment]
Hi @rbarbrow, thank you for your issue submission. Unfortunately, this appears to be a problem with the cmdlt and a support issue. Issues in this repo are for documentation issues. You can try one of the following links for additional help.

Microsoft Support: https://support.microsoft.com/
Azure AD forums: https://social.technet.microsoft.com/Forums/en-US/home?forum=windowsazureaditpro
Stackoverflow: https://stackoverflow.com/

Alternatively, you can use the [Get-MgUserPhoto](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.users/get-mguserphoto?view=graph-powershell-1.0&preserve-view=true) cmdlet using Microsoft Graph PowerShell which is where all current efforts are focused.
