### ISSUE TITLE
New-AzureADApplicationExtensionProperty Error occurred while executing

### ISSUE THREAD

**Issue by lucahost** [Azure/azure-docs-powershell-azuread#825]
Not sure where I can report issues like this.

The cmdlet ```New-AzureADApplicationExtensionProperty``` does not work if ```-TargetObjects``` is set to ```@("User", "Group")```

The graph request does work using the same name, dataType and targetObjects tho.

Could you maybe redirect this to the AzureAD PowerShell Team?

**Comment by msewaweru** [comment]
Hello @lucahost, I was able to run this command successfully. 

<img width="860" alt="image" src="https://user-images.githubusercontent.com/73849846/189077834-f6edf99c-3b30-4794-8eae-7aa31e7a726b.png">

I would recommend doing this using Microsoft Graph PowerShell which is the replacement for Azure AD and MSOnline module that are due for deprecation. You can start here: [Overview of Microsoft Graph PowerShell](https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0).

Proceeding to close this issue.
