### ISSUE TITLE
Incorrect ADObject reference

### ISSUE THREAD

**Issue by DevanshuSyk** [Azure/azure-docs-powershell-azuread#827]
# Give the Service Principal Reader access to the current tenant (Get-AzureADDirectoryRole)
Add-AzureADDirectoryRoleMember -ObjectId **5997d714-c3b5-4d5b-9973-ec2f38fd49d5** -RefObjectId $sp.ObjectId

**The object dosent exsist**

#Error
get-AzureADDirectoryRole : Error occurred while executing GetDirectoryRole
Code: Request_ResourceNotFound
Message: Resource '5997d714-c3b5-4d5b-9973-ec2f38fd49d5' does not exist or one of its queried reference-property objects are not present.
RequestId: d2b58ec8-7d8f-4f46-a629-d9f1c7758111
DateTimeStamp: Thu, 09 Jun 2022 15:01:30 GMT
HttpStatusCode: NotFound
HttpStatusDescription: Not Found
HttpResponseStatus: Completed
At line:1 char:1
+ get-AzureADDirectoryRole -ObjectId 5997d714-c3b5-4d5b-9973-ec2f38fd49 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADDirectoryRole], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.GetDirectoryRole

**Comment by msewaweru** [comment]
Hello @DevanshuSyk , thanks for highlighting this issue. Kindly confirm that you have used the Object Id of the service principal and not the app Id.
![image](https://user-images.githubusercontent.com/73849846/173382984-3af902f4-a714-4b13-a4c1-3af56d803984.png)

**Comment by DevanshuSyk** [comment]
Add-AzureADDirectoryRoleMember -ObjectId 5997d714-c3b5-4d5b-9973-ec2f38fd49d5 -RefObjectId $sp.ObjectId\
