### ISSUE TITLE
azureadps-2.0-preview/AzureAD/Get-AzureADMSUser.md - Example 1 does not work

### ISSUE THREAD

**Issue by TadaoMachida** [Azure/azure-docs-powershell-azuread#830]
azureadps-2.0-preview/AzureAD/Get-AzureADMSUser.md
### Example 1
```powershell
PS C:\> $user = Get-AzureADMSUser -UserPrincipalName TestUser@example.com 
```
Get a user by user principal name.

The command example above fails with "Get-AzureADMSUser : A parameter cannot be found that matches parameter name 'UserPrincipalName'".

**Comment by msewaweru** [comment]
Hi @TadaoMachida, thanks for highlighting this issue. I have been able to reproduce this issue and I have created a work item to track it's resolution. 

<html>
<body>


ID | Work Item Type | Title | Assigned To | State | Tags
-- | -- | -- | -- | -- | --
1949904 | Product Backlog Item | Issue: Correct example 1 in azureadps-2.0-preview/AzureAD/Get-AzureADMSUser.md | Eunice Waweru | New |  

</body>
</html>

To be able to move forward, please use this example:

```
Get-AzureADMSUser -Filter "UserPrincipalName eq 'Stevens@M365x81760664.OnMicrosoft.com'"
```
