### ISSUE TITLE
AzureADPreview Powershell module command Get-AzureADMSNamedLocationPolicy not working when executed from a Devops Pipeline

### ISSUE THREAD

**Issue by adispoerri** [Azure/azure-docs-powershell-azuread#834]
Using following part

    Connect-AzAccount -Credential $cliCreds -TenantId $TenantID
    Connect-AzureAD -Credential $cliCreds -TenantId $TenantID
    Write-Host "connected to AAD successfully"
    Write-Host ""

    Write-Output "Start DEBUG"
    Get-AzureADMSNamedLocationPolicy
    Write-Output "DEBUG End"

![Output](https://user-images.githubusercontent.com/52703082/175569701-ed30b7f2-d603-49c1-bc6b-3659e74a5e53.png)

-> the script stuck on "Get-AzureADMSNamedLocationPolicy" and the Pipeline stops after the timeout (60min) is reached
-> the same code connected with the same Account runs fine on local Session - so Permissions looks fine to me
-> Conditional Access shows no Errors/Issues

- the Credentials are builded from a KeyVault - Secret
- vmImage = windows-latest (using windows-2019 shows the same Result)
- when I add some Debug-Code like "(Get-AzureADApplication -Top 10).DisplayName" it runs without any Issue

Last successfull run was on last Wednesday (2022-06-22): 

![LastGoodRun](https://user-images.githubusercontent.com/52703082/175569599-f472d1b5-219d-4df3-9cf0-42f73d41c695.png)

<br>

Module-Version:

![AzureADPreviewModule](https://user-images.githubusercontent.com/52703082/175569661-4a1b14ec-9aad-4463-a67a-4dffbc77e056.png)

**Comment by msewaweru** [comment]
Hello @adispoerri, thanks for highlighting this issue. I will work to reproduce this on my end and will get back to you on the way forward.

**Comment by msewaweru** [comment]
@lstallman, assigning this to you for your advice on what the issue could be here.

**Comment by lstallman** [comment]
@adispoerri Thank you for sharing this information.  When you say "the same code connected with the same Account runs fine on local Session" can you describe what you mean by local session?  Also to confirm, the issue occurs when you are running the same script via Azure DevOps pipeline?

My hunch is that even though you are providing the connection credentials in the script, you might need to allow API access or resolve some other access issue when Azure AD cmdlets are being run via the pipeline.

**Comment by msewaweru** [comment]
Hello @adispoerri, checking if you have been able to look through the previous comment.

Check out [this post](https://blog.hompus.nl/2020/11/11/manage-azure-ad-applications-from-an-azure-devops-pipeline/#:~:text=%20Manage%20Azure%20AD%20applications%20from%20an%20Azure,Attempts%20with%20assigning%20administrator%20roles%20to...%20More) as well if you are still stuck.

Proceeding to close this issue. Feel free to reopen it with follow up feedback.
