### ISSUE TITLE
Version History Outdated - Missing Preview Version 2.0.2.149

### ISSUE THREAD

**Issue by bmkaiser** [Azure/azure-docs-powershell-azuread#841]
The current version history page doesn't include what changes were a part of Azure AD Preview version 2.0.2.149 even though it was released 5 months ago.

![image](https://user-images.githubusercontent.com/5446414/178316664-530b368b-73ef-46a6-8178-6fc28b451faf.png)

![image](https://user-images.githubusercontent.com/5446414/178316577-4dbd30a9-e786-4c31-a237-0388c918f555.png)

**Comment by msewaweru** [comment]
Hello @bmkaiser, thanks for highlighting this issue. I've initiated a process to get the information required to update this page. I have also created a work item to track this task. Proceeding to close this issue and will update once the work item is updated. Thanks.

<html>
<body>


ID | Work Item Type | Title | Assigned To | State | Tags
-- | -- | -- | -- | -- | --
1988838 | Product Backlog Item | Update the Azure AD Preview version history page with the details of the latest version 2.0.2.149 | Eunice Waweru | New |  


</body>
</html>
