### ISSUE TITLE
Get-AzureADUser OnPremisesUserPrincipalName

### ISSUE THREAD

**Issue by Get-SomeCofee** [Azure/azure-docs-powershell-azuread#849]
Get-AzureADUser does not retrieve all properties listed on the web interface.  Please update the module to retrieve all properties.  

Also update Set-AzureADUser as well.

OnPremisesUserPrincipalName
OnPremisesDistinguishedName
OnPremisesSamAccountName

**Comment by msewaweru** [comment]
Hello @Get-SomeCofee, thanks for highlighting this issue. Do you mean return these properties by default.
You can select the properties you want returned by the cmdlet by running:
`
Get-AzureADUSer -objectId $UserId | Select onPremisesSamAccountName,onPremisesDistinguishedName,onPremisesDomainName`

Let me know if this answers your query.

**Comment by Get-SomeCofee** [comment]
Hello,
This suggested command doesn't work.  Returns blank properties.

onPremisesSamAccountName onPremisesDistinguishedName onPremisesDomainName
------------------------ --------------------------- --------------------

**Comment by Mike-Crowley** [comment]
Those are extension properties. They are nested in the `extensionproperty` attribute. You can see them like:

`Get-AzureADUser -ObjectId user1@example.com | Select-Object -ExpandProperty extensionproperty | Format-Table`

**Comment by Get-SomeCofee** [comment]
@Mike-Crowley Thanks for the suggestion
`Get-AzureADUser -ObjectId user1@example.com | Select-Object -ExpandProperty extensionproperty`

this command does return the onPremisesDistinguishedName property.  
It does not OnPremisesUserPrincipalName or OnPremisesSamAccountName

**Comment by msewaweru** [comment]
@mmcla tagging you here to help with this issue. Thanks.

**Comment by Mike-Crowley** [comment]
@Get-SomeCofee 

The Msonline and Azuread powershell modules use "AZURE AD" Graph, not Microsoft Graph. Azure AD Graph doesn't include those other two attributes. You can test here:

https://graphexplorer.azurewebsites.net/#

Note: Azure AD Graph is deprecated, and Microsoft Graph is the current API. But for this, you need to use the Microsoft Graph SDK module.

attributes returned for a user are listed here:
https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/users-operations#get-users--

**Comment by Get-SomeCofee** [comment]
so... Get-AzureADUser is abandoned?  great. thanks.

**Comment by Mike-Crowley** [comment]
Yes. Here is an article with many of the announcements:

https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/azure-ad-change-management-simplified/ba-p/2967456

here is a relevant excerpt:

> if you’re using the Azure AD PowerShell or MSOnline PowerShell modules to manage Azure AD, we encourage you to try the Microsoft Graph PowerShell SDK. The Microsoft Graph PowerShell SDK continues to be where all our current and future PowerShell investments are being made. In light of the announcement to not turn off the Azure AD Graph API on June 30th, our goal is to also provide guidance and tools for migrating existing scripts and PowerShell processes, reliant on the Azure AD Graph API and MSOnline module, to the Microsoft Graph PowerShell SDK. This is due to the **planned deprecation of the two PowerShell modules (MSOL & AAD) after December 2022**.

**Comment by msewaweru** [comment]
Thanks @Mike-Crowley for your help with this issue. 

@Get-SomeCofee, thanks also for highlighting the issue. For some introductory info in Microsoft Graph PowerShell, see [Microsoft Graph PowerShell overview](https://docs.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0).

I will proceed to close this issue.
