### ISSUE TITLE
Error occurred while executing RemoveMSAdministrativeUnitMember

### ISSUE THREAD

**Issue by mdurini-swisscom** [Azure/azure-docs-powershell-azuread#861]
I tried to use the command Remove-AzureADMSAdministrativeUnitMember -Id "xx-xx-xx-xx-xx" -MemberId yy-yy-yy-yy-yy and I got this error

Remove-AzureADMSAdministrativeUnitMember : Error occurred while executing RemoveMSAdministrativeUnitMember 
Code: Request_ResourceNotFound
Message: Resource 'xx-xx-xx-xx-xx"' does not exist or one of its queried reference-property objects are not present.
InnerError:
  RequestId: zz-zz-zz-zz-zz-zz
  DateTimeStamp: Wed, 21 Sep 2022 21:21:10 GMT
HttpStatusCode: NotFound
HttpStatusDescription: Not Found
HttpResponseStatus: Completed

At line:1 char:1
+ Remove-AzureADMSAdministrativeUnitMember -Id "xx-xx-xx-xx-xx"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AzureADMSAdministrativeUnitMember], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphV10.Client.ApiException,Microsoft.Open.MSGraphV10.PowerShell.RemoveMSAdministrativeUnitMember

the two parameters are correct. I was able to remove the user from the web interface and from graph explorer.

**Comment by msewaweru** [comment]
Hi @mdurini-swisscom, I have run this cmdlet successfully.
From the error returned, the administrative unit or the member is not found. To confirm this please run;

`Get-AzureADMSAdministrativeUnit` to get the actual id of the administrative unit.

Then run:

`Get-AzureADMSAdministrativeUnitMember -Id $AdministrativeUnitID` to get the members of the unit.

You can then use `Remove-AzureADMSAdministrativeUnitMember -Id $AdministrativeUnitID -MemberID $UserID`
