### ISSUE TITLE
Get-AzureADApplicationPasswordCredential does not show password

### ISSUE THREAD

**Issue by MSIH** [Azure/azure-docs-powershell-azuread#865]
https://learn.microsoft.com/en-us/powershell/module/azuread/get-azureadapplicationpasswordcredential?view=azureadps-2.0

Do you need specific permissions to see the value of the password?

$getApplication = Get-AzureADApplication -Filter "DisplayName eq '$fullAppName'" 
 $getApplication | Get-AzureADApplicationPasswordCredential

CustomKeyIdentifier :
EndDate             : 10/12/2023 4:33:35 PM
KeyId               : xxxxx
StartDate           : 10/12/2022 4:33:35 PM
Value               :

**Comment by msewaweru** [comment]
@madansr7, assigning this to you to advise further.

**Comment by madansr7** [comment]
@MSIH , It is by design that we do not show the password value in the GET call. The only time the value of the password is shown is right after it's created using the /addPassword action.

**Comment by MSIH** [comment]
But why does your documentation state otherwise! https://learn.microsoft.com/en-us/powershell/module/azuread/get-azureadapplicationpasswordcredential?view=azureadps-2.0

If this function does not show the password, then please remove the reference from your documentation and from the library. 

"
Gets the password credential for an application.

Syntax
PowerShell

Copy
Get-AzureADApplicationPasswordCredential
   -ObjectId <String>
   [-InformationAction <ActionPreference>]
   [-InformationVariable <String>]
   [<CommonParameters>]
Description
The Get-AzureADApplicationPasswordCredential cmdlet gets the password credentials for an Azure Active Directory application.

Examples
Example 1:
PowerShell

Copy
PS C:\>Get-AzureADApplicationPasswordCredential -ObjectId 3ddd22e7-a150-4bb3-b100-e410dea1cb84

CustomKeyIdentifier :
EndDate             : 9/28/2017 3:57:10 PM
KeyId               :
StartDate           : 9/28/2016 3:57:10 PM
Value               : ZJ0V1Yg4cp4eWIey9DrYspqVdX1pdvY437P/ueGxVLU=

"

**Comment by madansr7** [comment]
@MSIH thanks for pointing this out. I've opened an issue for the docs to be updated. 
Sorry, that it caused confusion.
