### ISSUE TITLE
Get-AzureADAuditSignInLogs not bring back Last sign-in

### ISSUE THREAD

**Issue by meklulose** [Azure/azure-docs-powershell-azuread#868]
Is there a limitation to last sign-in date?  I am trying to get Last sign-in time, but some accounts are coming back blank. For example: in azure AD I can see the last sign-in date is: Last sign-in: Jun 24, 2022, 9:28 AM but when I run the following script, I do not get anything back
` Get-AzureADAuditSignInLogs -Filter "UserId eq '2491d7fb-50f9-4517-a66d-11884b368db4'" -Top 1 |
 Select CreatedDateTime, UserPrincipalName, IsInteractive, AppDisplayName, IpAddress, TokenIssuerType`

I haven't come across any article that mentions only date within certain days can be brought back by the command. It would be great if someone can clarify this.

**Comment by msewaweru** [comment]
@besiler, could you provide some infor on this issue.
