### ISSUE TITLE
'Connect-AzureAD' is not recognized as a name of a cmdlet in macOS

### ISSUE THREAD

**Issue by NoahOliva** [Azure/azure-docs-powershell-azuread#873]
***Context:***
I'm running PowerShell 7.3.1 in **macOS Ventura 13.0.1** as admin, and I want to use AzureAD module.

***Process:***
I ran the following instruction to install AzureAD module `Install-Module -Name AzureAD`

which installed fine, but the issue comes up when I want to import the module using `Import-Module AzureAD`  

what I'm getting is the next error message

> Import-Module: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

Also, when I want to connect to AzureAD with `Connect-AzureAD -AccountId [myemailaddress]` it doesn't recognize the cmdlet, and what I get is this:

> Connect-AzureAD: The term 'Connect-AzureAD' is not recognized as a name of a cmdlet, function, script file, or executable program.
> Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

<img width="1120" alt="AzureAD PS issue" src="https://user-images.githubusercontent.com/45153909/207791315-32e20694-879c-41c3-8925-b03cafe1cab3.png">

Any suggestion? Am I missing something or doing something wrong?
Please let me know. Thanks!
-Noe

**Comment by janegilring** [comment]
The AzureAD module is unfortunately not supported on platforms other than Windows.

As the AzureAD module relies on the Azure AD Graph API which is planned for deprecation, the recommendations is to start using the 
[Microsoft Graph PowerShell module](https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0) instead. This module has cross-platform support based on PowerShell 7.

**Comment by NoahOliva** [comment]
> The AzureAD module is unfortunately not supported on platforms other than Windows.
> 
> As the AzureAD module relies on the Azure AD Graph API which is planned for deprecation, the recommendation is to start using the [Microsoft Graph PowerShell module](https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0) instead. This module has cross-platform support based on PowerShell 7.
> 
> Check out [Azure AD PowerShell to Microsoft Graph PowerShell migration FAQ](https://learn.microsoft.com/en-us/powershell/azure/active-directory/migration-faq?view=azureadps-2.0) for additional information.

Thanks for the reply :) I'll try to learn and see how it works!

**Comment by msewaweru** [comment]
Thank you, @NoahOliva for raising this issue and @janegilring for your response.

I will proceed to close this issue.
