### ISSUE TITLE
Get-MsolGroupMember - duplicate syntax example and how to retrieve devices?

### ISSUE THREAD

**Issue by SpitFire-666** [Azure/azure-docs-powershell-azuread#878]
https://learn.microsoft.com/en-us/powershell/module/msonline/get-msolgroupmember?view=azureadps-1.0

Hi, looks like there's a duplicate syntax example on the page.

Also, the doco states that this cmdlet retrieves "members can be either users or groups." only.

I'm having a hard time finding a way to retrieve devices/computers from an msol group. Assuming it's possible? Perhaps a pointer on that page would help.

Cheers

**Comment by msewaweru** [comment]
Hi @SpitFire-666, thanks for reaching out.

The syntax has a small different on the parameter variants (MaxResults vs All).

Also, to get device group members, I would recommend that you use the [Microsoft Graph PowerShell module cmdlet](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.groups/get-mggroupmember?view=graph-powershell-1.0&preserve-view=true) which has this supported. Please note that the MSOnline module is planned for deprecation and we are asking users to [upgrade to the new module](https://learn.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0) replacing MSOnline.
