### ISSUE TITLE
Get password documentation in incorrect

### ISSUE THREAD

**Issue by madansr7** [Azure/azure-docs-powershell-azuread#883]
The documentation [https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0/AzureAD/Get-AzureADApplicationPasswordCredential.md](https://github.com/Azure/azure-docs-powershell-azuread/blob/live/azureadps-2.0/AzureAD/Get-AzureADApplicationPasswordCredential.md) shows the password credential value being returned. AAD does not return value of password secrets and this is causing confusion among customers. 

Looking at the following GH issue for reference. 
https://github.com/Azure/azure-docs-powershell-azuread/issues/865

**Comment by msewaweru** [comment]
Hi @madansr7, thanks for highlighting this issue. I have a PR to correct this. 

Proceeding to close this.
