### ISSUE TITLE
Add-MsolGroupMember : A parameter cannot be found that matches parameter name 'WhatIf'

### ISSUE THREAD

**Issue by uz-it** [Azure/azure-docs-powershell-azuread#931]
Parameter 'WhatIf' does not exists in Common parameters.

**Comment by csmulligan** [comment]
Hi @uz-it Azure AD Powershell is planned for deprecation on March 30, 2024. For more details on the deprecation plans, see the [deprecation update](https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/important-azure-ad-graph-retirement-and-powershell-module/ba-p/3848270). We encourage you to continue migrating to [Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/microsoftgraph/overview), which is the recommended module for interacting with Azure AD. In addition, Microsoft Graph PowerShell allows you access to all Microsoft Graph APIs and is available on PowerShell 7. For answers to frequent migration queries, see the [Migration FAQ](https://learn.microsoft.com/en-us/powershell/azure/active-directory/migration-faq?view=azureadps-2.0).

The MSOnline cmdlet: **Add-MsolGroupMember** mapped to the Microsoft Graph PowerShell cmdlet: **New-MgGroupMember** and this cmdlet has the **-WhatIf** parameter.

Hope it solves the issue. 
I’m closing this issue now, please reopen it if needed.
Thank you.
