### ISSUE TITLE
Include amount of time it may take for deactivation

### ISSUE THREAD

**Issue by josuvil** [Azure/azure-docs-powershell-azuread#94]
Hello,

I would like to recommend that we add a note to this document to state something similar as to what is stated in this article: https://support.microsoft.com/en-us/help/2619062/you-can-t-manage-or-remove-objects-that-were-synchronized-through-the-azure-active-directory-sync-tool

"Note: It may take 72 hours for deactivation to be completed. The time depends on the number of objects that are in your cloud service subscription account."

Also, a note explaining that this cmdlet should not be run as a troubleshooting step would be helpful. Thank you.

**Comment by TaraMeyer** [comment]
@josuvil,  Hello, what specific topic needs this additional information added to it?

**Comment by josuvil** [comment]
This one: https://github.com/Azure/azure-docs-powershell-azuread/blob/f0db04df6dc280dc039a5cb99e813ed90bb27d4c/Azure%20AD%20Cmdlets/MSOnline/v1/Set-MsolDirSyncEnabled.md

**Comment by RobdeJong** [comment]
Can you please provide help text for the hint not to use this as troubleshooting?

Thanks,

Rob

**Comment by josuvil** [comment]
Sure. Let's add this: "**Warning**: Running this cmdlet should not be used as a simple troubleshooting step. Careful planning should take place when enabling or disabling directory synchronization due to the ramifications this may cause to your operations."

**Comment by RobdeJong** [comment]
Hi – I added the note about the latency. Can you help me by providing some text for this?

Thanks,

Rob

**Comment by RobdeJong** [comment]
Done

Thanks,

Rob

**Comment by josuvil** [comment]
Thanks! Where can I see the changes made?

**Comment by RobdeJong** [comment]
It will take some time for the changes to be published.

Thanks,

Rob

**Comment by TaraMeyer** [comment]
@josuvil - can you confirm the changes you requested are now live so that I may close this issue?

**Comment by josuvil** [comment]
Excellent! Looks close. Thank you for your help. Please close.
