### ISSUE TITLE
Issues with "-MailEnabled" Parameter of "New-AzureADMSGroup" command

### ISSUE THREAD

**Issue by Sektorsync** [Azure/azure-docs-powershell-azuread#948]
Since about one week the "-MailEnabled" Parameter of "New-AzureADMSGroup" command in AzureADPreview PS-Module seems not more to work

If we create a mail-enabled dynamic group using the command

New-AzureADMSGroup -DisplayName <DisplayName> -Description <Description> -MailNickName <MailNickname> -MailEnabled:$true -SecurityEnabled:$true -GroupTypes "DynamicMembership","Unified" `-MembershipRule <Rule definition> -MembershipRuleProcessingState "<State>"

this Group is not available in ExchangeOnline Powershell, neither with Get-UnifiedGroup / Get-Recipient / Get-DistributionGroup, or in new EAC.

One week ago, this way of creating MailEnabled Dynamic SecurityGroups using AzureAdPreview Powershell worked without a problem.

We still use the Groups that have been created in this way, but we have to create more.

Could you please have a look int this issue?

**Comment by Sektorsync** [comment]
Hello!

This issue seems to be related to MO697570 (started December 7,2023)

========================
Users may have been unable to create Microsoft 365 Groups in multiple Microsoft 365 services
MO697570, Last updated: December 15, 2023 at 8:57 AM GMT+1
Start time: December 7, 2023 at 12:51 PM GMT+1, End time: December 15, 2023 at 3:30 AM GMT+1
========================

**Comment by csmulligan** [comment]
Hi @Sektorsync the issue seemed to be related to [MO697570](https://west.jcteams.info/jcteamsinfo/docs/MO697570.html) and it is resolved by now. 

Please be aware that Azure AD Powershell is planned for deprecation on March 30, 2024. For more details on the deprecation plans, see the [deprecation update](https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/important-azure-ad-graph-retirement-and-powershell-module/ba-p/3848270). We encourage you to continue migrating to [Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/microsoftgraph/overview), which is the recommended module for interacting with Azure AD. In addition, Microsoft Graph PowerShell allows you access to all Microsoft Graph APIs and is available on PowerShell 7. For answers to frequent migration queries, see the [Migration FAQ](https://learn.microsoft.com/en-us/powershell/azure/active-directory/migration-faq?view=azureadps-2.0).

I'm closing this issue now. Please feel free to reopen if needed.
Thank you.
