### ISSUE TITLE
New-AzureADApplicationProxyApplication generates an IdentifierUrisEndsWithSlash error

### ISSUE THREAD

**Issue by p-b--** [Azure/azure-docs-powershell-azuread#968]
I'm not sure if this is a documentation problem or an issue with the underlying cmdlet

But when running New-AzureADApplicationProxyApplication based on the documentation
```
New-AzureADApplicationProxyApplication -DisplayName "SomeName" -InternalUrl "https://internal" -ExternalUrl "https://internal-contoso.msappproxy.net/" -ExternalAuthenticationType AadPreAuthentication -ConnectorGroupId $connectorid
```

It generates an error with the code IdentifierUrisEndsWithSlash. There isn't a place to set the app identifier in the command, although the underlying graph APIs do require one without a slash. Attempting to remove the slash will also result in (another) error.

**Comment by csmulligan** [comment]
Hi @p-b-- thank you for reaching out. If you’re still facing this issue, could you please add a slash at the end of both `-ExternalUrl` and `-InternalUrl`, and let me know if this works? If not, could you please send me the cmdlet example you’re using and the exact error? Thank you!

**Comment by p-b--** [comment]
Hey -- sorry I should have followed up, about a week or two later it fixed itself. Thanks!
