### ISSUE TITLE
Set-AzureADPolicy not adding the domains

### ISSUE THREAD

**Issue by illyianayusof** [Azure/azure-docs-powershell-azuread#981]
Hi,

Currently, I'm working on a project to add external domains in Azure Entra admin center using PowerShell scripts.
The reference that I've been following is in the link I've provided below:
https://github.com/pstepien77/set-b2bmanagementpolicy

I only specifically use the function to 'Append Allow List'.
After a month of developing and testing, it has worked perfectly fine and all the tested domains were entered. However, it then stopped working. The scripts ran successfully but the function of appending the external domain did not work. In addition, I didn't edit the scripts after it has successfully entered into the whitelist.

Is it something to do with the command library of Set-AzureADPolicy? Have there been any updates or changes for it?

**Comment by csmulligan** [comment]
Hi @illyianayusof thank you for reaching out! The cmdlet Set-AzureADPolicy is an Azure AD PowerShell cmdlet, and Azure AD PowerShell will be deprecated at the end of the month:

Azure AD Powershell is planned for deprecation on March 30, 2024. To learn more, read the [deprecation update](https://techcommunity.microsoft.com/t5/microsoft-entra-blog/important-azure-ad-graph-retirement-and-powershell-module/ba-p/3848270). We recommend migrating to [Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0) to interact with Microsoft Entra ID (formerly Azure AD). Microsoft Graph PowerShell allows access to all Microsoft Graph APIs and is available on PowerShell 7. For answers to common migration queries, see the [Migration FAQ](https://learn.microsoft.com/en-us/powershell/azure/active-directory/migration-faq?view=azureadps-2.0).

You can find the equivalent Microsoft Graph PowerShell cmdlets in [this article](https://learn.microsoft.com/en-us/powershell/microsoftgraph/azuread-msoline-cmdlet-map?view=graph-powershell-1.0). If you still require any assistance with the Set-AzureADPolicy, could you please provide the exact script you’re using?
Thank you.

**Comment by csmulligan** [comment]
@illyianayusof thanks for reaching out. I'll go ahead and close this issue, and I’m hopeful that my last comment has resolved the matter. Please don’t hesitate to reach out if you require any further assistance.
Thanks again!
